### PR TITLE
public/storage or /storage ????

### PR DESCRIPTION
**Pull request by recca0120**
public/storage or /storage ????

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What we have now is correct.

**Comment by shahidnajam** [comment]
@GrahamCampbell  I agree with you.  There is no need to change storage folder.

Some programmers want to merge very stupid changes. i just don't understand them.

**Comment by recca0120** [comment]
@shahidnajam 
this's my mistake...
I wan't to upgrade my old project..
so I use git merge laravel 5.2
I found public/storage in .ignore
and I use public/storage too
maybe use public/storage folder is stupid ...
okay... it's fine....

**Comment by scrwdnet** [comment]
@shahidnajam I'm sure people don't understand why you need to make asshat comments like that. I'm sure @recca0120 had his reasons for the change at the time, perhaps something more constructive next time with a little community spirit.

**Comment by shehi** [comment]
I am with @shahidnajam on this one: tired of nonsense PRs to the repo, min 30-40 of them come in every week. Community spirit is a resource and it's bound for depletion with this kinda incidents. Don't agree? Go code Linux kernel with @torvalds .

**Comment by scrwdnet** [comment]
@shehi yes you are right there are lots of PR's, it comes with the territory of such a large and popular open source project but taking a minute or two to educate people trying to help, even if 'very' wrong, is much better than making them feel bad and putting them off trying to help in the future. Laravel has a fantastic community and it would be a shame to shun people for trying to help. I bet you weren't perfect when you first got into development and I bet you sure as hell ain't perfect now so cut people some slack for trying to do a good thing.

A PR isn't really the place for these discussions and it's probably annoying @GrahamCampbell :P sorry!

**Comment by recca0120** [comment]
@shehi you are right...
there are lots of PR's... 
maybe next time, I will find another way to get answers...

**Comment by shehi** [comment]
Too many presumptions you made there about me, @scrwdnet ! Not to mention, the point isn't about being a "wunder-kind" but being considerate towards community.

@recca0120 , that's understandable, yet a PR in no way is a method of "getting answers". There are forums for that, check laracasts.com, or better yet, stackoverflow.com for that.

**Comment by recca0120** [comment]
sorry about my bad english...
I mean I send this PR's, it too ruah...

laracasts.com or forum is better way
okay... I'm glad talk to you guys...
thanks

**Comment by scrwdnet** [comment]
Sorry I didn't mean to presume anything about you @shehi, my point was that we have all made mistakes and will continue to do so no matter how long we have been developers for.

Yes, more consideration and less snide remarks would be nice, by making a PR people are not asking to have nasty things said to them they are just trying to give back whether that be the right or wrong way.

@recca0120 yup @shehi is right plenty of places to get answers out there if you need them.

**Pull request closed without merging**
