### PR TITLE
Add database Prefix in .env

### PR DESCRIPTION
**Pull request by AhsanAbrar**
i always do this manually so i think it should be come with core.

it's really helpful for me if you approve this little contribution.

i hope it'll be helpful other's too.

Regards

### CODE REVIEW

**Comment by marktopper** [comment]
What about line [52](https://github.com/AhsanAbrar/laravel/blob/6fc79964740daa3a9ab42dd12da59c748c3d9970/config/database.php#L52) and [77](https://github.com/AhsanAbrar/laravel/blob/6fc79964740daa3a9ab42dd12da59c748c3d9970/config/database.php#L77).

**Comment by AhsanAbrar** [comment]
ohh i'm really sorry, i often used mysql that's why forgot.

let me add these too.

**Comment by GrahamCampbell** [comment]
👎 Using prefixes is very uncommon.

**Comment by yoosuf** [comment]
👎🏿 using prefix is a personalised option, if you want do it within your project

**Comment by overtrue** [comment]
👎 +1

**Comment by pheliperocha** [comment]
.env is for settings that will differ according to the environment... It does not make sense to have different prefixes for different environments..

**Comment by Mechtecs** [comment]
:-1: -1
It doesent make sense and is as stated above very uncommon.

**Comment by scoutman57** [comment]
The only argument I have for putting the prefix in the .env is that we
currently have the "database name" in the env as well. The env can change
per environment just as the db name changes. Normally the prefix is still
considered part of the database name when you are referencing the db in
general.

Again that is really the only argument I can make. I can't say it's
uncommon as I have worked with many companies and have seen it go both ways
on if they use prefixes are not.

**Comment by wangroute** [comment]
:-1:

**Comment by thosewords** [comment]
:-1:

**Pull request closed without merging**
