### PR TITLE
Add dev dependencies and rollback scripts

### PR DESCRIPTION
**Pull request by diogoazevedos**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Needs full description.

**Comment by taylorotwell** [comment]
Please re-open with a full description of what this fixes, how, etc. Thanks.

**Comment by JeffreyWay** [comment]
Laravel Mix already includes all of these script additions except Vue. They're unnecessary.

https://github.com/JeffreyWay/laravel-mix/blob/master/package.json

**Comment by diogoazevedos** [comment]
@JeffreyWay Yes, but when using Yarn they don't create the .bin folder like NPM does.

**Comment by RomainLanz** [comment]
@diogoazevedos So this is not the problem of Laravel if `yarn` doesn't install correctly the dependencie.

**Comment by diogoazevedos** [comment]
@RomainLanz Yarn install all dependencies correctly, it just don't create the `.bin` folder like NPM does, and this make the things blow up if the command you are using isn't in dependencies (or global).

**Comment by JeffreyWay** [comment]
We have a different fix incoming that doesn't require laravel/laravel to re-declare those dependencies that are requested by Mix.

**Pull request closed without merging**
