### PR TITLE
[5.0] Use $errors->any() instead of count($errors) > 0

### PR DESCRIPTION
**Pull request by Landish**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
If it ain't broke, don't fix it. The current code is just fine.

**Comment by franzliedke** [comment]
I agree with @Landish that the default skeleton should promote best practices.

**Comment by GrahamCampbell** [comment]
Depends what you consider a best practice.

**Comment by franzliedke** [comment]
Well, since Laravel boasts how expressive it is right on its homepage, I know what I would choose. ;)

**Comment by Landish** [comment]
@GrahamCampbell  So, you're saying that, this `count($errors) > 0` is better than this `$errors->any()`?

> If it ain't broke, don't fix it.

I don't agree with you on this, but whatever. I tried to make my favorite php framework a *little* more better, but...

**Comment by GrahamCampbell** [comment]
> So, you're saying that, this count($errors) > 0 is better than this 

No, I'm saying it's not worth arguing over.

**Pull request closed without merging**
