### PR TITLE
Update database.php

### PR DESCRIPTION
**Pull request by ZachAlanMueller**

### CODE REVIEW

**Comment by ZachAlanMueller** [comment]
good

**Comment by lukasgeiter** [comment]
Looks like it's time to change your password :smile:

**Comment by Zkynet** [comment]
haha!

**Comment by ZachAlanMueller** [comment]
So new to this and I f'd up so badly. Hah.

**Comment by GrahamCampbell** [comment]
I'd recommend storing the password in the .env file. That way, you can't accidentally commit it. :)

**Pull request closed without merging**
