### PR TITLE
[8.x] Add `app.mix_url` and `MIX_URL`

### PR DESCRIPTION
**Pull request by crynobone**
With Laravel Octane, you will serve Laravel routes using Octane and public content including assets require separate Nginx, Apache web-server, etc.

Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Comment by driesvints** [comment]
MIX_ env variables are made available in JS by default. Does this conflict with that somehow? Where exactly do you need this?

**Comment by paras-malhotra** [comment]
@driesvints, the [Mix docs](https://laravel.com/docs/8.x/mix#custom-mix-base-urls) advise to do this and I have it in many of my apps. There aren't any issues with conflicts.

**Comment by taylorotwell** [comment]
laravel/vapor-core already assumes an `MIX_URL` environment variable convention for this. We should probably stick with that.

**Comment by crynobone** [comment]
@taylorotwell sure, but I think we should also update the docs for recommended environment variable too

**Comment by crynobone** [comment]
https://laravel.com/docs/8.x/mix#custom-mix-base-urls

**Comment by crynobone** [comment]
Updated.

**Review by GrahamCampbell — APPROVED** [review]

**Review by driesvints — APPROVED** [review]

**Pull request closed without merging**
