### PR TITLE
Typo fix on services.php

### PR DESCRIPTION
**Pull request by OzanKurt**
My editor also converted tabs to spaces somehow.

### CODE REVIEW

**Comment by taiyaei** [comment]
That'd be your editor that did that, GitHub doesn't just change the formatting.  Change them back to tabs please.

**Comment by taiyaei** [comment]
Also looking at the typo fix, I believe "sane" was intentional.

**Comment by OzanKurt** [comment]
Using spaces instead of tabs also match with the PSR-2 Coding Standards which Laravel also uses.

**Comment by RomainLanz** [comment]
Laravel doesn't follow PSR-2.

**Comment by taiyaei** [comment]
Laravel does not follow PSR-2 currently like @RomainLanz said.

http://laravel.com/docs/5.0/contributions#coding-style

You will be happy to hear (and most if not all of us) that with 5.1 it'll be PSR-2 (at least I believe that is still the plan).

**Comment by OzanKurt** [comment]
:cry:

**Comment by taiyaei** [comment]
Could you close this @OzanKurt? Thanks for your help though!  If Laravel was PSR-2 then this would've helped. :)

**Comment by OzanKurt** [comment]
How do i do that? :D

**Comment by ft23** [comment]
@OzanKurt ah be ozan bi iyilik yapayım dedin hor gördüler seni

**Comment by OzanKurt** [comment]
Abi bu kadar cirkeflik olmaz ya :D Alti ustu katkimiz olsun dedik.

**Comment by ft23** [comment]
Birgün değerini anlıcaklar ama çok geç olcak :)

**Pull request closed without merging**
