### PR TITLE
[5.1 LTS] Pick up changes from the 5.2 branch

### PR DESCRIPTION
**Pull request by vlakoff**
* There are some fixes in there, although the main idea is to reduce differences with 5.2, in order to ease for users future migration from 5.1 to 5.2 (5.3...)
* I have taken note of all the relevant PRs and commits, but the list is long... just ask if you have any question.
* I've spent some time on this, so please do not close within 30 seconds.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'm pretty sure these changes were intentionally not merged into 5.1.

**Comment by GrahamCampbell** [comment]
Yeh, there's nothing here that needs backporting/

**Comment by thowmas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thnghm@gmail.com
    Domain typeshape.com has exceeded the max emails per hour (1/1 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:54724 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by whm01.mammoth.net.au with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aSRYO-0002qn-Kj
	for tom@typeshape.com; Mon, 08 Feb 2016 02:47:17 +1100
Date: Sun, 07 Feb 2016 07:46:30 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1454859990;
	bh=nWdkAcSjX8T0cKWoHuD9OY7Fxii3frZJi41ew9VfmUA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Cxu6epGDu28XbWPzVqJleoFkOBOu3PA7+Ho7isC2YBJ3miPPDJhtC/ENU5fbWVsqX
	 pLG8/fOLIsP2Krd+Uz2aDo1J/wiPtyKg+2sIWOkTneqC7oAQ93cIx/b9GxwFFJpVGO
	 vPobkZJX5YK2WYsm6L1PRT6PAj1cR2f3QTKEQ+q0=

**Comment by GrahamCampbell** [comment]
@thowmas Please fix this. Your spam on all our PRs is unacceptable.

**Comment by vlakoff** [comment]
You should at least consider #3635.

**Comment by GrahamCampbell** [comment]
I'll ask Taylor if he's ok with it being backported.

**Comment by thowmas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  thnghm@gmail.com
    Domain typeshape.com has exceeded the max emails per hour (1/1 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:44302 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by whm01.mammoth.net.au with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aSSCh-0007Zi-2b
	for tom@typeshape.com; Mon, 08 Feb 2016 03:28:56 +1100
Date: Sun, 07 Feb 2016 08:28:09 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1454862489;
	bh=LpHoVhZZzISZ3G68Z7ctPrfz6RnrANU/sqsJJGUhyXQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xn386BeTz/z24EO4NF0/yPv3qrmhH4VeD8a7ddP2oGXYOz8yfnYJwwH42EZcoUhQS
	 FCsKwIbgnPPGFYx/N8Ki3/4Z5XRv6aSp1vI9/lTFAbNzUKxyuDV6KI2lL3kyjK9Hj6
	 iIAggpJ3SiAU1hwIqW+dcVbbUUOG+DEipM6MumLE=

**Pull request closed without merging**
