### PR TITLE
Bump cross-env version.

### PR DESCRIPTION
**Pull request by mvdnbrk**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks but we prefer to let @JeffreyWay handle this.

**Comment by CaddyDz** [comment]
@mattstauffer welcoming community you say?

**Comment by mattstauffer** [comment]
I most certainly do. In fact, I gave a whole talk about it. Why, exactly, are you tagging me here about it? Does Laravel having a process for who is responsible for certain steps or pieces of the code make it not welcoming? Does Dries’ tone not appreciate enough gratitude for you? I’m honestly unable to understand what this has to do with being welcoming or not.

**Comment by driesvints** [comment]
I'm sorry if was a little blunt about this. Definitely didn't mean to be. It's just that Jeffrey has been updating our front-end dependencies every time a new mix version has come out. It's always been this way. Definitely don't take this personally.

**Pull request closed without merging**
