### PR TITLE
Upgrade laravel-mix to 0.8.3

### PR DESCRIPTION
**Pull request by kossa**
Upgrade laravel-mix from 0.8.1 to 0.8.3 after successful testing

### CODE REVIEW

**Comment by joshmanders** [comment]
Mix is on v0.8.8...

**Comment by GrahamCampbell** [comment]
This pull request literally does nothing anyway.

**Comment by joshmanders** [comment]
Thanks, Obama!

**Comment by pdhayes** [comment]
``

**Pull request merged**
