### PR TITLE
[5.8] Modify RedirectIfAuthenticated middleware to accept multiple guards

### PR DESCRIPTION
**Pull request by Te7a-Houdini**
Same as #3685 , this will allows to

```php
Route::get('foo', 'Foo@foo')->middleware('guest:web,api');
```

### CODE REVIEW

**Comment by gpressutto5** [comment]
Why redirecting an api request?

**Comment by Te7a-Houdini** [comment]
@gpressutto5  it's just an example , but in real case scenarios we maybe doing this

```php

Route::get('admins-only-login-form', 'AdminController@loginForm')->middleware('guest:admin,moderators,users');
```

**Comment by taylorotwell** [comment]
Why did you also change the redirect URL?

**Comment by Te7a-Houdini** [comment]
@taylorotwell sorry changed by mistake

**Comment by tomhorvat** [comment]
@taylorotwell @Te7a-Houdini 

Does this break 'guest' middleware? I'm able to access /login on clean 5.8-dev install without redirect...

Tested on valet, twice.

**Pull request merged**
