### PR TITLE
[5.8] Update number of Laracasts videos

### PR DESCRIPTION
**Pull request by ryandon83**
Commit updates the number of available Laracasts videos. As of this writing there are 1506 videos.

### CODE REVIEW

**Comment by antonkomarev** [comment]
Maybe it's better to rephrase this sentence to not update it all the time?

**Comment by ludo237** [comment]
Over 1400 is still correct, old PR were closed because the sentence is still correct even with 1506 videos

**Comment by GuidoHendriks** [comment]
Maybe only update at values like 1500/2000.

**Comment by ryandon83** [comment]
Perhaps update now because 1500 is a nice rounded number? Once 2000 is reached, the sentence can be reworded to "Laracasts contains thousands of video tutorials on a range of topics including Laravel, modern PHP, unit testing, and JavaScript." This wording would probably be just as impressive as an actual number. Otherwise, 500 level increments sounds good to me.

**Pull request merged**
