### PR TITLE
[11.x] Refresh Database in Tests

### PR DESCRIPTION
**Pull request by Jubeki**
Due to the changes in `.env.example` were you use session and cache tables, you also need to migrate the database.

What is your opinion on including the `LazilyRefreshDatabase` Trait into the General TestCase by default?

### CODE REVIEW

**Comment by driesvints** [comment]
Not really a fan of requiring mysql for the default test suite run... wondering if we can tackle this differently.

**Comment by Jubeki** [comment]
Taylor changed the defaults in https://github.com/laravel/laravel/commit/feded74d9eea2cde9715b75412ae8e5a5342f52d

So now you are requiring some kind of database for the default skeleton.
SQLite would probably then be the only alternative.

**Comment by Jubeki** [comment]
Or even better use the `:memory:` option from sqlite, then you don't really have a database.

**Comment by driesvints** [comment]
I think @nunomaduro's PR #6297 might be a better alternative here. Thanks!

**Comment by Jubeki** [comment]
That is also an option! Thanks for the fast response.

**Pull request closed without merging**
