### PR TITLE
[6.0] Remove timestamp from create_failed_jobs_table file

### PR DESCRIPTION
**Pull request by arubacao**
Remove timestamp from `create_failed_jobs_table` file.
From:
`2019_08_19_175727_create_failed_jobs_table.php`
To:
`2019_08_19_000000_create_failed_jobs_table.php`

### CODE REVIEW

**Comment by deleugpn** [comment]
Why?

**Comment by driesvints** [comment]
There's no reason to do this imo.

**Comment by arubacao** [comment]
It makes it more consistent with existing migrations in this repo and looks cleaner.

**Comment by fitztrev** [comment]
@driesvints @deleugpn that's how [the other 2 migrations](https://github.com/laravel/laravel/tree/b7d2b48b75afbaa34c82688cb30be2f00a7d8c57/database/migrations) were named in f4a2282e4eccfe875f9785bd8c0e7f5d8030c563

**Comment by driesvints** [comment]
Okay I'll reopen this to see what Taylor says.

**Pull request merged**
