### PR TITLE
Update DatabaseSeeder.php

### PR DESCRIPTION
**Pull request by shankitkumar**

### CODE REVIEW

**Comment by shankitkumar** [comment]
gfhfg

**Comment by shankitkumar** [comment]
fghfghdfhggfh hfg

**Comment by ankurk91** [comment]
Sometimes i feel shame to be an Indian. :(

**Comment by ovac** [comment]
Interesting!

**Comment by ovac** [comment]
I guess he's just having fun though!

**Comment by samundra** [comment]
Why is this still open?

**Comment by MichaelDeBoey** [comment]
@samundra It's weekend, so give @taylorotwell a break 😉

**Comment by GuidoHendriks** [comment]
Move along, nothing to see here. It's not hurting anyone, will be closed soon enough. 🙃

**Comment by a-komarev** [comment]
Merge it please, such a great addition we have waited for so long! Can't wait to see it's live! :1st_place_medal:

**Comment by insign** [comment]
Whata? Is this a timeline of sarcasm that am I having difficulty get in?

**Comment by pavinthan** [comment]
No one here without beginner state, teach them if you know, please don't tease.

**Comment by gabrielinbuon** [comment]
@shankitkumar gfhfg..

Can't find the meaning... is that variable issue or logical issue? :D

**Pull request closed without merging**
