### PR TITLE
[5.7] Update log config: 30 daily + easy overwrite channel for dev

### PR DESCRIPTION
**Pull request by bertheyman**
As per request [here](https://github.com/laravel/laravel/pull/4767):

- Default max daily logs to 30
- Easily overwrite the channel for dev environment

### CODE REVIEW

**Comment by laurencei** [comment]
If this was accepted - you would want to update `.env.example` with the name there, so people could see it more obviously it could be updated.

**Comment by bertheyman** [comment]
Good idea! I've updated my pull request.

**Comment by taylorotwell** [comment]
Eh, I don't really agree with this change. The LOG_STACK in practice could be multiple drivers (an array).

**Comment by bertheyman** [comment]
Ok, thanks for the feedback!

**Pull request closed without merging**
