### PR TITLE
Update welcome route to use the new Route::view() method

### PR DESCRIPTION
**Pull request by mdavis1982**
Now that we have the new `Route::view()` method, should we update the Welcome route to use this since it's only function is to return a view?

Happy for this to be closed if it's not preferable to update it, but thought it might make it clear that this is now possible 😄

### CODE REVIEW

**Comment by decadence** [comment]
Here we go again
https://github.com/laravel/laravel/pull/4391

**Comment by MehediDracula** [comment]
Duplicate of

#4310
#4367 
#4378 
#4381 
#4386

**Comment by MehediDracula** [comment]
Lots of PR for this :laughing:

**Comment by mdavis1982** [comment]
Hadn't seen the other ones! I'll close this 😄

**Comment by joshmanders** [comment]
Can we get a `CONTRIBUTING.md` file added so that a notice that this is not needed can be added... We're at 50+ PR's for this.

**Pull request closed without merging**
