### PR TITLE
Update AppServiceProvider.php

### PR DESCRIPTION
**Pull request by ruhul0**
Fixing the issue of getting database migration error for string length.

### CODE REVIEW

**Comment by scoutman57** [comment]
👎

**Comment by antonkomarev** [comment]
Related #4239 #4488 #4774

**Comment by nunomaduro** [comment]
IMO: https://github.com/laravel/laravel/pull/4774#issuecomment-425057845.

**Comment by michaeldyrynda** [comment]
Doesn’t belong in the default app. Better to update your mysql install 😅

**Comment by driesvints** [comment]
Heya, please see the other closed prs about this which are linked above.

**Comment by bioudi** [comment]
Found a solution here 
https://laravel-news.com/laravel-5-4-key-too-long-error

**Pull request closed without merging**
