### PR TITLE
Update CreatesApplication.php

### PR DESCRIPTION
**Pull request by Mickey248**

### CODE REVIEW

**Comment by arthurkirkosa** [comment]
Because hacktoberfest?

**Comment by KristofMorva** [comment]
That only starts in October I think. Also, Laravel has got many useless PRs before this also, so it's not a surprise.

**Comment by michaeldyrynda** [comment]
Irrespective, the change wouldn't pass a lint check

**Comment by Mickey248** [comment]
thankyou foe comment

**Comment by valdevweb** [comment]
I dont follow this thread and i receive all the e-mails

**Pull request closed without merging**
