### PR TITLE
[5.0] Use pseudo boolean notation

### PR DESCRIPTION
**Pull request by lucasmichot**
Now available with https://github.com/laravel/framework/pull/6667

### CODE REVIEW

**Comment by taylorotwell** [comment]
Not really necessary I don't think?

**Comment by rosemalejohn** [comment]
When is the official release of laravel 5?

**Comment by RomainLanz** [comment]
@rosemalejohn I think it's not the right place to ask this question.... however Taylor already answer to that question a lot of time, a little of search is not bad!

**Comment by Hikkijp** [comment]
@GrahamCampbell :+1: :+1: :+1: :+1: :+1: :+1: 
Can't wait for tomorrow to come.  :smile:

**Comment by rosemalejohn** [comment]
Thanks for the replies.

**Pull request closed without merging**
