### PR TITLE
Remove Mandrill from list of supported email providers

### PR DESCRIPTION
**Pull request by ssfinney**
Considering that Mandrill's entry was removed from `config/services.php` in d998b5bd0392f76dcaa461fdec919658947c2e65, shouldn't we go ahead and remove Mandrill from the list?

P.S. I tried to get the formatting consistent with d998b5bd0392f76dcaa461fdec919658947c2e65, but please correct me if you feel the list should be formatted differently.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, since we've not removed the mandrill driver?

**Comment by GrahamCampbell** [comment]
@taylorotwell why did you remove it from the services anyway?

**Comment by nacr-dev** [comment]
Yes why? The service has chanced but mailchimp paid users can still use mandrill.

**Comment by ssfinney** [comment]
I'm just advocating for consistency. I have no problem keeping Mandrill in the services file.

**Comment by GrahamCampbell** [comment]
Mandrill is not at all dead. I guess they just want to improve their deliverability and lower the spam going through their service.

**Pull request closed without merging**
