### PR TITLE
Fix controller constructors, they must call parent's method

### PR DESCRIPTION
**Pull request by theravel**
I want to be able to add any logic to base controller's constructor, so that it must be executed

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Then just do that in your application!? No need to put it in the skeleton app in my opinion.

**Comment by GrahamCampbell** [comment]
@lukasgeiter I disagree. This looks like a good default to me.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
This might need to go into develop instead though. Ping @taylorotwell.

**Comment by taylorotwell** [comment]
You can't include these unless the base controller actually includes a constructor I believe. But, yes, would also go to develop branch.

**Pull request closed without merging**
