### PR TITLE
[5.7] Remove the home directory from all controllers, and middlewares.

### PR DESCRIPTION
**Pull request by GabMic**
To be honest, every time i make a fresh install of laravel, the first thing i do is to remove the `home` directory from all controllers. people do not use `/home`, they use just `/` like 99.999% of sites worldwide.
This will save some time, and make it more reasonable.

### CODE REVIEW

**Comment by driesvints** [comment]
`/` is already reserved for your landing page. `/home` is the page where you end up when you login, register, etc...

**Comment by m1guelpf** [comment]
While I'm against removing /home for /, I'd say /dashboard is a much common url. Should I do some research on the usage of both and submit another PR for consideration?

**Comment by driesvints** [comment]
@m1guelpf yeah I agree but `/home` is now the default and what people are used to. It's also the default used in Spark, etc. So changing it would mean people having to figure out why it changed and it's not worth the hassle imo.

**Comment by GabMic** [comment]
Well, the fact it is (along with the controller, routes) for auth users, and no user is existing after the auth command, it is really unnecessary. 
The landing page should be removed after running the auth command, as it is generating a new home view. that view should be visible from the main path `/`, and of course not be for only authenticated users. you can see this in probably 99.999% of projects, sites web apps etc'.
All this will simplify workflow and save some time for everyone on a fresh install.

**Comment by narwy** [comment]
> / is already reserved for your landing page. /home is the page where you end up when you login, register, etc...

No way.

I agree with removing `/home` it's better to have it all as `/`

**Comment by driesvints** [comment]
> All this will simplify workflow and save some time for everyone on a fresh install.

Well, yeah but this will save time for yourself and others who agree with you but not for others who prefer the current approach. They'll have to make the changes every time they use a fresh Laravel install. It's just an opinion on how the auth behavior should be.

**Comment by narwy** [comment]
`/home` is nothing related do a dashboard, to be honest why even restructure a route to display something so simple.

I agree with all the changes to make it `/` or even `/dashboard`

**Comment by hulkur** [comment]
Make it configurable, with default `/home` to preserve current state

**Comment by GabMic** [comment]
That's what i am saying. I think the majority of people do not use this imo. As evidence, i really don't see any site practically using this path.

**Comment by ludo237** [comment]
What about `/private` ... 

I mean the choice are almost infinite how do you decide? Maybe @hulkur is right but again, it's literally a 4 letter replace DIY

**Comment by taylorotwell** [comment]
No changes planned here.

**Pull request closed without merging**
