### PR TITLE
Reuse the bindings alias

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎

**Comment by taylorotwell** [comment]
By convention we usually just list the full class name up there. It actually never occurred to me that you could use the shorter form. 😆  ... will just keep it classes for now to be consistent. 👍

**Comment by GrahamCampbell** [comment]
Using the longer form is much better because you can immediately know what it is that's actually running, and jump to the code.

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: V4DjeoX0t9You can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0007  You can check the status of or update this ticket online at: http://you.8ball.me

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: rmFq58OxS3You can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0008  You can check the status of or update this ticket online at: http://you.8ball.me

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: oN717lq5lTYou can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: eb1vQRCjjwYou can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0009  You can check the status of or update this ticket online at: http://you.8ball.me

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0010  You can check the status of or update this ticket online at: http://you.8ball.me

**Pull request closed without merging**
