### PR TITLE
Update ModelFactory.php

### PR DESCRIPTION
**Pull request by mstfsysl**
needless comma.

### CODE REVIEW

**Comment by overtrue** [comment]
👎

**Comment by jsRuner** [comment]
.....哈哈，有意思。就更新了一个符号

**Comment by mstfsysl** [comment]
How can i delete this pull request? I am new at github, my aim is to learn how it works, sorry.

**Comment by GrahamCampbell** [comment]
Don't worry about it. :)

Our code style is to have trailing commas in arrays.

**Comment by mstfsysl** [comment]
Thank you :)

2017-05-11 17:12 GMT+03:00 Graham Campbell <notifications@github.com>:

**Pull request closed without merging**
