### PR TITLE
[5.7] Fixes a small grammar error in public/index.php

### PR DESCRIPTION
**Pull request by robbyrice**
:grinning:

### CODE REVIEW

**Comment by taylorotwell** [comment]
It breaks the spacing 😱

**Comment by robbyrice** [comment]
So, this is a no go then?

**Comment by shirshak55** [comment]
@robbyrice taylor don't want to break space so why don't you move 'info' to upper and add it :P

**Comment by robbyrice** [comment]
@shirshak55 not quite sure I understand what you mean.

**Comment by shirshak55** [comment]
@robbyrice  something like 

|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it into
| script here so that we don't have to worry about manually
| loading any of our classes later on. It feels great to relax.
|
*/

**Comment by robbyrice** [comment]
Oh ok, I see. However I'm not going to move forward with this, so feel free to create a new Pull Request if you would like.

**Comment by shirshak55** [comment]
@robbyrice yeah i am also not going because taylor may say it don't add any value to framework which is correct IMHO :)

**Comment by samundra** [comment]
Besides, Taylor is very strict about 3 character thing, IYKWIM.

**Pull request closed without merging**
