### PR TITLE
Remove obsolete driver option

### PR DESCRIPTION
**Pull request by u01jmg3**

### CODE REVIEW

**Comment by serpentblade** [comment]
Spotted this in release notes.  the "apc" cache driver is still active and functional, despite the historic APC extension no longer functioning in PHP 8.  The driver still works with the APCu extension.

**Comment by u01jmg3** [comment]
The `apc` driver appears to have been a casualty of the [slimming exercise](https://github.com/laravel/laravel/pull/6188).

- Last appears here: [`428a190`](https://github.com/laravel/laravel/commit/428a190#diff-1add210cb1f30d8f14eb2d3934d64fbfd8dec0a7823dc746c6136fc8e0c3da2f)
- Does not reappear again here: [`96508d4`](https://github.com/laravel/laravel/commit/96508d4#diff-1add210cb1f30d8f14eb2d3934d64fbfd8dec0a7823dc746c6136fc8e0c3da2f)

I simply aligned things by removing the comment for a driver that's no longer present.

**Comment by serpentblade** [comment]
@u01jmg3 Thanks for that explanation.  Very curious that it was removed as it is still a very useful cache, but I see a lot was cut from configs.  🤷

**Comment by u01jmg3** [comment]
Although there was a slimming exercise done here, the core set of configs over in laravel/framework has no such requirement.

Maybe try a PR over there to see if it can be reinstated? Hard to know what was intentional and what might have been an oversight.

**Pull request merged**
