### PR TITLE
[8.x] Anonymous migrations

### PR DESCRIPTION
**Pull request by driesvints**
This implements anonymous migrations from https://github.com/laravel/framework/pull/36906 for the skeleton.

### CODE REVIEW

**Comment by crynobone** [comment]
If we want to do this, shouldn't we bump the minimum `laravel/framework` to `^8.37`?

**Comment by driesvints** [comment]
@crynobone I did that?

**Comment by crynobone** [comment]
@driesvints ahh missed that

**Comment by taylorotwell** [comment]
Hmm - I'm not sure if we should change this on a patch release of the skeleton. Could their be tooling out there that depends on the migration class names?

**Comment by driesvints** [comment]
I don't know myself but we can definitely postpone to 9.x to be sure.

**Comment by taylorotwell** [comment]
OK let's retarget to master.

**Comment by driesvints** [comment]
Sent to https://github.com/laravel/laravel/pull/5590

**Pull request closed without merging**
