### PR TITLE
Update gulpfile.js

### PR DESCRIPTION
**Pull request by aleixfabra**
Error: Entry module not found: Error: Can't resolve 'buble'

### CODE REVIEW

**Comment by taylorotwell** [comment]
The answer is not to remove this from the gulpfile.

**Comment by aleixfabra** [comment]
I know, but I could find where to create an issue. So I decided to show it in that way.

**Comment by JeffreyWay** [comment]
Submit your issue on the laravel/elixir repo instead.

**Comment by aleixfabra** [comment]
Ok!

**Comment by abachmann** [comment]
I had the same issue. You just need to install the latest node.js version.

**Pull request closed without merging**
