### PR TITLE
add config parameter for mysql unix socket

### PR DESCRIPTION
**Pull request by yangqi**
spent quite some time to figure out how to connect to mysql through unix socket in laravel, hope this would help

### CODE REVIEW

**Comment by verheesj** [comment]
Is this config param implemented in Laravel core?

**Comment by GrahamCampbell** [comment]
This should just be added to our docs, but I think it already is?

**Comment by yangqi** [comment]
can you point me where in the docs, I couldn't find it.

**Comment by GrahamCampbell** [comment]
> can you point me where in the docs, I couldn't find it.

It's likely it needs adding then. Could you send a pull please.

**Comment by yangqi** [comment]
Sure, will do.

**Comment by lury** [comment]
actually the same is true for 'port' - it doesn't exist in default configuration and .env file but it should
```			
'port'		=> env('DB_PORT', 3306),
```

**Pull request closed without merging**
