### PR TITLE
[5.8] Updates dev dependencies versions.

### PR DESCRIPTION
**Pull request by mvdnbrk**

### CODE REVIEW

**Comment by mnabialek** [comment]
What's the reason to make those changes? As far as I know newest versions will be automatically installed when running `npm install` so there's no point to update them here.

**Comment by ankurk91** [comment]
Laravel does not supply a `lock` file and `^` caret sign already allow you to install latest (non breaking) version

**Comment by mnabialek** [comment]
In addition I believe there is no Bootstrap 4.3.1 yet :)

**Comment by taylorotwell** [comment]
As others have noted, these versions will already be installed I believe.

**Pull request closed without merging**
