### PR TITLE
[11.x] Add DB_ENGINE config

### PR DESCRIPTION
**Pull request by mhfeizi**
This adds DB_ENGINE environment variable.

### CODE REVIEW

**Comment by MrPunyapal** [comment]
this will be helpful ☑️

**Comment by balu-lt** [comment]
It should be just `env('DB_ENGINE')` because `null` is already there by default.

**Comment by saturnphp** [comment]
yeah good idea

**Comment by mhfeizi** [comment]
https://github.com/laravel/framework/pull/50620

**Pull request closed without merging**
