### PR TITLE
Use double quotes for html attributes

### PR DESCRIPTION
**Pull request by tonglil**
For consistency.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
5.0 is no longer maintained. Only security fixes will reach 5.0.

**Comment by tonglil** [comment]
Gotcha, is master 5.1?

**Comment by GrahamCampbell** [comment]
Yeh, and develop is 5.2. :)

**Comment by tonglil** [comment]
:+1:

**Comment by tonglil** [comment]
Does master get pulled up into develop (aka I don't need to make a PR for develop if this is in master already).

**Comment by GrahamCampbell** [comment]
No, we always merge changes up to the newest branches. :)

**Comment by tonglil** [comment]
Thanks, no more questions!

**Pull request closed without merging**
