### PR TITLE
Fix Laravel Start for PHPUnit

### PR DESCRIPTION
**Pull request by laurencei**
@GrahamCampbell - will this fix the issue for https://github.com/laravel/laravel/pull/4228?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This won't work, because we can't define a constant more than once.

**Comment by laurencei** [comment]
yeah - was just thinking that...

even using 'is_defined' wont work - because we need to re-define it for each test?

**Comment by taylorotwell** [comment]
I don't think we need to be sweating over this. There isn't even a clear reason to use the constant and if someone has one they can make the file themselves.

**Comment by laurencei** [comment]
@taylorotwell - the constant is used by lots of packages. 

https://github.com/barryvdh/laravel-debugbar is the most popular.

So @GrahamCampbell is right - there are going to be side effects...

**Comment by arcanedev-maroc** [comment]
I think it's wise to keep the old `bootstrap/autoload.php` file because:

 * It's a breaking change for many packages that uses the `LARAVEL_START` constant.
 * Useful for the `old` shared hosting that doesn't gives you the php.ini to edit and if you want to solve issues like this:

```php

<?php 
// bootstrap/autoload.php
ini_set('xdebug.max_nesting_level', 500); // To fix the `Maximum function nesting level of 'xxx' reached, aborting!`


define('LARAVEL_START', microtime(true));
```

**Comment by GrahamCampbell** [comment]
> ini_set('xdebug.max_nesting_level', 500); // 

No point in that. The new default in xdebug is large enough anyway.

**Comment by arcanedev-maroc** [comment]
I talking about the `old` shared hosting.

**Comment by GrahamCampbell** [comment]
Meh, I'm massively against adding that for old shared hosting. Use better hosting, or fix it yourself would be my approach. No reason to have xdebug in production (in most cases anyway).

**Comment by arcanedev-maroc** [comment]
Yeah, tell that to the "Client" :)

**Pull request closed without merging**
