### PR TITLE
Consistency between files.

### PR DESCRIPTION
**Pull request by RomainLanz**
Align correctly all lines to be consistent with other files.

### CODE REVIEW

**Comment by lukasgeiter** [comment]
:-1:

**Comment by RomainLanz** [comment]
@lukasgeiter Maybe better to argument why is this bad instead of just write a thumb down...

Other files align their lines, we need to be consistent between them, so we have 2 options:
 1. Remove space in every files.
 2. Align in every files.

**Comment by lukasgeiter** [comment]
@RomainLanz I don't think it's bad but I personally prefer not to align them. So the thumbs down is just my opinion. However the majority of config files are not aligned so I'd rather remove those spaces. Except maybe for the long lists in `app.php`, for those it kind of makes sense...

**Comment by RomainLanz** [comment]
@taylorotwell What do you think about removing alignement in other files except `app.php`?

**Pull request closed without merging**
