### PR TITLE
Assist code-completion with `@var $factory` PHPDoc

### PR DESCRIPTION
**Pull request by tomlankhorst**
Corresponds to [this PR](https://github.com/laravel/framework/pull/27793)

### CODE REVIEW

**Comment by tomlankhorst** [comment]
Why would StyleCI reject PHPDoc style comments?

**Comment by antonkomarev** [comment]
Such PRs were merged at least 2 times before and then were rolled back and I don't understand why.

Personally what I'm doing after each new Laravel installation - changing `database/factories/UserFactory.php` file

```php
/* @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(App\User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm', // secret
        'remember_token' => str_random(10),
    ];
});
```

**Comment by ludo237** [comment]
Same as @antonkomarev 

I don't know why it got removed but I manually update my factories with that

**Comment by taylorotwell** [comment]
No plans to add this right now.

**Pull request closed without merging**
