### PR TITLE
Add hover effect to links

### PR DESCRIPTION
**Pull request by vinkla**
Added a hover color to links in the welcome view.

screen shot 2017-01-29 at 1 26 56 pm

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hm, no plans to add this right now.

**Comment by vinkla** [comment]
Why not? User feedback is quite common.

**Comment by rodymol123** [comment]
I, for one, think it looks zonda 👍

**Comment by goodnesskay** [comment]
lool. nice one @vinkla

**Comment by Thielo** [comment]
@vinkla User Feedback is important, thats true. But no real "user" is supposed to see this fresh installed Laravel Welcome page.

**Comment by vinkla** [comment]
@Thielo I see developers as users.

**Pull request closed without merging**
