### PR TITLE
Remove .env files from versioning

### PR DESCRIPTION
**Pull request by m1guelpf**
This change will protect enviroment files like .env.local .env.prooduction .env.remote from versioning

### CODE REVIEW

**Comment by marky291** [comment]
You are assuming such files will exist.

**Comment by m1guelpf** [comment]
@marky291 It's common to have a .env.production and if some of that files doesn't exist, noting happens.

**Comment by frezno** [comment]
imho no need for this.
It's up to the user to add or delete some files which may or may not have an affect on gitignore. But that's up to the user in this case.
Otherwise you might have to add eg a manual.md file and a changelog file etc. as well since those might be added by the user as well.

**Comment by thecodemill** [comment]
FYI, whilst not always practical, it's recommended NOT to use .env.production files, or even the .env file itself on production servers. Such config options should be passed to the environment from the server configuration to reduce overhead - https://github.com/vlucas/phpdotenv#usage-notes

**Comment by marky291** [comment]
Laravel is built to use .env even for production.

**Pull request closed without merging**
