### PR TITLE
Add vscode config to .gitignore

### PR DESCRIPTION
**Pull request by kossa**

### CODE REVIEW

**Comment by huenisys** [comment]
Hi kossa,

I think they are promoting having these files on a .gitignore_global instead. I saw previous requests like this. Honestly, they better go there.

Relevant article here: https://davidwalsh.name/global-gitignore

**Comment by driesvints** [comment]
Please use a global `.gitignore` for project specific things: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by lightingcoders** [comment]
use .gitignore_global

**Comment by kossa** [comment]
Thank you for your infos :)

**Pull request closed without merging**
