### PR TITLE
Using app name from .env file

### PR DESCRIPTION
**Pull request by soufyanekaddouri**
Using app name from .env file instead of configuration file

### CODE REVIEW

**Comment by DojoGeekRA** [comment]
@soufyanekaddouri you can't fetch values from `env` function after you do a `php artisan config:cache` (which is the case of every deployed app).

[Here](https://laravel.com/docs/5.4/configuration#configuration-caching) is the reference in the documentation.

**Comment by al0mie** [comment]
I guess app name and locale are different things.

**Comment by taylorotwell** [comment]
Correct, we are not supposed to fetch using env outside of configuration files since they are cached.

**Comment by GrahamCampbell** [comment]
> Correct, we are not supposed to fetch using env outside of configuration files since they are cached.

Yes. This is VERY important. Laravel doesn't actually load the environment variables when config is cached.

**Pull request closed without merging**
