### PR TITLE
Update ForgotPasswordController.php

### PR DESCRIPTION
**Pull request by Mickey248**

### CODE REVIEW

**Comment by clarkeash** [comment]
@Mickey248 whats the reason for this?

**Comment by jmanzo** [comment]
I did understood the change done!

**Comment by taylorotwell** [comment]
Is this a Hacktoberfest thing?

**Comment by jmanzo** [comment]
@taylorotwell I think yes

**Comment by gileswells** [comment]
@taylorotwell if you mark it spam then they don't get credit for it.

**Comment by m1guelpf** [comment]
@taylorotwell If you add the invalid label it doesn't count.

**Pull request closed without merging**
