### PR TITLE
Added Laravel Favicons

### PR DESCRIPTION
**Pull request by OzanKurt**
I think every fresh laravel install will look much more pretty now.

### CODE REVIEW

**Comment by taiyaei** [comment]
Having a favicon directory with a ton of different sizes is maybe too much IMO, especially since Laravel is now moving towards opt-in for the scaffolding soon: https://github.com/laravel/framework/commit/c0fb560d139e5ec77780bc5a1c2229e5da909462

I guess we'll see what Graham or Taylor think about this.

**Comment by OzanKurt** [comment]
@taiyaei Hey mate! 

> This pull request contains merge conflicts that must be resolved.

What does this mean?
My laravel fork is still at 4.2.* :D

**Comment by GrahamCampbell** [comment]
This is meant to be a default app structure. Why would people want laravel favicons?

**Comment by martindilling** [comment]
I would actually like a default favicon, not all the possibilities, but just the one that's showing as the browser tab icon.  
A favicon is usually some of the last things I look at, so for me it would be nice with a default to make the tab more recognizable. But if that's the purpose of it, then I think the default favicon should be something different from the laravel.com one ;)

If it's only one simple favicon, then I can't see the harm in it, I would probably see it more as a reminder for me to take care of ;)

**Comment by aprillins** [comment]
@graham because most of people see the favicon first before they read the
tab on their browsers I think

On Tue, Mar 24, 2015 at 5:17 PM, Martin Dilling-Hansen <
notifications@github.com> wrote:

> I would actually like a default favicon, not all the possibilities, but
> just the one that's showing as the browser tab icon.
>
> A favicon is usually some of the last things I look at, so for me it would
> be nice with a default to make the tab more recognizable. But if that's the
> purpose of it, then I think the default favicon should be something
> different from the laravel.com one ;)
>
> If it's only one simple favicon, then I can't see the harm in it, I would
> probably see it more as a reminder for me to take care of ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/laravel/pull/3311#issuecomment-85435997>.
>



-- 
*Iskandar M.*
Tel: +6282133358000
BB Pin: 217F7E9E
(GMT+07:00) Bangkok, Hanoi, Jakarta

**Comment by GrahamCampbell** [comment]
> because most of people see the favicon first before they read the tab on their browsers I think

Why would you want to see a laravel favicon, for a laravel application? The fact that your application is made with laravel is totally irrelivent to the user.

**Comment by barantr90** [comment]
:+1: @GrahamCampbell

**Comment by aprillins** [comment]
But it's totally relevant for me while I develop the application. I love beautiful appearance. :laughing:

**Comment by martindilling** [comment]
@GrahamCampbell if that's the argument, then why have the welcome page that say Laravel? ;)

And as I tried to say, it's not something you need for your finished application of cause, but a favicon could make it easier to find the right tab xD This is usually how my browser looks like 
tabs

**Comment by BogdanBartis** [comment]
@martindilling The welcome page is there to let you know the framework was installed correctly. A blank page or no page at all would not be very reassuring.

**Comment by graham** [comment]
Hi everyone,

I think you meant @GrahamCampbell not @graham.

Looks like an awesome project!

Graham Abbott

**Comment by GrahamCampbell** [comment]
@BogdanBartis The point is that we don't want people to forget to change the icon and have their app having the default icon.

**Comment by forkiven** [comment]
Does anyone else have trouble running 'composer update'? I'm getting errors even on a fresh install of laravel :/

**Comment by javiereguiluz** [comment]
@GrahamCampbell one minor issue associated with not defining a default favicon is that some browsers may request the `/favicon.ico` file, generating a 404 error in the application.

**Comment by GrahamCampbell** [comment]
@javiereguiluz Hmmm, really? I thought we had a default 0 byte file there?

**Comment by GrahamCampbell** [comment]
We do: https://github.com/laravel/laravel/blob/master/public/favicon.ico.

**Comment by GrahamCampbell** [comment]
How are you getting error 404?

**Comment by javiereguiluz** [comment]
@GrahamCampbell I was referring to not having the `favicon.ico` file. But it's true that this problem doesn't occur when using the 0 byte favicon trick. Excuse me for the noise.

**Comment by rossedman** [comment]
:-1: I think leaving the application structure as blank as possible for front end is best.

**Comment by juukie** [comment]
Agree with @rossedman. No need for a Laravel favicon.

**Comment by crynobone** [comment]
I don't think this is a wise idea, what if someone ignore changing the favicon and just have a production code using Laravel logo. 

Especially when @taylorotwell does really care about Laravel Trademark and has been chasing people who use Laravel logo as their product/app/services logo before.

**Comment by GrahamCampbell** [comment]
Yeh, totally agree.

**Comment by paulrose** [comment]
Expecting users to update 25 different favicons would be a crazy idea. Definitely not something the framework should handle. The framework is supposed to be a blank slate for people to start developing, not something pre-branded.

This should be closed to stop the back and forth from people.

**Comment by overtrue** [comment]
:-1:

**Pull request closed without merging**
