### PR TITLE
add root .htaccess

### PR DESCRIPTION
**Pull request by yuchonghua**

### CODE REVIEW

**Comment by decadence** [comment]
Just point your DOCROOT to `public` folder

**Comment by devilsafe** [comment]
nginx php7.2 is ok for this wonderful job?

**Comment by yuchonghua** [comment]
In fact, many virtual host operators do not support modifying the root directory, they need their own vps, and the purchase price of vps is 10 times that of the virtual host.

**Comment by michaeldyrynda** [comment]
There are multiple VPS providers (Vultr, Linode, Digital Ocean) with hosting for as little as $2.50 per month. What virtual host are you paying 25c a month for?

**Pull request closed without merging**
