### PR TITLE
Add font path variable

### PR DESCRIPTION
**Pull request by ahmed3mar**

### CODE REVIEW

**Comment by rodymol123** [comment]
Pretty sure most people do not use the fonts from the bootstrap-sass directory...

**Comment by marky291** [comment]
Currently Laravel cannot find the font files, causing an error on version 0.6 for mix.

See my comment here;
https://github.com/laravel/laravel/commit/6574b9dd759e5e89735f1ba3bcbfbf4aa114cec7

**Comment by taylorotwell** [comment]
@JeffreyWay wasn't something like this already closed before?

**Comment by Dominoli** [comment]
@taylorotwell Yes: https://github.com/laravel/laravel/pull/4109

**Comment by marky291** [comment]
How can it be closed and still be an issue ?

Only affects 0.6 not 0.5?

**Comment by taylorotwell** [comment]
We'll have to wait on @JeffreyWay to weigh in. I don't maintain Mix.

**Comment by JeffreyWay** [comment]
@taylorotwell  So it looks like setting the icon-font-path is standard procedure for Webpack projects that use Bootstrap.

https://github.com/jtangelder/sass-loader/issues/133

I've tested this commit, and it works perfectly. Can we merge it?

**Comment by marky291** [comment]
All working again, thanks guys :D

**Comment by vedmant** [comment]
The problem is actually with relative paths, in Laravel Mix 0.6 they stopped working. All resource paths now starts with node_models, when I need to include my own image from resources, I need to write something like this:

```
~/../resources/images/tooltip/tooltip1.png
```

**Comment by marky291** [comment]
I just use url ('/images/backgroundo.png') ?

Works fine now.

**Comment by marky291** [comment]
Place images folder inside scss folder for example above

**Comment by vedmant** [comment]
@marky291 Thanks, actually now it works if I just put images to public/images and refer them like url (/images/backgroundo.png), it didn't work with Mix 0.5 version.

**Comment by vedmant** [comment]
Anyway, now I wanted to import datatables styles from "~datatables.net-dt/css/jquery.dataTables" it fails, because it can't resolve relative images path `* ../images/sort_both.png` how to handle it now, there is variable to change path to images.

**Pull request merged**
