### PR TITLE
update welcome.blade.php

### PR DESCRIPTION
**Pull request by vitorleonel**
Change hard coded url home to named route

### CODE REVIEW

**Comment by SOSTheBlack** [comment]
Nice

**Comment by taylorotwell** [comment]
No plans to add this in case they don't have the named route.

**Comment by rodurma** [comment]
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Console/stubs/make/routes.stub#L4

**Comment by abidihoussem** [comment]
Bfri9jnei9h3io0ih9
rsoij0rtiupn44tiokrtguij54gioj45tjoi45ioj45uij45enijtybipnjttbjipntrgiijnrtijnprtjinrtg



U43FJIREG90IJR4GOI0JR4FNKOPRFGNK0OXV9OH 6GERT7BFRYEUO HBFIG HIFBGHIFBG  U
IHG UIVHUH  FHFU9

**Pull request closed without merging**
