### PR TITLE
Create a shortcut for artisan command when using windows

### PR DESCRIPTION
**Pull request by xxnoobmanxx**
Just an alternative for windows users to execute 'artisan' command without 'php' prefix

### CODE REVIEW

**Comment by jhoff** [comment]
FWIW, the actual artisan command isn't executable by default so mac / linux users have to type `php artisan` too...

**Comment by zaknes** [comment]
Yeah I don't see many benefits of doing this unless we add one for Mac / Linux users, too.

Just create an alias.

**Comment by xxnoobmanxx** [comment]
It is just something cool I've found in composer installation for windows... 
Not sure how it would be implemented for other OS

**Comment by taylorotwell** [comment]
Holding off on this.

**Comment by onbjerg** [comment]
Shouldn't ``chmod +x artisan`` make it executable? On macOS and Linux it would read the shebang to understand that it's a PHP file.

**Pull request closed without merging**
