### PR TITLE
Remove clear-compiled from pre-install

### PR DESCRIPTION
**Pull request by antonioribeiro**
If your application is somehow broken (you have a missing class, for instance), you won't be able to `composer update` because, well, your application is broken and composer is trying to call your application...

http://i.imgur.com/v2sUx5w.png

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
As discussed in https://github.com/laravel/framework/issues/9660, we really need a better way to do this.

**Comment by garygreen** [comment]
@GrahamCampbell you are closing these issues but agreeing that something needs to change to improve it... May I suggest than we at least re-open #9660 until Taylor has a chance to see the proposed standalone command and discuss improvements/possibilities in fixing the issue? Closing it is only giving the impression that 'it won't be fixed'

**Comment by GrahamCampbell** [comment]
I'll talk to Taylor about this outside of github. Easier that way.

**Comment by mvdstam** [comment]
@GrahamCampbell Also very much not transparant and not giving the impression that this is taken seriously.

Also: Simply saying "Taylor doesn't like the idea" and then closing the issue without any further explanation is simply stupid and rude. Do you even _want_ people to contribute?

**Comment by GrahamCampbell** [comment]
> Also very much not transparant

This is just how we deal with issues.

**Comment by GrahamCampbell** [comment]
Just be patient. Taylor is actually current on holiday.

**Comment by gmsantosxl** [comment]
In this kind of situations I simply run `composer update --no-scripts`. 

Usually `artisan clear-compiled` works again after that.

**Comment by GrahamCampbell** [comment]
> In this kind of situations I simply run composer update --no-scripts. 

Same here, but that situation isn't ideal for automated deployments.

**Comment by GrahamCampbell** [comment]
I tell you what, I'll make a new issue for this.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/9678.

**Comment by progmars** [comment]
I too was using `--no-scripts` workaround as a last resort, but it does not work for `require` command:
`"--no-scripts" option does not exist`

So no way to disable scripts when you want to add a new package.

**Pull request closed without merging**
