### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by muba00**

### CODE REVIEW

**Comment by imabug** [comment]
[PSR 2](http://www.php-fig.org/psr/psr-2/).2 - The closing ?> tag MUST be omitted from files containing only PHP.

**Comment by overtrue** [comment]
👎

**Comment by muba00** [comment]
@imabug Thank you for information.

**Comment by GrahamCampbell** [comment]
> tag MUST be omitted from files containing only PHP.

The reason for this is because if you accidently put a newline after the closing tag in a php file, then php will start sending the request to the client.

**Comment by fengchenghao** [comment]
@GrahamCampbell LOL. It makes sense. Thank you for your explanation!

**Pull request closed without merging**
