### PR TITLE
APP_NAME variable for Application Name

### PR DESCRIPTION
**Pull request by abixalmon**
Added APP_NAME environment variable for Application Name in config/app.php

### CODE REVIEW

**Comment by mateusjatenee** [comment]
I particularly don't find this very interesting as the app's name is not
going to change very often.
Em sáb, 18 de fev de 2017 às 02:48, Abi Narayan <notifications@github.com>
escreveu:

**Comment by overtrue** [comment]
-1

**Comment by mrkatz** [comment]
It might not change often, however it would be useful to have a central location to declare the app name and be refrenced from there

**Comment by astierler** [comment]
I agree that while not very useful, it does kind of make it more consistent to the rest of the app config settings. (Or if deploying the same Laravel app for multiple different sites - not saying I've done this, but can't hurt)

**Comment by GrahamCampbell** [comment]
This has already been proposed. Just edit the config files for your app. They're there to be edited after all, otherwise we'd not include them in the app structure by default.

The env variables are for environment specific variables, such as your database password, and not for things specific to your application.

**Comment by GrahamCampbell** [comment]
> however it would be useful to have a central location to declare the app name and be refrenced from there

We already have this, from the config file. You should never try to read env variables outside of config files in laravel, because of config caching, and php threading bugs.

**Pull request closed without merging**
