### PR TITLE
[10.x] Add favicon to welcome page

### PR DESCRIPTION
**Pull request by milwad-dev**

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure this is totally necessary for the splash page, but if we add it it would go to `10.x` branch as we've done a new splash page there.

**Comment by milwad-dev** [comment]
@taylorotwell 
You mean add this pr after Laravel ```10.x``` splash page publish?

**Comment by milwad-dev** [comment]
@taylorotwell 
Ok, I add PR after new splash page.

**Pull request closed without merging**
