### PR TITLE
[5.3] Make the Authenticate middleware throw an AuthenticationException

### PR DESCRIPTION
**Pull request by JosephSilber**
This PR is part of [this change](https://github.com/laravel/framework/pull/13651), so that we can [unify unauthenticated responses](https://github.com/laravel/framework/pull/13113).

### CODE REVIEW

**Comment by taylorotwell** [comment]
This can't be merged without solution for redirect URI.

**Comment by JosephSilber** [comment]
@taylor currently, we ship [the full response logic](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/Authenticate.php#L24) in laravel/laravel, and allow people to tweak it there.

Can't we do the same here? Ship the whole `unauthenticated` method in laravel/laravel, and allow people to tweak it inline.

**Comment by taylorotwell** [comment]
Sure, change the PR to do that

**Comment by JosephSilber** [comment]
@taylorotwell should we make the base exception handler an abstract class, and create an abstract `unauthenticated` method on it?

**Comment by taylorotwell** [comment]
I don't see any need for that really.

**Comment by taylorotwell** [comment]
Just do what we said a few comments ago.

**Comment by JosephSilber** [comment]
@taylorotwell done.

**Pull request merged**
