### PR TITLE
Add the DisableFloc middleware

### PR DESCRIPTION
**Pull request by tobiasthaden**
This adds a middleware that sets the `Permissions-Policy` header, to disable FloC.

This PR is more a start of a discussion on how we as the Laravel Community think about `Google's Federated Learning of Cohorts`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think this is probably something better suited as a package.

**Comment by tobiasthaden** [comment]
@taylorotwell A package or adding this to the framework itself doesn't have the same effect as this is built in the app. It is more about taking a position.

**Comment by ondrejmirtes** [comment]
I've started a discussion about this with a bit more context here: https://github.com/laravel/ideas/issues/2576

**Comment by taylorotwell** [comment]
@tobiasthaden would you mind resending this... I am unable to reopen it. I just read more about this issue.

**Pull request closed without merging**
