### PR TITLE
adding lock files to .gitignore

### PR DESCRIPTION
**Pull request by yamenarahman**
I think these files should be placed there.

### CODE REVIEW

**Comment by crynobone** [comment]
No, this is a project skeleton repo, no a library.

**Comment by yamenarahman** [comment]
@crynobone sorry can't get you, why no ?

**Comment by GuidoHendriks** [comment]
You can do this is your own project. But I have no idea why you’d want to... On composer for example: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by yamenarahman** [comment]
@GuidoHendriks Thanks.

**Pull request closed without merging**
