### PR TITLE
Preserve colors

### PR DESCRIPTION
**Pull request by tillkruss**
I like seeing the colors, makes it easier to scan.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Nice one.

**Comment by alish00** [comment]
nice
[ساندویچ پانل](https://mammut-group.com/)

**Comment by phanan** [comment]
A similar PR was submitted here https://github.com/laravel/laravel/pull/4635 and closed by @taylorotwell and @GrahamCampbell for (IHMO) valid reasons. By forcing `--ansi` we're basically removing the ability to force `--no-ansi`, which can be useful in certain cases (OTOMH: debug, poor console support, color accessibility). In short, this decision should be users' to make, not Laravel.

**Comment by tillkruss** [comment]
‪Isn't it enough to just remove it for users who need to use --no-ansi? My guess would be that's less than 1%.

**Comment by phanan** [comment]
I'm not sure what you mean by "removing it for users who need to use `--no-ansi`," nor do I have the number to back either of the arguments up. I guess the key point here is (according to linked PR) `--no-ansi` will always be overriden by `--ansi` thus makes it impossible for users to disable colors.

**Comment by antonkomarev** [comment]
@phanan this changes located in `laravel\laravel` repository - what means in your application, and not hardcoded in framework. So you are free to change `composer.json` file to fit your requirements.

**Comment by phanan** [comment]
👍 I guess it shouldn't be a big deal. Thanks for listening to my rant 😄

**Pull request merged**
