### PR TITLE
File created for SQLite database

### PR DESCRIPTION
**Pull request by anteriovieira**
File created for those who want to use SQLite database. Thus we need only set DB_CONNECTION as environment variable.

### CODE REVIEW

**Comment by leandrorosendo** [comment]
:+1:

**Comment by jorgemurta** [comment]
That file existed in Laravel 4.
The community surelly had a reason to delete it I think

**Comment by leandrorosendo** [comment]
I used here and it worked , please inform the reason of this file delete in Laravel 4 . thank's

**Comment by taylorotwell** [comment]
It's just simple to create one if needed.

**Comment by anteriovieira** [comment]
It makes sense, thank you.

**Pull request closed without merging**
