### PR TITLE
[Proposal] Set `pretend` via env as well

### PR DESCRIPTION
**Pull request by alnutile**
This would allow setting to change on different servers as needed eg CI server, dev, prod, local etc.

Maybe `driver` makes this not a concern?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Seems a bit overkill to add everything. It's pretty easy for people to add this themselves if they want it. It's up to Taylor though.

**Comment by taylorotwell** [comment]
I kinda think it's better to use the `log` driver actually for these situations. I'm kind of wondering if we can deprecate `pretend` mode.

**Comment by GrahamCampbell** [comment]
> I'm kind of wondering if we can deprecate pretend mode.

:+1: for doing that in 5.1. :)

**Comment by alnutile** [comment]
Makes a lot of sense. Pretend seemed kind of redundant to me.

**Comment by ibrasho** [comment]
:+1: for doing that in 5.1

**Pull request closed without merging**
