### PR TITLE
[6.x] DRY up path to /home

### PR DESCRIPTION
**Pull request by taylorotwell**
We were defining this path in six places (!).

### CODE REVIEW

**Comment by Lloople** [comment]
Maybe a method would be better, like the `redirectTo()` in Auth Controller, in case someone needs to build this value with some logic

**Comment by tontonsb** [comment]
I agree to @Lloople  that `RouteServiceProvider::home()` would be more versatile. But I'll gladly take this PR over the current state!

**Comment by sierrafayad** [comment]
Would it be ok if the `RedirectsUser` trait have access to the `RouteServiceProvider`? Instead of the config file I was proposing when modifying the framework. This way it could retain the actual functionality of the function and property `redirectTo` using the HOME constant from the ServiceProvider but letting you define the function redirectTo as you like

**Comment by sertxudeveloper** [comment]
> Maybe a method would be better, like the `redirectTo()` in authentication controllers, in case someone needs to build this value with some logic

This solution uses the Route Service Provider, if someone needs to add some logic to the home route, like me, we could use a custom service provider or helper to return the proper string in the controllers we need it.

**Comment by Lloople** [comment]
@sertxudeveloper You mean replacing all code occurrences of `RouteServiceProvider::HOME` by `RouteServiceProvider::getHomeRoute()` or something like that? If that's the case and we can already do this replacement for `/home` why we need a PR like this?

**Comment by sertxudeveloper** [comment]
@Lloople Yes, I would have no problem in modifying it with a personalized method in the places where I need it.

**Comment by taylorotwell** [comment]
@Lloople you can still override the `redirectTo` methods as needed.

**Comment by dionysiosarvanitis** [comment]
Still prefer a [named route](https://github.com/laravel/laravel/pull/4657) for this.

**Comment by marchershey** [comment]
How does this benefit?

> @Lloople Yes, I would have no problem in modifying it with a custom method in the places where I need it.

Yeah, but what's easier... changing the $redirectTo or changing the $redirectTo & service provider?

--

Is this change documented anywhere so I can read up on the benefits? Thanks

**Comment by martindilling** [comment]
@taylorotwell 
> @Lloople you can still override the `redirectTo` methods as needed.

I would very much prefer the `redirectTo` method being the only way to define this. Can't see a reason for it to be a property with check for the existence of the method. 
If it's just a method, it's allows for using both a plain url, route name or anything you want out of the box. But as it is now, if you "just" want to use a route name, you can't just change the value in 7 places, you have to remove a property, and add a new method in 7 places ;)

**Pull request merged**
