### PR TITLE
Update .gitignore to add .idea folder

### PR DESCRIPTION
**Pull request by vineethkrishnan**
Added .idea directory to gitignore. 
Sometimes it gets pushed to the repository by accident.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This should be added to your system .gitignore file, and not your app's.

**Comment by Oxicode** [comment]
> Added .idea directory to gitignore.
> Sometimes it gets pushed to the repository by accident.

I like it. I prefer to add ".idea" in the global .gitignore file. But nobody does it.

**Comment by GrahamCampbell** [comment]
People will only do it if we people stop adding it to projects.

**Comment by lk77** [comment]
you can change this file in your project

**Comment by GuidoHendriks** [comment]
It's even debatable wether or not you should ignore the whole folder. See GitHub's suggested `.gitignore` and the referenced link to JetBrains' website:

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Pull request closed without merging**
