### PR TITLE
Less static usage of routes

### PR DESCRIPTION
**Pull request by djanse**

### CODE REVIEW

**Comment by robclancy** [comment]
wtf hahahah

**Comment by ollieread** [comment]
Why did you not just recommit to the previous PR you made?

Besides that, what exactly are you trying to solve?

**Comment by djanse** [comment]
Hi ollieread,

I did not recommit to the previous RP because I have no clue how to do this on github.com

Futher the only thing im trying to solve is a little readability within IDE's which support PHPDoc:

screenshot_3

**Comment by GrahamCampbell** [comment]
You can change this to whatever you want in your own app.

**Comment by bbashy** [comment]
Should be default.

**Comment by robclancy** [comment]
Should definiately not be default hahahahaha. Best PR ever.

**Pull request closed without merging**
