### PR TITLE
Update 2014_10_12_000000_create_users_table.php

### PR DESCRIPTION
**Pull request by TheEVIL**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't right is it?

**Comment by StelianAndrei** [comment]
Maybe **username ** would be a better idea? Many websites this day offer the user the ability to login either by username or email

**Comment by lucasmichot** [comment]
:+1: for `username`

**Comment by pespantelis** [comment]
@StelianAndrei :+1:

**Comment by youchenlee** [comment]
:+1: for  `username`

**Comment by overtrue** [comment]
:+1: for `username`

**Comment by vlsoprun** [comment]
:+1: for username

**Comment by arrilot** [comment]
Is there any code in laravel/framework repo that depends on this `name` field? If so this change can lead to some annoying problems.

**Comment by shehi** [comment]
-1 for username.

**Comment by anteriovieira** [comment]
Username make sense, but rather keep name. This does not prevent implement the rules to save the name of User in this column since the name is of user.

**Comment by ChadTaljaardt** [comment]
@shesi +1

**Pull request closed without merging**
