### PR TITLE
Fix break from #4226

### PR DESCRIPTION
**Pull request by joshmanders**
https://github.com/laravel/laravel/pull/4226 removes `bootstrap/autoload.php` and breaks `artisan`. This PR fixes `artisan` to work.

### CODE REVIEW

**Comment by laurencei** [comment]
You need to also add `define('LARAVEL_START', microtime(true));` in there as well

**Comment by GrahamCampbell** [comment]
👎 Other PR should be reverted. It breaks phpunit tests too.

**Comment by joshmanders** [comment]
Good catch there @GrahamCampbell, I'll update this PR to fix that too.

**Comment by GrahamCampbell** [comment]
Already send a revert PR. It's the best fix for the issue.

**Comment by GrahamCampbell** [comment]
No point in removing the existing file. It did a perfect job.

**Comment by GrahamCampbell** [comment]
PHPUnit is broken in the sense that the constant doesn't get defined there.

**Comment by joshmanders** [comment]
No use keeping a single file that requires `vendor/autoload.php` only..

**Comment by joshmanders** [comment]
I just did a search of the codebase (quickly using find in files) and `LARAVEL_START` is only ever defined, never used...

**Comment by laurencei** [comment]
@joshmanders - yes, but current packages/apps will be expecting it to be there.

**Comment by joshmanders** [comment]
Good point @laurencei

**Comment by laurencei** [comment]
@joshmanders - one option though is to define it in the CreatesApplication trait? That would solve the problem.

**Comment by joshmanders** [comment]
I thought about that, but seems hacky.

**Comment by joshmanders** [comment]
I guess I'll leave PR open and see what @taylorotwell says.

**Comment by DojoGeekRA** [comment]
@joshmanders i'm very curious about what is the purpose of `LARAVEL_START`, what is it used for?

**Comment by laurencei** [comment]
@DojoGeekRA - it is a constant that marks the start of the Laravel Application.

Although not directly used by Laravel itself - it is available for developers/packages etc to determine performance/run times etc.

**Comment by DojoGeekRA** [comment]
Thanks @laurencei!

**Pull request merged**
