### PR TITLE
Upgrade to Mix v6

### PR DESCRIPTION
**Pull request by JeffreyWay**
This PR upgrades Laravel Mix to v6. 

The update to `package.json` should be all that we need here, but we should also take a look at some of the presets. 

- **Upgrade Guide**: https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md
- **Changelog**: https://github.com/JeffreyWay/laravel-mix/blob/master/CHANGELOG.md

I've also made a PR to the docs.

https://github.com/laravel/docs/pull/6705

### CODE REVIEW

**Comment by driesvints** [comment]
So clean 😍

**Comment by pavinthan** [comment]
is still `cross-env` required in Laravel level ?

**Comment by driesvints** [comment]
I think we can drop it now, can't we @JeffreyWay?

**Review by ZeProf2Code — APPROVED** [review]

**Review by GrahamCampbell — APPROVED** [review]
🚢 🎄

**Comment by dinhquochan** [comment]
🎉🎉

**Review by kayobruno — APPROVED** [review]

**Comment by febrihidayan** [comment]
I've been waiting for this to be able to use Vue.js 3

**Comment by jeff-browne** [comment]
'mix' is not recognized as an internal or external command,

```
 MINGW64 /e/wamp64/www/Laravel8Projects/Laravel_Livewire_JetStream_Projects/jetstream_blog
$ npm run dev

> @ dev E:\wamp64\www\Laravel8Projects\Laravel_Livewire_JetStream_Projects\jetstream_blog
> npm run development


> @ development E:\wamp64\www\Laravel8Projects\Laravel_Livewire_JetStream_Projects\jetstream_blog
> mix

'mix' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs21-01-18T13_22_31_264Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs21-01-18T13_22_31_295Z-debug.log
```
Screenshot_1

**Comment by driesvints** [comment]
@jeff-browne please try a support channel and don't use PR's to post support requests, thanks.

**Pull request merged**
