### PR TITLE
Update Controller.php

### PR DESCRIPTION
**Pull request by JustSteveKing**
Making the default controller `abstract` as it is only ever extended not used directly

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@driesvints this is just a small paper-cut that seems to trigger me 😆

**Review by localheinz — COMMENTED** [review]
👍

**Comment by a-bashtannik** [comment]
I don't think this should be merged. Nothing blocks from using `\App\Http\Controllers\Controller` as a single controller with a couple of methods. There is an abstract parent behind this class, which defines some default mechanics, but this class can be used as fully working thing with the single responsibility.

**Comment by danharrin** [comment]
@a-bashtannik 99% of people would never do that. If you want to, that's fine, there's nothing stopping you from removing the `abstract`. It's userland code.

**Comment by taylorotwell** [comment]
I'm working on *a lot* of skeleton changes for 11.x - will lump this into that. 👍

**Pull request closed without merging**
