### PR TITLE
[5.3] Update autoload.php

### PR DESCRIPTION
**Pull request by mayoz**
See https://github.com/laravel/framework/pull/14564

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. I'm not too sure this is a good idea though.

**Comment by GrahamCampbell** [comment]
How does it compare performance wise?

**Comment by GrahamCampbell** [comment]
Doesn't PHP cache file_exists calls?

**Comment by mayoz** [comment]
@GrahamCampbell frankly, don't tested it. Perhaps, no effect on performance. Yes, PHP cache yet it but just think it's unnecessary. The solution is very simple :)

**Comment by vlakoff** [comment]
Probably breaking as the `compiled.php` can be missing during dev, and I'm pretty sure there is no performance gain.

**Comment by taylorotwell** [comment]
Would be breaking.

**Pull request closed without merging**
