### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by siturra**

### CODE REVIEW

**Comment by insign** [comment]
Since when Laravel uses JSON in his languages files?

**Comment by siturra** [comment]
https://laravel.com/docs/5.6/localization#defining-translation-strings

**Comment by insign** [comment]
As I understand, it is optional for heavy applications. And probably won't
be a part of the default framework.

**Comment by siturra** [comment]
have you with your decisions, every Latin American that downloads the framework must translate at each project start.

**Comment by antonkomarev** [comment]
Then they could use this package: https://github.com/caouecs/Laravel-lang

**Comment by taylorotwell** [comment]
No plans to add translations out of the box. The community can distribute them.

**Comment by insign** [comment]
They could, but never wanted. Maybe to leave the project as small as
possible.

>

**Pull request closed without merging**
