### PR TITLE
Version info on welcome page

### PR DESCRIPTION
**Pull request by Laraveldeep**
Version info on welcome page is useful after fresh install for new comers without going through artisan to check.

### CODE REVIEW

**Comment by CaddyDz** [comment]
I give 90% odds @taylorotwell would close this

**Comment by vzool** [comment]
@CaddyDz I think if it designed better you may change your mind :)

**Comment by m1guelpf** [comment]
@Laraveldeep I think this still has a chance if you only display major version (i.e. Laravel 5.4) istead of full version (i.e. 5.4.30)...

**Comment by Laraveldeep** [comment]
No issues guys if rejected. 

Just a thought and giving it a try. Welcome page is already well designed.

**Comment by dpde** [comment]
I don't see any benefit in this.
What is wrong with having a look into the composer.json and composer.lock files?

**Comment by okanlawonema** [comment]
It's a good one, it could be place at the footer right corner

**Comment by Laraveldeep** [comment]
Nothing wrong with having a look at compoer.json or artisan. If we can display that on the welcome page.. that could save some time for new comers (at least that's what I think).

If you think about about it, whole blog posts have been dedicated to this topic it the past... How to check my Laravel version. :)

**Comment by Laraveldeep** [comment]
Liked the suggestion by @okanlawonema 

Made new PR. Original design intact with small version info below Laravel text. :)

**Pull request closed without merging**
