### PR TITLE
Remove unguard call

### PR DESCRIPTION
**Pull request by JosephSilber**
It's now done in the seeder command: https://github.com/laravel/framework/pull/10474

### CODE REVIEW

**Comment by crynobone** [comment]
Remove unused import?

**Comment by shehi** [comment]
Why this was merged? Those lines actually were exactly what taught me how to use unguard and reguard features without even checking the docs. IMHO they should've just been commented out, instead of direct removal.

**Comment by veelasky** [comment]
+1 with shehi.

**Comment by dryhurstroberts** [comment]
+2

On Mon, Oct 5, 2015 at 12:47 AM, Rifki Alhuraibi <notifications@github.com>
wrote:

> +1 with shehi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/laravel/pull/3511#issuecomment-145452176>.
>



-- 
-- 
Jonathan P Dryhurst Roberts
jonathan.dryhurst@gmail.com
US: 562-230-5691
UK: 07402 852 007

**Comment by benjamincrozat** [comment]
Same here: *why* mass assignment restrictions should be enabled when seeding the database?

**Comment by arrilot** [comment]
They are not enabled now. Please read the Joseph's comment

**Comment by benjamincrozat** [comment]
Yes sorry. It's much better like that.

**Comment by shehi** [comment]
@arrilot : Oops, sorry, missed that as well. -1 [retracting my question] :)

**Pull request merged**
