### PR TITLE
[7.x] Adds collision's phpunit adapter

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request adds of the **collision's phpunit adapter** to the default Laravel 7 skeleton. This adapter provides two things:

- Better console visuals on tests failures
- Always stops on failure

1. Here a simple comparasion with the default phpunit output ( on the left ) against collision ( on the right ).

Screenshot 2020-01-22 at 22 32 09

2. Things get even better on complex examples, as collision focuses on what really matters - hidden vendor frames, and others:

Screenshot 2020-01-22 at 22 59 33

Let me know what do you guys think. 👍

### CODE REVIEW

**Comment by mpociot** [comment]
The adapter, unfortunately, does not respect the "stopOnFailure" setting.
In my example, I have two failing tests. Without the listener, the output looks like this:

image

As you can see, I get both failures.

With the listener added, PHPUnit immediately stops after the first failure:

image

**Comment by mfn** [comment]
It's also kind of weird when your tests within an IDE primarily, e.g. phpstorm.

It's not really necessary there because you can one-click right into the failed test anyway.

Additionally, when multiple test fails it only shows it from a single test (the first?) so not sure how useful.

I think that should be an explicit user choice if they want so.

**Comment by gocanto** [comment]
though it looks awesome and clean, I personally prefer the errors stack.

**Comment by crynobone** [comment]
Anyway to have this skipped for certain request? E.g running from CI shouldn't stop on first error or failure

**Comment by deleugpn** [comment]
As a CLI user, this looks AMAZING. I dont use phpstorm to run my tests, so I do want this today!! Is it compatible with Laravel 6? Is it easy to disable for CI? Our CI env already expects the original output for reporting purposes, but on a day to day developer experience, I never knew I needed this until I saw it!

**Comment by nunomaduro** [comment]
Very valuable feedback so far. I am up to update the listener to meet the needs we all have - so don't hesitate on explaining what you would like have instead. Example: `only activate the listener when the flag  --stop-on-failure is used`.

**Comment by driesvints** [comment]
@nunomaduro might want to update your original comment to reflect that

**Comment by voyula** [comment]
👎

**Comment by taylorotwell** [comment]
@nunomaduro so what is the status here? Have some changes been made? If so, can you update us here on what they were?

**Comment by nunomaduro** [comment]
Closing this pull request. Something even better is coming soon. Thanks for all the valuable feedback. ❤️

**Pull request closed without merging**
