### PR TITLE
Use const and destructuring assignment

### PR DESCRIPTION
**Pull request by diogoazevedos**
Is a good practice use `const` with `require` and more elegant use destructuring assignment.

### CODE REVIEW

**Comment by RomainLanz** [comment]
We should also remove semicolon, but it's another story

**Comment by taylorotwell** [comment]
It doesn't matter.

**Comment by taylorotwell** [comment]
Jeffrey says its fine so I will merge I guess.

**Comment by JeffreyWay** [comment]
const sucks.

**Pull request merged**
