### PR TITLE
Updated welcome page route

### PR DESCRIPTION
**Pull request by Advaith3600**
Latest version of Laravel now has `Route::view()` method. So what is the need of using the old long way to just show the view?

### CODE REVIEW

**Comment by rappasoft** [comment]
_Obligatory links to all the other closed PRs_

**Comment by a-komarev** [comment]
See #4367 #4398 #4386 #4403 #4400 #4401 and many others.

**Comment by Te7a-Houdini** [comment]
already closed , #4410  #4424

**Comment by JuniorClaudio** [comment]
One email notification more for that ... again!

**Comment by ElfSundae** [comment]
😢 😭 😪

**Comment by Advaith3600** [comment]
Ok

**Comment by pavinthan** [comment]
Please close this issue.

**Comment by scoutman57** [comment]
This is why I wish something like this would be put in the doc block. 

https://github.com/scoutman57/laravel/commit/37978f9e9779ade8733a5925d768e4fd1c87addb

**Comment by azeyrx** [comment]
I think anyone who is interested to use it will be able to read the documentation.
@scoutman57 @Advaith3600

**Pull request closed without merging**
