### PR TITLE
Check laravel requirements

### PR DESCRIPTION
**Pull request by aleixfabra**
Check laravel requirements at welcome.blade.php view.

I'm new in laravel so I don't know if you already discussed this in the past but I think it's a great help when you stard a new project.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These requirements are incorrect.

**Comment by aleixfabra** [comment]
Can you say me why @GrahamCampbell? 
I read it here: https://laravel.com/docs/5.2#installation

**Comment by GrahamCampbell** [comment]
Those docs are incorrect. Not sure how that happened. `PHP >= 5.6.4` is only needed starting from L5.3.

**Comment by aleixfabra** [comment]
So it's php 5.5.9?

**Comment by GrahamCampbell** [comment]
> So it's php 5.5.9?

Yes, laravel 5.1 and 5.2 are both php 5.5.9+.

**Pull request closed without merging**
