### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by YashJha05**
Try to merge your programs to make them look more elegant

### CODE REVIEW

**Comment by ahinkle** [comment]
Hacktoberfest spam has begun.. 🙄

**Comment by stancl** [comment]
Wow, this man is a **true expert** at scamming companies' goodwill for free t-shirts.

- A pull request that breaks Laravel (this one)
- Adding stupid comments to random READMEs
  - https://github.com/irving-rs/guess_number/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8R4
  - https://github.com/irving-rs/quadratic_equation_solver/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5
  - https://github.com/irving-rs/tic_tac_toe/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5
  - https://github.com/irving-rs/body_fat_calculator/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5
- And a pull request with ... a **completely empty diff** https://github.com/google/googletest/pull/3033/files

I'm in awe at the level of scamming skills. Especially the last point. I'm truly amazed.

My amazement will promptly follow GitHub's, DigitalOcean's, and dev.to's support — pretty sure their minds will be blown too.

Great job!

**Comment by irving-rs** [comment]
@stancl - I am the owner of those random READMEs 😭. Thanks for your resume. 

Maybe, he is just a child, I do not know.

**Comment by stancl** [comment]
@irving-rs Just trying to get free t-shirts at the expense of OSS maintainers.

**Comment by stancl** [comment]
Don't want to beat a dead horse here, but for what it's worth, @driesvints if you could label these PRs with `spam` or `invalid`, it would both increase the quality of Hacktoberfest and potentially low further spam targeted at your repos.

Screen Shot 2020-10-01 at 19 03 46

I made a list of them.

https://gist.github.com/stancl/882645f71118631565b307f63548c679#file-laravel-md

**Comment by GrahamCampbell** [comment]
It would be helpful if you simply report offending users to GitHub. If their account is new and their only activity is spam, there's a good chance their account will be suspended.

**Comment by GrahamCampbell** [comment]
I don't understand why GitHub can't use ML to detect this sort of behaviour. Seems pretty common for someone to create a new account, and send spammy PRs.

**Pull request closed without merging**
