### PR TITLE
Fix indent format.

### PR DESCRIPTION
**Pull request by taiyaei**
This converts AppServiceProvider to spaces since it wasn't and removes
a few empty lines after class declarations.

### CODE REVIEW

**Comment by OzanKurt** [comment]
Doesn't laravel use tabs?

**Comment by yasinkocak** [comment]
2.4. Indenting
Code MUST use an indent of 4 spaces, and MUST NOT use tabs for indenting.

N.b.: Using only spaces, and not mixing spaces with tabs, helps to avoid problems with diffs, patches, history, and annotations. The use of spaces also makes it easy to insert fine-grained sub-indentation for inter-line alignment.

http://www.php-fig.org/psr/psr-2/

**Comment by GrahamCampbell** [comment]
We are not psr2 yet.

**Comment by pespantelis** [comment]
>Laravel follows the `PSR-4` and `PSR-1` coding standards. In addition to these standards, the following coding standards should be followed:

>- The class namespace declaration must be on the same line as `<?php`.
- A class opening `{` must be on the same line as the class name.
- Functions and control structures must use Allman style braces.
- Indent with tabs, align with spaces.

http://laravel.com/docs/master/contributions#coding-style

**Pull request closed without merging**
