### PR TITLE
Update web.php

### PR DESCRIPTION
**Pull request by Artiik-fr**
Use the new Route::view method from Laravel 5.5

### CODE REVIEW

**Comment by fletch3555** [comment]
There have literally been 50 PRs for this already, and they have all been declined so far.  I assure you, yours will be no different.

**Comment by a-komarev** [comment]
I will just leave it here: #4398 #4396 #4391 #4386 #4381

**Comment by Artiik-fr** [comment]
Okey

**Comment by a-komarev** [comment]
It will be easier to add view helper in routes and keep one more route with closure for tests to stop this types of PRs in future :}

**Comment by ghazanfarmir** [comment]
@a-komarev and then expect even more PRs to remove one of the two :)

**Comment by a-komarev** [comment]
@ghazanfarmir this will happen with possiblity of 0.0000001% and now we are getting PRs with `Route::view` each day.

**Pull request closed without merging**
