### PR TITLE
[WIP] [6.x] Use laravel/tinker v2

### PR DESCRIPTION
**Pull request by GrahamCampbell**
To be merged when tinker v2 is ready. This can then make it into 7.x by merging `master` -> `develop` in the usual way.

### CODE REVIEW

**Comment by crynobone** [comment]
Why not `"laravel/tinker": "^1.0|^2.0"` if isn't non breaking changes.

**Comment by driesvints** [comment]
@crynobone because the skeleton is only used for new installs and new laravel 6 installs will be compatible with tinker 2

**Comment by GrahamCampbell** [comment]
Exactly. This is not the framework repo. People can edit their app's composer.json after making a new app if they want. :)

**Comment by crynobone** [comment]
Just that without tinker v2, I can't sync Testbench 5.x with Laravel `dev-develop` skeleton anytime soon.

**Comment by GrahamCampbell** [comment]
The dependencies of tinker don't support Symfony 5 yet.

**Comment by GrahamCampbell** [comment]
This was really merged too soon, since psysh 0.9.x may never support Symfony 5.

**Pull request merged**
