### PR TITLE
[5.2] Simple exception addition to allow for autheticated members to logout

### PR DESCRIPTION
**Pull request by 82rules**
I couldnt find the latest stable [5.2] branch so I apologize if submitting to master is frowned upon.
This PR allows autheticated members to hit the getLogout in AutheticatesUsers trait so that when authed users are trying to hit that route the middleware does not prevent them from executing the logout logic.

### CODE REVIEW

**Comment by pietdevries94** [comment]
`$this->middleware('guest', ['except' => ['logout','getLogout']);` should be `$this->middleware('guest', ['except' => ['logout','getLogout']]);'

**Comment by 82rules** [comment]
Is there any way to resubmit to StyleCI or must I resubmit the PR?

**Comment by pietdevries94** [comment]
The owners can probably reset StyleCI

**Comment by barryvdh** [comment]
You're still missing a space. Push a new commit and it will trigger a new check.

**Comment by gaomd** [comment]
We already have [`Route:auth()`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L351) which uses the `logout`.

**Comment by 82rules** [comment]
I wasn't aware of Route::auth(), calling that from the routes file will default the routes in then?

**Comment by taylorotwell** [comment]
This shouldn't be needed in fresh Laravel 5.2 applications.

**Pull request closed without merging**
