### PR TITLE
Remove optimize command

### PR DESCRIPTION
**Pull request by diogoazevedos**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The optimize command is not deprecated, we actually just went straight ahead and removed the class compiled file generation from it. What remains of the otomize command is not deprecated. That said, I think we should actually deprecate the whole command.

**Comment by GrahamCampbell** [comment]
I'm guessing the post install scripts already "clear compiled", so there's no point in running the optimize command, but not because it's "deprecated".

**Comment by diogoazevedos** [comment]
@GrahamCampbell Thanks! I will recommit with an appropriated message.

**Comment by taylorotwell** [comment]
Not sure this needs to be removed yet.

**Pull request closed without merging**
