### PR TITLE
Update server.php

### PR DESCRIPTION
**Pull request by thelastblack**
Sometimes, using `server.php` for PHP local server gives 404 error for static files in `public` folder. I think the problem lies in `return false` when using that.

I am using NetBeans 8.1 for development, and configuring to run `server.php` with PHP local server, and debugging with XDebug, static files fail to load. It just gives 404, generated by PHP local server itself.

Although running `php -S localhost:8000 server.php` is fine on command-line, and then running debug in NetBeans works, but it does not work when run with NetBeans and in debug mode.

This patch fixes the issue, although it would be better to serve files based on mime-type. In my tests, using `mime_content_type` or `finfo_*` can not correctly detect type of minified files. As this file is to be used with local development, it is not a great issue to use simple extension-based detection.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'm sorry, but this doesn't look like a correct fix.

**Comment by thelastblack** [comment]
You have any clue regarding problem?

**Comment by thelastblack** [comment]
I just checked PHP doc for [built-in web server](http://php.net/manual/en/features.commandline.webserver.php), section `Example #5 Handling Unsupported File Types`.
It is basically doing what I have done, so what is wrong with it?

**Comment by GrahamCampbell** [comment]
> so what is wrong with it?

Because there are not unsupported. They're listed as supported.

**Comment by GrahamCampbell** [comment]
> Standard MIME types are returned for files with extensions: .3gp, .apk, .avi, .bmp, .css, .csv, .doc, .docx, .flac, .gif, .gz, .gzip, .htm, .html, .ics, .jpe, .jpeg, .jpg, .js, .kml, .kmz, .m4a, .mov, .mp3, .mp4, .mpeg, .mpg, .odp, .ods, .odt, .oga, .ogg, .ogv, .pdf, .pdf, .png, .pps, .pptx, .qt, .svg, .swf, .tar, .text, .tif, .txt, .wav, .webm, .wmv, .xls, .xlsx, .xml, .xsl, .xsd, and .zip.

**Comment by shehi** [comment]
@thelastblack : Using ```readfile()``` can be dangerous for users who might choose utilizing output buffer. When OB is used, it will fill up the memory and "drown" the app.

**Comment by thelastblack** [comment]
@shehi True, but note that this is only a "local development server". It is by no mean used in production and all.
Besides, it is easy to change it to read files chunked.
Anyway, I have found that maybe NetBeans is using project root for file finding, whereas files should be resolved relative to `public` folder. I did not find a way to tell NetBeans to use `-t project-root/public` when running PHP yet.

**Pull request closed without merging**
