### PR TITLE
Edited .gitignore

### PR DESCRIPTION
**Pull request by hivokas**
As for me, these folders & file shouldn't be committed.
What do you think about this?

### CODE REVIEW

**Comment by a-komarev** [comment]
I'm sure you will get an answer that this file is under your control in your own application and you are free to change it for your requirements.

**Comment by dpde** [comment]
This might work with your project but probably not for everyone.
I worked on many projects where all frontend assets are compiled locally to not rely on any build process during deployment (which might fail and brake the deployment). In that case, the assets in /public are required.

**Comment by a-komarev** [comment]
In my current project there are no assets at all. It's only API application.

**Comment by rappasoft** [comment]
Yeah but that doesn't mean it has to change for everyone..

**Comment by taylorotwell** [comment]
I honestly like committing them. Hate compiling and stuff on the production server.

**Comment by nunomaduro** [comment]
@hivokas Not everyone compiles this stuff on the production server.

**Pull request closed without merging**
