### PR TITLE
Run gulp after installing npm dependencies

### PR DESCRIPTION
**Pull request by martinbean**
Automatically run `gulp` after installing npm dependencies.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This won't actually work unless you've aliased gulp.

**Comment by GrahamCampbell** [comment]
You'll need `./node_modules/.bin/gulp`.

**Comment by GrahamCampbell** [comment]
People commonly want to run it with the `--production` flag too. I don't see this change as being needed, or indeed wanted by everyone.

**Comment by GrahamCampbell** [comment]
People also commonly use bower too.

**Comment by martinbean** [comment]
> You'll need ./node_modules/.bin/gulp.

Not true. npm copies binaries to *node_modules/.bin*, which is part of the path npm looks in.

**Comment by GrahamCampbell** [comment]
> which is part of the path npm looks in.

It doesn't on every system. For example, it doesn't for me on my PC.

**Pull request closed without merging**
