### PR TITLE
Update .env.example

### PR DESCRIPTION
**Pull request by setiawanIman**

### CODE REVIEW

**Review by karlhillx — COMMENTED** [review]
Why is this necessary?

**Comment by setiawanIman** [comment]
Maybe many people who don't know how to enter the password from their env must use a string or not. I'm sorry if that's unnecessary.

**Comment by crisgarlez** [comment]
In my first time with Laravel it took me a while to realize that the Database password did not work for me due to the use of special characters.

DB_PASSWORD='#pAssWord1234' instead DB_PASSWORD=#pAssWord1234

**Comment by stancl** [comment]
hacktoberfest spam, I think there will be many of these in the coming days 🙃

**Pull request closed without merging**
