### PR TITLE
Allow filesystem to be changed on config

### PR DESCRIPTION
**Pull request by caiquecastro**
Allow to change the filesystem storage on the fly.
For example, you can swap the storage disk with a fake one with
`Storage::fake` for tests.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Seems fair. 👍

**Comment by laurencei** [comment]
Do you need the `FILESYSTEM_DEFAULT` and `FILESYSTEM_CLOUD` in the default `.env.example` though? It's starting to get fairly large in there...

So to clarify; I'm saying just have the changes to `config/filesystem.php` as part of this PR, and not the `.env.example` as well?

**Comment by caiquecastro** [comment]
Remove the env variables from .env.example

**Comment by troccoli** [comment]
I think we do. If I see something in .env.example I know it's something I
can customise.

**Comment by caiquecastro** [comment]
Actually the default and cloud keys are mapped to disks array, so, after thinking more about it, it doesn't make sense to add them to .env, only if there are more disks declared on disks array.

**Comment by taylorotwell** [comment]
Should be FILESYSTEM_DRIVER like the rest of the "default" values (queue, etc.)

**Comment by caiquecastro** [comment]
So, should I replace FILESYSTEM_DEFAULT by FILESYSTEM_DRIVER? What about the cloud driver?

**Comment by taylorotwell** [comment]
Yes.

Cloud variable name is fine.

**Comment by caiquecastro** [comment]
Thanks. I'd updated the PR.

**Comment by ConnorVG** [comment]
Seeing `_DRIVER` and `_CLOUD` is semi-frustrating; especially considering `_DRIVER` and `_CLOUD_DRIVER` looks equally silly.

Bummer!

**Pull request merged**
