### PR TITLE
Moved Usermodel to App\Models, change namespace and calls to it.

### PR DESCRIPTION
**Pull request by chilion**
I moved the User model to a newly created folder App\Models and made sure all namespaces and uses where set right again.

Why did I do this? I have never seen an application with only one Model and so for me it breaks the complete structure and overview of my files when I put the Models straight in the app folder. I noticed this a few times on wishlists and decided it was time for me to go and create a PR.

### CODE REVIEW

**Comment by zaknes** [comment]
Honestly for how much I do this in every Laravel project, I seriously think that it should be added.

Even though it has been suggested time after time.

**Comment by GrahamCampbell** [comment]
This should go to develop really, if at all.

**Comment by chilion** [comment]
@GrahamCampbell I can do that :-) Can you give me a reason why it shouldn't be merged?

**Comment by jadjoubran** [comment]
@chilion what about the generators as well?

**Comment by chilion** [comment]
@jadjoubran Good point, if there is any change at all it might gets merged I will changed them as well. I'm quite curious about @taylorotwell's opinion... :-)

**Comment by jaschweder** [comment]
@chilion for generators you can pass the namespace has parameter and it put your models in correct place, but, this will force all users to put their models inside "models" folders, I'dunno if is this the purpose.

**Comment by chilion** [comment]
@jaschweder At this moment it "forces" all users to put them in the App folder which seems even less the purpose....

**Comment by jaschweder** [comment]
@chilion true

**Comment by GrahamCampbell** [comment]
>  can do that :-) Can you give me a reason why it shouldn't be merged?

Taylor will be in touch soon. It's 100% his decision.

**Comment by taylorotwell** [comment]
There is one main reason I don't like this change, and that is because it forces on people the false idea that Model = Database, and I intentionally wanted to get away from that in the 5.x series because it creates a lot of confusion down the line.

**Comment by chilion** [comment]
@taylorotwell I don't see where it forces people into that idea, why doesn't it do that in the App folder? 
It's a Model right, a folder called Models, not a folder called DatabaseModels or Database.

I get your point about Models !== Database, but I don't see where my PR forces that idea onto people. Could you please elaborate so I can sleep silently tonight? ;-)

**Comment by taylorotwell** [comment]
Because I maintained Laravel for years when there was a "models" folder. Here's what happens: people will put all of their database models in that directory. Then, at some point they will need to write a class that isn't a database model, and they will ask on the forums where to put it, and they will want to create a folder called "libraries" or "classes" or something in the core.

**Comment by chilion** [comment]
@taylorotwell I get that yes, thanks for explaining!
_Can we get a console command then that will do this hassle of a work for every new project for the once willing to use it? Don't document it, people who want it will find it 👼_

**Comment by GrahamCampbell** [comment]
I don't think a console command is needed. It takes one second to move it.

**Comment by Hoosk** [comment]
@chilion +1😸

**Comment by DanRovito** [comment]
@chilion this might help if you want to generate your models in a different folder https://github.com/laracademy/generators

**Comment by taylorotwell** [comment]
`php artisan make:model Models/User`

**Comment by rk-development** [comment]
is anything wrong with 'libraries' directory in app core?

**Pull request closed without merging**
