### PR TITLE
[5.7] Add a custom connection demo to use redis sentinel

### PR DESCRIPTION
**Pull request by dynamohuang**
Add a custom connection demo to use redis sentinel.

### CODE REVIEW

**Comment by dynamohuang** [comment]
Referring [https://stackoverflow.com/questions/52885098/configure-redis-sentinel-in-laravel-5-5](https://stackoverflow.com/questions/52885098/configure-redis-sentinel-in-laravel-5-5)

**Comment by driesvints** [comment]
You can add this in your own project.

**Comment by driesvints** [comment]
Sorry, just now saw your PR. We'll see what @taylorotwell says.

**Comment by taylorotwell** [comment]
I think this is a better topic for documentation or a community blog post.

**Pull request closed without merging**
