### PR TITLE
Task controller

### PR DESCRIPTION
**Pull request by jirawat001**
Task Edit update delete for people to use

### CODE REVIEW

**Comment by isogram** [comment]
I think this guy should get some courses about `How to Use Github` . Perharps he just want to create his own project using laravel but he forked, push into it and did this ridiculous PR. 😅

**Comment by Motifsky** [comment]
@isogram I think you need to be more supportive and less critical.

**Comment by isogram** [comment]
@Motifsky It's fair to say that we have to be more supportive and less critical if he realized what he did. But he did PR like this more than 3 times, man. Seriously.

**Comment by michaeldyrynda** [comment]
People make mistakes, they learn from people helping them out, not criticising them. Everybody was a beginner at some point,.

**Comment by Motifsky** [comment]
Karma

**Comment by Motifsky** [comment]
let's close this thread

**Pull request closed without merging**
