### PR TITLE
Using env variable for Redis database number

### PR DESCRIPTION
**Pull request by v-Stein**
Update .env and database config to use an environment variable for Redis database number.

Avoids conflicts when using multiple Laravel apps on a single Redis server

### CODE REVIEW

**Comment by overtrue** [comment]
👎

**Comment by joshmanders** [comment]
This doesn't need PR'd in, you can alter it in your own app.

**Comment by v-Stein** [comment]
I did it, but I assume this should be set by default for a new Laravel app.

**Comment by joshmanders** [comment]
It is set by default, the value is `0`.

What I am saying is not everything needs to be configurable in `.env` that's what `config/` directory is for.

**Comment by v-Stein** [comment]
Every present option for a Redis server is set in .env by default, except the database index number.
Any explanation?

**Comment by taylorotwell** [comment]
It's less common for that to be environment specific.

**Pull request closed without merging**
