### PR TITLE
create .env file only if it do not exists already.

### PR DESCRIPTION
**Pull request by SachinAgarwal1337**
On server we do `composer install` to update the dependencies which will reset the `.env` file every time. This will prevent from resetting it.

### CODE REVIEW

**Comment by shehi** [comment]
Why did you close this PR?

**Comment by crynobone** [comment]
`composer install` doesn't execute `post-root-package-install` script, that only happen on `composer create-project`.

**Comment by SachinAgarwal1337** [comment]
I created a new one https://github.com/laravel/laravel/pull/3736. This was showing error in StyleCI check.

**Comment by SachinAgarwal1337** [comment]
@crynobone Oh I dint know that. Thank for info :D

**Pull request closed without merging**
