### PR TITLE
Added <title> tag

### PR DESCRIPTION
**Pull request by fwartner**
Otherwise the header output will be something like "localhost:port"

### CODE REVIEW

**Comment by rweas** [comment]
:+1: 

Although most people use laravel.dev or project.dev so it would show Laravel or Project for them. But still this is good.

**Comment by overtrue** [comment]
:+1:

**Comment by ekatiron** [comment]
:+1:

**Comment by yasinkocak** [comment]
How can we forget

**Comment by SammyK** [comment]
:+1: I was just about to add this

**Comment by fwartner** [comment]
*push*

**Pull request merged**
