### PR TITLE
doctype uppercase to lowercase

### PR DESCRIPTION
**Pull request by B-07**
no harm, only benefits

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> no harm, only benefits

How do you mean. Last time I checked, it should be upper case?

**Comment by B-07** [comment]
[here's html5bp's reasoning from uppercase to lowercase](https://github.com/h5bp/html5-boilerplate/issues/1522). Also noticed that Taylor himself using lowercase in laravel.com

**Comment by GrahamCampbell** [comment]
> Also noticed that Taylor himself using lowercase in laravel.com

We actually don't know this for sure. It's likely CloudFlare have changed this.

**Comment by a-komarev** [comment]
Supporting it keep all html document structure completely lowercase.

**Pull request merged**
