### PR TITLE
update controller

### PR DESCRIPTION
**Pull request by shinochiha**

### CODE REVIEW

**Comment by Welfordian** [comment]
why

**Comment by realodix** [comment]
Feel free to make this change in your own application if you want to.

**Comment by ludo237** [comment]
@Welfordian he's rushing to make low quality pull request for [Hacktober Fest ](https://hacktoberfest.digitalocean.com/)

**Comment by driesvints** [comment]
Heya thanks but this is fine really.

**Comment by driesvints** [comment]
Also: there's no need to 👎  this so much. They're a first time contributor (see the badge when they open a pr) so let's feel them welcome.

**Comment by ChiragSukhala** [comment]
WHY? This commit does nothing other than increasing the file size and operation time. Pleas correct me if wrong.

**Pull request closed without merging**
