### PR TITLE
[5.2] Added two symfony deps to require-dev

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Goes with https://github.com/laravel/framework/pull/10938.

### CODE REVIEW

**Comment by shehi** [comment]
@GrahamCampbell : If the dependency library (framework) has these in its composer.json, what is the point of adding them again to this package? It will fetch framework's dependencies anyway.

**Comment by GrahamCampbell** [comment]
The framework doesn't depend on them. They're only needed to use the integration testing crawler.

**Comment by GrahamCampbell** [comment]
Thus, it makes sense to move them out of laravel/framework so they can only be loaded as dev-dependencies.

**Comment by shehi** [comment]
I actually was thinking the other way around: removing them from this package. That way, we won't need to update our apps.

**Comment by GrahamCampbell** [comment]
We can't do that? We have no way to install on dev only.

**Comment by shehi** [comment]
I don't get you: both repos have those requirements as ```"require-dev"```, so removing that from one of these repos won't hurt. So instead of removing from framework, I suggest doing the same here, remove it from ```laravel/laravel```. Because we all will be updating our requirements via composer anyway, including this repo as well (it will fetch it's dependencies and run tests afterwards), meaning those two symfony packages will come into play as ```"require-dev"``` eventually. That way, all of us won't have to update our composer.json files in our apps.

Am I missing something here?

**Comment by GrahamCampbell** [comment]
Require-dev does not inherit.

**Comment by shehi** [comment]
Ah ok. Thanks.

**Pull request merged**
