### PR TITLE
Create 2016_07_29_152748_create_tasks_table.php

### PR DESCRIPTION
**Pull request by jirawat001**

### CODE REVIEW

**Comment by teerapat2539** [comment]
it's bad PR.

**Comment by jirawat001** [comment]
I want create add function tasks edit update

**Comment by rappasoft** [comment]
Why are you pulling this here though?

**Comment by teerapat2539** [comment]
Because he is stupid

**Comment by rosDNsf** [comment]
@teerapat2539 says the man with ears and nose of a fox drooling... 

Please be respectful to people who clearly are new to Github.

**Comment by jirawat001** [comment]
because I want to add data for edit data but i don't add function for people to dowload use

**Comment by jirawat001** [comment]
sorry not have advantage

**Pull request closed without merging**
