### PR TITLE
[7.x] Update APP_URL on .env.example

### PR DESCRIPTION
**Pull request by murtazasultani**
Since majority uses artisan serve command to run a Laravel app and the artisan serve command use port 8000 to run the app

### CODE REVIEW

**Comment by martindilling** [comment]
I don't think I've ever used artisan serve ;)

**Comment by murtazasultani** [comment]
@martindilling I think still `http://localhost` is not a proper default value for APP_URL

**Comment by sidis405** [comment]
Hmm. I guess it depends on one's workflow.
In my own experience, i use serve only if i'm checking out something temporary for which i don't want a host.
Other than that, developing using artisan serve is hella cumbersome compared to valet/homestead.

That being said, out of curiosity, under which circumstance does the current APP_URL value get in the way?
I can think of 2-3 scenarios in which the value is called from the framework but that's why you come and edit the value.

The only thing that comes to mind is that changing this to 127.0.0.1:8000, (to the value of artisan serve), might give the idea to newcomers that if you change this element in .env, the host:port of serve will change, and that just ain't it.

**Comment by GrahamCampbell** [comment]
I think this has been proposed before, and rejected.

**Pull request closed without merging**
