### PR TITLE
Move global middleware to RouteServiceProvider

### PR DESCRIPTION
**Pull request by rkgrep**
This is related to https://github.com/laravel/framework/pull/10758

Prevents probable performance problems and unexpected responses, in case middleware applied to non-existent routes.

### CODE REVIEW

**Comment by crynobone** [comment]
This approach also create potential headache when say a package middleware that depends on `StartSession` middleware to be executed before it.

Laravel maintainer has been advertising that anything that depends on session should be converted to middleware and append it to http kernel contract via `appendMiddleware()`.

**Comment by GrahamCampbell** [comment]
:-1

**Comment by GrahamCampbell** [comment]
This behaviour is wrong imo.

**Comment by GrahamCampbell** [comment]
I'd be :+1: to moving just the csrf middleware though.

**Comment by rkgrep** [comment]
@crynobone I'm not sure if this will affect packages. Although, I haven't seen packages modifying kernel middlewares yet (only route ones).

**Comment by rkgrep** [comment]
@GrahamCampbell You have this behavior in StyleCI :smile:

**Comment by GrahamCampbell** [comment]
> You have this behavior in StyleCI

StyleCI isn't an app structure that is suitable for the majority of Laravel users though. :)

**Pull request closed without merging**
