### PR TITLE
update dependencies versions

### PR DESCRIPTION
**Pull request by mayoz**

### CODE REVIEW

**Comment by JellyBool** [comment]
You should always test it out and then make the pr.

if you just change the dependencies like this, it won't just work, refer issue here https://github.com/laravel/elixir/issues/612

change `"laravel-elixir-vue": "^0.1.4"` to `"laravel-elixir-vue-2": "^0.2.0"` .

**Comment by mayoz** [comment]
@JellyBool sorry, edit on Github and I missed my local file.

**Comment by JellyBool** [comment]
Whoops ... I make a pr just now and came back to see your change. @mayoz

**Comment by JeffreyWay** [comment]
Looks good to me.

**Comment by JellyBool** [comment]
@JeffreyWay 
Yeah , for now in my new project, I just wrap it in a `div` with an `id`.

But I still wonder Taylor would merge this pr because laravel/passport Frontend Quickstart : 

https://laravel.com/docs/5.3/passport#frontend-quickstart

still use `ready()` on every component. So .... If this pr was merged, make sure the passport Frontend Quickstart component use the Vue 2.0 `mounted()` instead of `ready()`.

If you don't mind , I could make a pr for that on laravel/passport project.

**Comment by mayoz** [comment]
@JeffreyWay if you want, i can close the PR. Can you send Elixir, upgrade dependencies version and JS fix?

**Comment by taylorotwell** [comment]
I think this stuff could be sent to master branch to be honest.

**Pull request closed without merging**
