### PR TITLE
[8.x] Remove unused javaScript

### PR DESCRIPTION
**Pull request by ninjaparade**
lodash seems to be included and included in bootstrap.js but it's never used. Thought I'd make this PR if people are okay with removing this or is it used that often that it should be left in the scaffolding of a fresh application?

### CODE REVIEW

**Comment by driesvints** [comment]
I also can't find any usages in Jetstream, UI or Breeze. Spark, Nova, Horizon and Telescope still use lodash but those come with their own asset pipeline.

**Comment by GrahamCampbell** [comment]
I think it was included because it's a common thing people use, and serves as a food example of how to load packages (in the bootstrap file).

**Comment by taylorotwell** [comment]
Basically echo @GrahamCampbell

**Comment by browner12** [comment]
A year later is it time to revisit this PR? From my understanding, there are more modern and native ways to accomplish basically everything Lodash provides. By leaving it in our scaffolding, we may be inadvertently encouraging less than modern JS coding standards.  And possibly causing inflated build sizes for those unaware.

https://thejs.dev/jmitchell/its-time-to-let-go-of-lodash-nqc
https://medium.com/techspiration/why-you-shouldnt-use-lodash-f8504d7b7383

**Pull request closed without merging**
