### PR TITLE
Rename 'Request' to 'RequestValidator'

### PR DESCRIPTION
**Pull request by ruelephant**

### CODE REVIEW

**Comment by overtrue** [comment]
:-1:

**Comment by veelasky** [comment]
no need to be confused, since `app\Http\Request` IS `Illuminate\Http\Request`.

**Comment by filipac** [comment]
:-1:

**Comment by ruelephant** [comment]
Possible to think that this classes is related (app\Http\Request) to Illuminate\Http\Request, although it isn't so

**Comment by veelasky** [comment]
well like I said before, IT IS.

`app\Http\Request` extending `Illuminate\Foundation\Http\FormRequest` extending `Illuminate\Http\Request`.

**Comment by ruelephant** [comment]
I know. But the class of app\Http\Request - validation class, and the class Illuminate\Http\Request - very sample request class.

**Comment by GrahamCampbell** [comment]
This is not the request validator. It is actually the request.

**Pull request closed without merging**
