### PR TITLE
Load `database.redis.default.database` from `.env` file.

### PR DESCRIPTION
**Pull request by ModernArtisan**
In some cases, conflicts may arise when several applications works on the same server and uses the same redis DB.
Related to this issue - https://github.com/laravel/horizon/issues/279

### CODE REVIEW

**Comment by sisve** [comment]
What happens if there's a conflict? How would someone know if they are affected by this?

**Comment by a-komarev** [comment]
Related: #4502 #4527

**Comment by a-komarev** [comment]
I don't really understand why this variable so unfavorable. There are a lot of other things which already configurable and not useful for all people. And in case of Redis database I've described main reason of adding this variable. If several applications are hosted on same machine - there will be conflicts with Queues and other third party packages. Especially this applicable for small startups with one server for staging and production applications.

**Comment by fletch3555** [comment]
Your app owns the file, you're free to make the change there if you need it.  @taylorotwell has noted in the past that he doesn't want to change the configs anymore (except for adding new options I imagine)

**Pull request closed without merging**
