### PR TITLE
Refactor npm scripts

### PR DESCRIPTION
**Pull request by JeffreyWay**
Per #4147, this adds a new `npm run watch-poll` command, and dries up some of those long repetitive npm scripts.

### CODE REVIEW

**Comment by SeoFood** [comment]
@JeffreyWay  you sure that the production script will work? `mix.config.inProduction` is always false for me.

**Comment by JeffreyWay** [comment]
@SeoFood The latest version of Laravel Mix will check for the `-p` flag. If you're on an older version, you can either keep your existing NPM scripts, or update to v0.8.2.

**Comment by SeoFood** [comment]
thx @JeffreyWay that old version :)

**Comment by JeffreyWay** [comment]
Gosh - why on Earth would they make it so that `$npm_package_config_webpack` works for Mac and Linux, but you have to use `%npm_package_config_webpack%` for Windows specifically? How are folks supposed to know this?? Fixing this now.

**Pull request merged**
