### PR TITLE
Remove config for workbench.

### PR DESCRIPTION
**Pull request by jumilla**

### CODE REVIEW

**Comment by darryldecode** [comment]
workbench is totally removed on version 5 onward?

**Comment by GrahamCampbell** [comment]
yep

**Comment by Landish** [comment]
If workbench is removed, how can we develop packages for L5?

**Comment by jumilla** [comment]
> If workbench is removed, how can we develop packages for L5?

The way I use is introduced.
(This way can use L4 & L5)

1. make directory 'packages/{{vendor}}/{{package}}
	[example]
	${project-root}/
		packages/
			LaravelPlus/
				Extension/
					src/
					composer.json
					...

2. edit composer.json
	[example]
	...
	"autoload": {
		"classmap": [
			...
		],
		"psr-4": {
			"LaravelPlus\\Extension\\": "packages/laravel-plus/extension/src"
		}
	},
	...

3. run `composer dump-autoload`

- Adobe -

**Comment by jumilla** [comment]
Sorry, mistaked. Below is right.

1. make directory 'packages/{{vendor}}/{{package}}
	[example]
	${project-root}/
		packages/
			laravel-plus/			<-- here!
				extension/		<-- here!
					src/
					composer.json
					...


> 2015/01/16 21:39、Fumio Furukawa <fumio.furukawa@gmail.com> のメール：
> 
> 
>> If workbench is removed, how can we develop packages for L5?
> 
> The way I use is introduced.
> (This way can use L4 & L5)
> 
> 1. make directory 'packages/{{vendor}}/{{package}}
> 	[example]
> 	${project-root}/
> 		packages/
> 			LaravelPlus/
> 				Extension/
> 					src/
> 					composer.json
> 					...
> 
> 2. edit composer.json
> 	[example]
> 	...
> 	"autoload": {
> 		"classmap": [
> 			...
> 		],
> 		"psr-4": {
> 			"LaravelPlus\\Extension\\": "packages/laravel-plus/extension/src"
> 		}
> 	},
> 	...
> 
> 3. run `composer dump-autoload`
> 
> - Adobe -
>

**Comment by taylorotwell** [comment]
Any way you want.

**Comment by franzliedke** [comment]
@darryldecode @Landish I've created [Studio](https://github.com/franzliedke/studio) as a replacement for workbench. Check it out!

**Pull request merged**
