### PR TITLE
[11.x] define specific sqlite version @ `composer`

### PR DESCRIPTION
**Pull request by xerc**
ref. https://laravel.com/docs/11.x/database#introduction
& https://github.com/laravel/nova-issues/issues/6293

### CODE REVIEW

**Comment by crynobone** [comment]
This enforced every project to require `sqlite` even if they don't use it.

**Comment by xerc** [comment]
with version 11 laravel want to be more accessible ; where to put it then ?

**Comment by xerc** [comment]
btw/ check https://www.sqlite.org/changes.html#version_3_45_2 `1.`

**Comment by nunomaduro** [comment]
No plans for this at the moment. Thank you!

**Pull request closed without merging**
