### PR TITLE
ship laravel base with clear:all as example

### PR DESCRIPTION
**Pull request by BartHuis**
give a base functionality as example how to simply make a new command

### CODE REVIEW

**Comment by BartHuis** [comment]
see https://github.com/laravel/laravel/pull/4013 , didn't know how to do it in once...

**Comment by taylorotwell** [comment]
I think those are all sort of very different things and your reasons for clearing them would be different for each case, so would rather keep them separate.

**Comment by BartHuis** [comment]
there are cases that your evoirement "acts strange" and you don't know if it's your code, or something in one or another cache, so you want to delete everything and look if it still happens, then you know for sure it's your code ;)

**Comment by BartHuis** [comment]
(i think symfony's cache:clear does the same i thought to remember from my symfony time?)

**Pull request closed without merging**
