### PR TITLE
[5.5] add whoops to dev dependencies

### PR DESCRIPTION
**Pull request by tomirons**

### CODE REVIEW

**Comment by ankurk91** [comment]
It is already here
https://github.com/laravel/framework/blob/master/composer.json#L77

**Comment by GrahamCampbell** [comment]
> It is already here
https://github.com/laravel/framework/blob/master/composer.json#L77

Dev dependencies are not inherited.

**Comment by ankurk91** [comment]
Oh, I completely forgot about that.
Why don't `laravel/framework` move it to `dependencies` ?

**Comment by m1guelpf** [comment]
Because it's a dev dependency

**Pull request merged**
