### PR TITLE
[5.1] Used dependencies in an alphabetical order

### PR DESCRIPTION
**Pull request by tyloo**
Hey folks!

I thought it would be nice to have our `use` statements ordered alphabetically. What do you guys think?

### CODE REVIEW

**Comment by mydnic** [comment]
:+1: My IDE automatically does that on every project files when applying PSR-2 rules

**Comment by GrahamCampbell** [comment]
Our code style is to sort by length.

**Comment by GrahamCampbell** [comment]
> My IDE automatically does that on every project files when applying PSR-2 rules

This has nothing to do with PSR-2.

**Comment by tyloo** [comment]
https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#use-declarations

This is a lie then ?

**Comment by eko** [comment]
:+1: for this PSR-2 rule, I think @tyloo is right.

**Comment by mydnic** [comment]
@tyloo This : https://github.com/php-fig-rectified/fig-rectified-standards is not the official PSR styleguide. It's a "rectified" version.

The alphabetical order has indeed nothing to do with PSR-2, it's just the phpfmt package for Sublime Text that applies this rule.

**Comment by GrahamCampbell** [comment]
This is NOT PSR-2.

**Pull request closed without merging**
