### PR TITLE
Separating MVC structure - Models

### PR DESCRIPTION
**Pull request by samuelsonbrito**
This separation is organized:
organization

### CODE REVIEW

**Comment by lagbox** [comment]
Previous PRs and discussion:
#4290 
#3967 
#3821 
#3795 
laravel/internals#637

**Comment by samuelsonbrito** [comment]
Community calls for separation of Models

**Comment by ankurk91** [comment]
You should also update
https://github.com/laravel/laravel/blob/0869d963aa96e2a9d4ab58cb451e35e9a31b07d9/database/factories/UserFactory.php#L16

**Comment by GuidoHendriks** [comment]
Did someone already mention that you can do this in your own application if you want to?

**Comment by samuelsonbrito** [comment]
Yes. But most people make this change when they create a new project. Taylor could come back with the Models.

**Comment by dschreck** [comment]
Can we change it from `app/Models/` to `app/Facsimilia/` - in my app I like to move all my Eloquent classes there instead.

**Comment by edenreich** [comment]
I think you would need to update also php artisan make:model command's namespace, otherwise we will need to type php artisan make:model Models\\[name]

**Comment by GuidoHendriks** [comment]
Guys, you’re wasting your time. This won’t be merged. 🙈

**Comment by nicknick-io** [comment]
Agree with Hendriks.

**Comment by taylorotwell** [comment]
Release a package called "namespace-models" that does this for you. I prefer them in the `app` directory, which is also "organized". "Models" is a meaningless word that very few people could even define coherently.

**Comment by samuelsonbrito** [comment]
Ok Taylor. Really :+1:

**Pull request closed without merging**
