### PR TITLE
[6.x] Implement integration test and in-memory DB

### PR DESCRIPTION
**Pull request by driesvints**
Hey everyone. With this PR I want to propose a new dedicated Integration test directory and in-memory DB defaults to the default Laravel test suite. As someone who's worked quite a bit with different test suites over the past years I think I can say for myself I have quite some experience in this area and wanted to share some small things through this PR.

### In-memory DB

The first thing I want to change with this PR is to provide new defaults for the database that's being used when running the test suite of the app. **This is probably the very first thing I change for every single app I start working on.** All of my tests run in memory against a sqlite database which is pretty fast I must say. 

While it is true that the current default Laravel test suite doesn't requires a database to be set up, it is from my understanding that a lot of people do add these new defaults as soon as they need to start testing against a database. It's also true that an sqlite can't mimic a MySQL or Postgres database which is probably used in production but the speed of an in-memory database makes it much more suited for running tests. Therefor, I believe these are good defaults to have in the skeleton.

### Integration Directory

From what I often read on issues and on Twitter I still see that there's a lot of confusion about what a Unit test is and what an Integration test is. A unit test is something you test in isolation, without booting the entire app. You, for example, test a single object or function without any outside dependencies and maybe mock some of those dependencies. These tests usually run really fast.

Integration tests, however, are tests which test the behavior of different components together. They aren't full cycle tests like End-to-End tests or Feature tests but they do require some additional setup (like a database for example). These tests tend to run a bit slower.

In the current skeleton setup you only have two directories: a Unit test directory and a Feature test directory. I think there's room for an Integration directory which actually copies the behavior of the current Unit test directory. Because you see, the current default Unit ExampleTest extends from the default TestCase. This isn't wanted for unit tests because it boots up the entire framework and thus slows down these tests which should actually run much faster (because they should be isolated). 

What I changed is that I've added a dedicated Integration test directory which keeps the current behavior of extending from the Laravel TestCase class and can be used to test different components in your app which require the framework to be booted. The old Unit ExampleTest is updated to only extend the default PHPUnit Testcase so the framework isn't booted and you get the speed boost for these types of test. It's also ok that you don't have all of the Laravel test methods for the Unit tests because most of these methods are meant for Integration tests and provide no value in Unit tests.

I also wanted to make a clear different between what a Unit test and what an Integration test is inside the example tests. For the Unit tests I'm testing if the User model accepts a name attribute and that it can be fetched properly (most people also don't realize you can perfectly Unit test Eloquent models as long as you don't do DB operations). For the Integration test I've added an example which actually makes use of the newly in-memory database defaults and I seed three users and fetch them with the User model.

### Conclusion

What I'm mainly trying to achieve with these changes is to educate people better about testing in general and what the different types of tests are. And I'm hoping this saves a lot of people some time when they start on a new Laravel app (even though the changes are minimal).

I'm sorry for writing such a large description. I'm usually against these myself hehe. But I wanted to be thorough enough to explain the reasoning behind it 🙂 

Let me know what you think.

**Update**: Taking from the feedback here I've made changes to this PR. More info here: https://github.com/laravel/laravel/pull/5169#issuecomment-562202777

### CODE REVIEW

**Comment by christophrumpel** [comment]
Great PR infos provided.

+1 for that.

Setting up the in-memory db is also what I do every time and still I have to look it up more than I like to admit :-) So providing an easier way to use would be awesome.

I think the integration directory would also be an improvement.

The only thing I would change: I wouldn't take an Eloquent model as an example for a unit test because it can be misleading. Yes, you can use it and it is valid, but as an example I would prefer showing testing something else like a plain PHP class.

**Comment by austenc** [comment]
Not a bad idea, but it seems like all the "real" apps I've worked on aren't able to use sqlite because of the DB structure or renaming columns in a migration somewhere. That being said, this would seem to be a good framework default. Perhaps adding an additional callout or section to the docs about considerations to make when swapping to a regular mysql testing DB would also be useful?

**Comment by driesvints** [comment]
> The only thing I would change: I wouldn't take an Eloquent model as an example for a unit test because it can be misleading. Yes, you can use it and it is valid, but as an example I would prefer showing testing something else like a plain PHP class.

@christophrumpel Heya, thanks! I'm gonna keep this part because it's actually one of the main points I want to make here that you can perfectly unit test Eloquent models. Plus there aren't any other skeleton defaults which can be used in a unit test so I'd rather not have to create a dedicated class for it.

**Comment by hulkur** [comment]
Maybe add foreign key checks too if database connection is available?
I usually do it in TestCase::setUp

https://sqlite.org/pragma.html#pragma_foreign_keys

**Comment by driesvints** [comment]
@hulkur heya. Foreign keys for the sqlite database are enabled by default so there's no need to do separate checks for that: https://github.com/laravel/laravel/blob/master/config/database.php#L43

**Comment by browner12** [comment]
I'm indifferent on the directory changes, but using an in-memory database gives me a little pause.

I'll just mention 1 issue I've run into before that prevents me from using SQLite.  Without an extra extension, SQLite is unable to use 'json' type columns.

**Comment by taylorotwell** [comment]
Personally I just put any integration test in the "Feature" test directory, which was kind of its original purpose. Do you think by introducing a third distinction we are making things more confusing? What's an integration test vs. a feature test? Feature tests are definitely integration tests. Are some integration tests not feature tests?

**Comment by driesvints** [comment]
> Do you think by introducing a third distinction we are making things more confusing? 

No not at all. Let me clarify: the difference, in my eyes, lies in the cycle it undertakes. Integration tests are tests which test components. Think: saving data in a database, dispatching jobs and checking reactions (mocking events, etc). Because you're testing one or only a few components they're faster than feature tests.

Feature tests, on the other hand are full cycle tests. You call an endpoint and follow the full request through an app and assert behavior. They touch a lot more parts of the app than just a couple components. Usually it involves lots of components being executed. And thus this makes these tests slower than integration tests.

There's a fourth category as well. End-to-End tests, which mimic the behavior of an actual user using your app. Think Dusk tests, actually making payments on a billing page with the testing api of Stripe, saving files on an actual test S3 bucket. This fourth category might be a little much for the default skeleton (mainly also because Dusk scaffolds this group) but I think these three directories definitely have their place.

All in all I want to say that there's definitely a clear distinction between Unit, Integration and Feature tests in my eyes. But I'm all open to listen to counter arguments of course 🙂

**Comment by driesvints** [comment]
Let me show you another example. In Laravel.io I've separated the test suite between "Feature", "Component" (Integration) & spec (Unit) tests. Have a look at these different tests to see how they differ, I think you'll get a better picture on what I mean: https://github.com/laravelio/portal/tree/master/tests

**Comment by ahmad-shawky** [comment]
@driesvints I checked your example and i found Component and Feature only. Also i checked one of compnents tests. It seems same idea of Unit Test.

**Comment by driesvints** [comment]
@ahmad-shawky spec tests are done by PhpSpec and live in the `spec` directory.

> Also i checked one of compnents tests. It seems same idea of Unit Test.

Which one?

**Comment by driesvints** [comment]
I also want to note that there's definitely no fixed rule on separating Integration and Feature tests. It's just that I believe they behave differently enough to warrant the separation 🙂

**Comment by ahmad-shawky** [comment]
> @ahmad-shawky spec tests are done by PhpSpec and live in the `spec` directory.
> 
> > Also i checked one of compnents tests. It seems same idea of Unit Test.
> 
> Which one?

https://github.com/laravelio/portal/blob/master/tests/Components/Models/ReplyTest.php

**Comment by ahmad-shawky** [comment]
@driesvints I understand your idea more clearly now. I think will be good

**Comment by deleugpn** [comment]
Just dropping this here: https://blog.twitter.com/engineering/en_us/topics/insights/2017/the-testing-renaissance.html

> Integration test - One of a few definitions is possible (thus we’ll avoid this term)
>
> A test covering many servers and verifying that they work together
> A test covering many classes and verifying that they work together

I always liked the fact that Laravel avoids that term due to it's ambiguity. Unit tests can also be ambiguous, but in the context of Laravel it was always "if it's not feature tests, its unit test" regardless of what they mean to you or your project.

**Comment by driesvints** [comment]
> https://github.com/laravelio/portal/blob/master/tests/Components/Models/ReplyTest.php

@ahmad-shawky that still makes use of a database under the hood, hence why it's an integration test :)

> Unit tests can also be ambiguous, but in the context of Laravel it was always "if it's not feature tests, its unit test"

@deleugpn This is something I've always found confusion myself when working on Laravel projects. Hence the PR and the attempt to make things more clear :)

**Comment by deleugpn** [comment]
I understand the sentiment, but just to make sure my post wasn't confusing: having two ambiguous test suite is not better than having only one.

**Comment by svpernova09** [comment]
I would rather see the Integration tests *in* the feature folder. They're often confused and I don't think it's Laravel's job to introduce further confusion by having them at the same level. Laravel defaulting to `tests/Feature/Integration` would be a good starting point and I could even see a `tests/Feature/Acceptance` or `tests/Feature/Dusk` possibly.

**Comment by Arkanius** [comment]
imo it might be confusing. We're getting trouble to find the difference in this thread. I think if it is really going to be merged it must be clear the difference about the integration and feature tests

**Comment by JackEllis** [comment]
Not fussed about the in-memory db default as we use raw queries in our app (on duplicate key update, for example) and have to test it against mySQL. But can see it being useful for like 80% of scenarios.

Love the new Integrations test idea (assuming I'm understanding it right). The way I'm understanding your differentiation is:

1. A feature test might be testing POST /api/v1/users { data } via an api call
2. An integration test would involve testing the creation of the user from, say, a form in the application that hits the same API as above but it would also test the confirmation output too

Have I understood that right?

**Comment by denniskoster** [comment]
I really kind the separation of `Unit`,  `Integration`, and `Feature` test directories. 

However, in my experience using SQLite to test your integration against can in some cases lead to false positives. I have encountered multiple issues where my test suite against SQLite ran perfectly fine only to find that I broke my production server which ran on PostgreSQL. I therefore wouldn't personally use that, but I'd say it's fine as a default. You can always change the phpunit settings.

Perhaps a Testcase class can be introduced for unit tests, which already includes the `MockeryPHPUnitIntegration` trait.

**Comment by pyr0hu** [comment]
Agree with @denniskoster and @JackEllis , I'd use MySQL/Postgre for the tests too to be the same as the production database. Tests passing on SQLite then failing on prod gives a false sense of security IMO.

**Comment by druc** [comment]
In my experience people use the `Feature` directory for http tests and `Unit` for testing eloquent models and _actual_ unit tests.

If the goal is "make people stop putting their model integration tests in the unit directory", a better structure would be:

- Integration
   - Models
   - Http
- Unit

+1 on sqlite by default

**Comment by driesvints** [comment]
My two cents on the sqlite vs your production driver: in my experience you just want to swap the db driver for a fast one to run your tests often. But within your CI environment you can choose your production driver to make sure your tests pass on it before it's deployed to production. Or you can use the production driver on select tests where you know the behavior is different.

I wouldn't want my tests to run slowly locally just because I want to make sure it uses the correct driver. That's what CI is for imo.

**Comment by devfaysal** [comment]
100% agree with Default set In-memory DB.
 +1 for this.

**Comment by ericlbarnes** [comment]
I agree with others that it should only have two folders. Once you go three it introduces too much analysis paralysis and just adds more confusion. But the rest of the stuff I love 100%!

**Comment by driesvints** [comment]
What if we just renamed the "Feature" directory to "Integration"?

**Comment by devfaysal** [comment]
default In-memory DB is undoubtedly agreed by all.
So I think PR can be split into 2 and easily merge the In-memory DB part.
Further discussion can be continued for the Integration Directory.

**Comment by pyr0hu** [comment]
Another possible option would be to add a flag to the Laravel installer and one can explicitly ask the installer to prepare a SQLite based PHPUnit setup or a MySQL/Postgres one.

**Comment by Arkanius** [comment]
Well, renaming "Feature" to "Integration" seems to make no difference. I mean, they are pretty similar imo.

About in-memory db as default I think it's a christmas gift lol

**Comment by ShaunaGordon** [comment]
+1 for the database setting change. That's something I pretty much always change, too, unless and until my actual usage need dictates changing it (such as some of the cases noted above). The point of defaults isn't to work in every single case, but to be sufficient enough that 80% don't need to change it (as opposed to 80% changing it).

I also like the overall idea on adding Integration testing as its own thing somewhere (I don't know if the originally-proposed idea fully achieves the intended outcome, but that's implementation details). Feature tests have always struck me as "follow a request through its lifecycle"/HTTP requests, and that's how I typically see it used in others' projects. If it was intended for other things, that has not been made particularly clear (the documentation even uses the header "HTTP Tests" for the examples that are most obviously put into the "Feature" folder/namespace and follows that paradigm all the way through all of the examples).

Following that assumption for Feature tests, and the assumption that Unit tests are...well...units, that does leave a pretty big gap for tests that are bigger than unit tests, but aren't HTTP/feature tests that has been rough to fill in with Laravel's suggested paradigms (yes, Laravel is pretty unopinionated about things, but there are still paths with more or less friction and that are more or less documented).

If people think adding a new folder introduces too much confusion, then perhaps what's needed is a documentation update that shows more than just the HTTP flow usage.

**Comment by djunehor** [comment]
I don't know about others, but using SQLite for tests has never worked for me and I won't even consider it since the production server uses MySQL. The last time I tried using SQLite for tests, update migrations failed.

As for the separation, I think it's a welcome development, even though it might be inconsequential for the most part developers still have to decide how they organise their tests and dependencies. Our Unit tests for example, still need the application loaded cos the helpers perform actions on Models.

**Comment by driesvints** [comment]
> Well, renaming "Feature" to "Integration" seems to make no difference. I mean, they are pretty similar imo.

"Integration" is a more adopted term than "Feature".

**Comment by Arkanius** [comment]
> "Integration" is a more adopted term than "Feature".

You're right! I use to hear people saying that they do "integration" tests and never heard about "feature" tests. I do it myself when talking with others. In this case, changing "Feature" to "Integration" looks more consistent and I totally agree with @driesvints

**Comment by joecampo** [comment]
+1 for in-memory sqlite by default. I think it’s the perfect solution, until it isn’t for whatever incompatibility you might run into. You'll usually get a lot of miles using sqlite before running into compatibility issues. And as @driesvints pointed out, you can always configure CI to handle testing everything against a slower production database driver.

I really like the idea of renaming “Feature” to “Integration” and as suggested by @druc adding subfolders for the types of integration tests. This would help identify that not every integration test is a "feature" or HTTP test.

* Integration
	* Http
	* Models
	* (e.g.) Dusk
* Unit

I think this structure would really solve confusion of feature vs. integration.

**Comment by hulkur** [comment]
As a wise man once said: naming is hard.

For me integration has always been "integrate with outside" - end-to-end test.
Unit is unit and everything in between is feature.

Leave it as is or rename it. Adding more default directories just adds to confusion.

**Comment by michapietsch** [comment]
I like how much thought you put into it, and that you want to advance education about testing. I still wrap my head around what to test, and how. I mostly skip your integration test example completely, because I would use an HTTP test. Because I know the endpoint covers the DB interaction.

Maybe I overlooked it, but what consequences does the separation have, besides mental model drawers? Ah, one thing I remember: Not booting the app for unit tests. Another reason I think about such distinction or to group tests is the possibility to run tests in parallel.

**Comment by Lloople** [comment]
Default in-memory database is a must 👍 

I also agree with the 3 directories 🤷‍♂

**Comment by deleugpn** [comment]
I agree with the people saying SQLite never worked for them. I guess we can at least try to agree that this might be a sensible default given how broad Laravel is. But for those that, like me, run tests against actual MySQL or any other actual database, remember you can setup a Docker container with in-memory file system (tmpfs: /var/lib/mysql:rw) and have your tests running against in-memory MySQL. Unfortunately that is not a sensible default because it requires Docker usage, which not everyone uses.

Regarding renaming `Feature` to `Integration`, that's a no from me. Testing a feature always felt a much better way to discuss with team mates over the tiresome debate of what is unit vs what is integration tests. I always state the argument that it's nice to write a Feature Test that covers what feature we're writing so that it becomes easy to refactor the code without breaking the (guess the word) **feature**.

**Comment by driesvints** [comment]
> I mostly skip your integration test example completely, because I would use an HTTP test. Because I know the endpoint covers the DB interaction.

The idea behind different types of tests is also a pyramid system where unit tests live on the bottom, integration tests in between and end-to-end tests on top. The reasoning behind this is that if the different units of your app are tested well enough and you have enough integration tests to check their interoperability then there's not much reason to write much slow end-to-end tests. A fundamental thing about testing is that you mainly aim at speed so your feedback loop stays a small as possible. Writing lots of unit tests backed up by a good set of integration tests allows for that. And hence the reason why I want to separate it in different directories. All this is about educating people more about testing really :)

**Comment by sandervanhooft** [comment]
The in-memory db test setting is a no-brainer. Great thinking @driesvints .

Like @taylorotwell I'm not sure about adding another test directory. Personally I'd rather save cognitive overhead deciding where the test should. Right now it's a binary choice: is this a unit test? Put it there. Else, put it in `features`.

For most app sizes this is sufficient, for me at least. May not be the case for larger apps where a lot of integrations are being reused.

That being said, I don't have anything against adding the integration folder or this way of testing, but it would end up empty in most of my projects.

**Comment by mattstauffer** [comment]
Renaming feature to integration makes sense. Adding a third doesn't, to me.

**Comment by driesvints** [comment]
Taking from most of the feedback and going over this with Taylor I've updated the PR to not add a third directory and keep the current "Feature" naming. The changes to the default in-memory DB and extending the Unit tests from PHPUnit's default test case have remained.

**Comment by sandervanhooft** [comment]
Great job @driesvints !

**Comment by browner12** [comment]
For all the people saying switching to an in-memory database is **_obviously_** the right choice, it is not.  There are some valid reasons and arguments against it. Now I'm not saying that it's the wrong decision for a default value, but let's talk about the pros and cons of both options without completely dismissing the other option.

If we're making these changes as a way to benefit new Laravel users, or users who are beginners with testing, are we doing them a disservice by recommending a SQLite database?  The clear benefit is **speed**, but one very important downside is the false positives. Are we going to add to the confusion of these new users when their tests pass in dev and fail in CI (or vice versa)?

As for the folder structure of the test directory, I'm kind of of the mindset "a tests is a test is a test".  They all have to run, and they all have to pass. So what's the point of the directory structure?  Organization is a big thing, making things easy to find, and easily comprehend what they are supposed to be covering.  Another thing is to separate them into different "suites" so you can easily run them as a group. I would say usually this again has to do with speed.  Ideally your Unit tests are **very** quick, while Feature (Integration) tests are a little slower, and Browser (Dusk) tests even slower still.

I think the Unit/Feature/Browser is both good from an organizational standpoint, and from grouping them into similar speed tests.

**Comment by Alymosul** [comment]
That's something i started to do in the projects i'm working on. I usually have the `integration` directory for the tests that are too generic or common in different features and do not belong to a feature on its own, for example testing how a `Transformer` would interacts with a `Model` that i might use in different features. To me feature testing is like describing what does this product offer/do.

But also to add I still try to find a clear line that differentiates between Unit vs Integration.. because as you said you won't use the `App` in the unit test because it boots a lot of thing, but what if your `App` has really small services that it doesn't cost you something to use it as a real collaborator, can we call that Unit? I saw @adamwathan talks in Laracon(s) and also I watched his course, where in one video he mentioned that `You can use real collaborators in Unit tests unless they're not costy and you can control them` therefore I say it depends on how much it cost you to boot up the entire app? I'd love to read @adamwathan opinion on this change.

**Comment by Lloople** [comment]
@browner12 You're not telling the user to use  SQLite as a database engine for production. You're showing them that this way is easier to begin with testing. If you're an experienced user you'll switch to MySQL if you think your environment would need it without problems. On the other hand and in my own opinion, I think there are not false positive but tests that would fail in local but pass in production, because SQLite has fewer features than MySQL.

**Comment by paulredmond** [comment]
My teams have some confusion over what a "feature" test is, but adding a third folder will add even further confusion IMHO. I wouldn't mind if `feature` were renamed to `integration` or just left as `feature`, as I feel these types of tests could be called integration tests.

In other environments (i.e., Rails) an Integration test is similar to what Laravel calls a feature test. The words require some context anyway. 

Another example where multiple definitions exist: a **System** test is also called **End to End** or **Functional** test in some frameworks.

The terms can be a bit vague so I personally like:

* Unit - unit tests
* Integration - test how various parts of the app interact
* End to End - browser testing

**Comment by browner12** [comment]
> You're showing them that this way is easier to begin with testing.

Why is it easier? Again, I don't necessarily disagree, but I'd like some reasons behind the argument to switch to an in-memory SQLite database.  I think we can all agree it's faster.  Are there other benefits?  Do these benefits outweigh the potential discrepancies between testing on your production database?  Are greener users going to be served better with speed or with accuracy?

**Comment by paulredmond** [comment]
I love the idea of having an in-memory database out of the box, it would make spinning up a new app and demoing some tests that use a database a breeze.

I do agree with @browner12 that developers should use caution in using a different engine for tests vs. real application. I've been burned by this in the past, but in practice not too often. Would the Laravel team consider making the default database connection SQLite? The experience out of the box would require creating a development database, but might be a nice default option. I know Rails uses SQLite by default out of the box.

**Comment by browner12** [comment]
> it would make spinning up a new app and demoing some tests that use a database a breeze

Who are we making these defaults for, though? Someone who wants to show some demos, or somebody starting a production ready application?

---

> Setting up a new Laravel app that has a working database connection with zero database configuration would be awesome IMO.

Maybe there's some pain point I'm missing here? I use Homestead, and it creates the MySQL databases for me. All I need to switch is the "database" env variable.  Is it hard to make databases?

**Comment by nisbeti** [comment]
Are the in memory tests really faster? I have swapped MySQL for Sqlite in memory a number of times and always found the difference to be negligable, and sometimes slower.

**Comment by paulredmond** [comment]
Maybe "demo" was the wrong word, but I just mean that it's nice to `laravel new` a new app idea and start creating tests and features for it without any friction. The friction is fairly small though.

My thought was that SQLite is a decent development database that you can easily change to other drivers, but could provide a default that makes the following possible, with zero setup friction:

```
laravel new project
cd project
php artisan migrate
```

It's just a thought though, not trying to fight for it, just throwing the idea out there since my experience in Rails using SQLite as the default has been a nice experience, and it's easy to change to another driver.

**Comment by adamwathan** [comment]
Personally I think trying to over-categorize things is not really useful/productive and mostly just pedantic procrastination of actually productive work.

The term "integration test" is unhelpfully vague IMO, and in practice I have written _very_ few true "pure" unit tests in any Laravel application I've developed. Instead I personally use "unit test" to mean "testing a method on a class" (regardless of how many real collaborators I am using or whether it talks to the file system, database, whatever), and "feature test" to mean "testing an HTTP endpoint".

The only other level of categorization I've ever found to be helpful is "browser tests", which is stuff using Dusk in the context of Laravel. To me, trying to categorize your tests based on whether they "integrate" with anything vs. are pure or whatever is just not really helpful, and is a point of friction/bike-shedding more than anything else.

Instead I find it much more useful to categorize based on the APIs the tests are using, so all Dusk tests get grouped together, all HTTP tests that use APIs like `$this->get(...)` and return `TestResponse` instances get grouped together, and all tests that interact directly with your application classes get grouped together.

This makes categorization simple and obvious, and much less subjective.

I think the current defaults are totally fine but if they were going to change at all I would probably either have 3 folders named `Browser`, `Http`, and `Unit`, or just get rid of the subfolders altogether and let people do whatever they want.

**Comment by Lloople** [comment]
I find myself doing this in every single project because of the speed and the easy it is to start over. Unless you have a really complex query you are fine to go with SQLite in testing. I have a large app with joins and subqueries and tests are built into SQLite. I swap to MySQL when I find a really complex query failing on SQLite , but until that moment I was able to enjoy the SQLite speed breeze.

I would like to mention, as a lot of people did before me, that this is only the default configuration. I mean, if you don't agree with this and you prefer testing in MySQL, you still need to change the `phpunit.xml` file, even nowadays you have to. So I don't see anything wrong with this approach. I would recommend adding a good explanation about SQLite vs Others at the beginning of the Tests section in the documentation, but that's all.

Apart from using SQLite or MySQL for testing, I would recommend to put some variables in there just to prevent running the tests into your local development database by default. Since there are no variables it will use the ones in the `.env` file, wapping out the data you'd have during your normal development period.

**Comment by henriquebremenkanp** [comment]
I think using different drivers make your tests doubtful. They are supposed to give you confidence that things will not break.

I mean, we would not run our tests with PHP 7.4 if I we are deploying 7.3. 
Even though a new version may be a little bit faster, just takes a simple mistake to slip one new feature like an arrow function or a typed property and accidentally you have your tests passing and your deployments failing. And this scenario is just one minor version bump of the same thing. 

If both the default connection and the default test connection were to be sqlite, that's a completely different story. I see benefit in having a database solution that works out of the box like we do have a cache driver, sessions driver, queue driver, etc that works without configuration as well. 
I think it will be an easier start for the framework and I would not mind changing the database to my project needs as I already do with all the other drivers.

**Comment by ravenberg** [comment]
I feel we shouldn't try to carry over the established distinctions between a feature and an integration test to the framework, unless we revisit how we define what a unit test is within a Laravel app (currently that's anything that's not feature). The framework has done a tremendous job in making testing simpler. If anything could use a new label it should be unit imo.

I like the sqlite in-memory default 💯.

**Comment by rs-sliske** [comment]
a few years ago i would probably have agreed with default of in memory sqlite, but after being bit by that i would advise people not to be using it for integration tests. it does not behave the same as other databases (data constraints - or lack of).

also adding to this with how widespread docker is spinning up a clean mysql/postgres/mssql etc etc etc db doesnt really take any effort

**Comment by stefanbauer** [comment]
Not much time, therefore in short:

- In-memory DB default -> yes, a good idea for local testing purposes as a sensible default (even if I would change it to a real database to make the environment as same as possible)
- Adding a third test directory doesn't make sense to me because a feature test is basically an integration test. It checks if different modules/components are working fine together.

If you imagine the test pyramid there are unit tests at a very low level, then integration (feature) tests on top of that and at the very top, there might be a "super feature test" (which I'd call functional test). But the third one is very theoretical.

So summary: Keep it as is and rename `Feature` to `Integration`.

**Comment by driesvints** [comment]
Merged! Thanks for all your feedback on this one people! 🙂

**Comment by troccoli** [comment]
I just want to say thank you to everyone who contributed to the discussion. It was very useful, educational and genuinely refreshing to see so many people calmly and politely make their point.

**Comment by mitesh1409** [comment]
@driesvints 
What if we want to use Laravel Model Factories in the Unit tests?
https://github.com/laravel/framework/issues/30879

**Comment by driesvints** [comment]
@mitesh1409 Move them to the `Feature` test directory or extend your test with the Laravel `TestCase` class.

**Comment by mitesh1409** [comment]
@driesvints 
Thanks for your reply.

So I believe if we want to make use of Model Factory feature in unit tests, then importing
"Tests\TestCase" instead of "PHPUnit\Framework\TestCase" is perfectly fine and is not a bad practice.
The only drawback is that it will run slow since it will boot the framework.

Thanks again :)

**Comment by driesvints** [comment]
@mitesh1409 you're entirely free what you want to do in your own app

**Pull request merged**
