### PR TITLE
don't need it

### PR DESCRIPTION
**Pull request by pierreneter**

### CODE REVIEW

**Comment by joshmanders** [comment]
Can we get some context here? I am not up-to-speed on my npm cli knowledge, but last I knew you had to pass `--` to denote that the flags after should be passed along. Has this changed?

**Comment by hrodrigues1984** [comment]
The `--` is related to [https://github.com/laravel/laravel/pull/4196](https://github.com/laravel/laravel/pull/4196)

**Comment by pierreneter** [comment]
Oops. Sorry, my bad. @joshmanders right. https://docs.npmjs.com/cli/run-script

**Comment by robclancy** [comment]
Should default to yarn anyway.

**Comment by hultberg** [comment]
Just a question after watching some MRs in this repo, and I notice a lot of them are missing some kind of justification or explanation of their changes, and still gets merged. Is there some internal chat of some sort where this is done, shouldn't there be more explanation here why the lines changed by this MR was "not needed"?

**Comment by pierreneter** [comment]
Please ignore this, it is my fault, I will be more careful in the next PR opening. And I will write descriptions, not just short ones. My bad.
:(

**Comment by joshmanders** [comment]
IMHO any PR regardless if it's the next greatest thing to come to the framework should be closed without a proper title and description.

**Comment by marky291** [comment]
It is quite easy to see what code is and does with the changes tab, the creator of laravel also uses this simplistic titles as this does if you look through the history of commits.

**Comment by hultberg** [comment]
@pierreneter No worries, mistakes happen to the all of us. 😄

**Pull request merged**
