### PR TITLE
[5.5] Add typehint comment for the $factory variable

### PR DESCRIPTION
**Pull request by carusogabriel**
Following https://github.com/laravel/framework/pull/22553

### CODE REVIEW

**Comment by carusogabriel** [comment]
@taylorotwell The StyleCI change should be applied and replicate to framework?

**Comment by a-komarev** [comment]
@carusogabriel search in issues. There are tons of PRs with this change. Some of them were accepted, then reverted, and again and again.

**Comment by carusogabriel** [comment]
@a-komarev Thanks, I'll replicate this to Framework as well :+1:

**Comment by GrahamCampbell** [comment]
The StyleCI change is happening because the position is not valid phpdoc, so it gets converted to a comment.

**Comment by GuidoHendriks** [comment]
@GrahamCampbell By that you mean that it's invalid _according to StyleCI_? Because it actually is valid PHPDoc.

**Pull request closed without merging**
