### PR TITLE
add .phpintel to .gitignore

### PR DESCRIPTION
**Pull request by ahmedash95**
Hi , 
phpintel is a common sublime plugin 
> PHP code scanner and analyzer for code intelligence within PHP projects.

it creates .phpintel directory like .idea for phpstorm so it would be nice if we add it to help all laravel artisans who uses this plugin for auto ignore instead of add it manually in each project.

### CODE REVIEW

**Comment by joshmanders** [comment]
You can add this to your own projects.

**Comment by ahmedash95** [comment]
@joshmanders as i said 
>  it would be nice if we add it to help all laravel artisans who uses this plugin for auto ignore instead of add it manually in each project.

there is .idea and .vendor so it would be very nice to add `.phpintel` too , since it's a common plugin  and after this pr you don't have to update your .gitignore file in each project you have

**Comment by crynobone** [comment]
First time seeing `.phpintel`, so don't think it's that common, no?

And GIT has been good enough to introduce "Global .gitignore" to handle such scenarios: <https://help.github.com/articles/ignoring-files/#create-a-global-gitignore>

**Comment by ahmedash95** [comment]
@crynobone Thanks .. this is very helpful and it's first time to know it.

don't know should I close this or wait someone of maintainers to close or merge it

**Comment by mingyoung** [comment]
A change like this will just make other people PR like this:

```diff
+ .ignore-file1
```
```diff
+ .ignore-file2
```

```diff
+ .ignore-file3
```
...

**Comment by ahmedash95** [comment]
@mingyoung  Then i should i will close this.

**Pull request closed without merging**
