### PR TITLE
Environment variable to toggle HTTPS only session cookies

### PR DESCRIPTION
**Pull request by kezkankrayon**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Just do this in your own app.

**Comment by kezkankrayon** [comment]
This is worth noting if your SSL setup differs between environments. If you have `'secure' => true` in an environment that doesn't have SSL setup, you will receive a TokenMismatchException. In my case, SSL is not setup in my local or development environment, but is setup in my production environment.

**Comment by LKDevelopment** [comment]
i think this environment variable would be useful!

**Comment by mateusjatenee** [comment]
I think it would be useful too.

**Comment by vinicius73** [comment]
It's just a parameter to more that can help in the development.

I do not see why not have it in the settings, even if not in the case of .env.exemple

**Comment by kezkankrayon** [comment]
I think it does more than help development; it allows a setting to be secure by default. Also, exposing the variable in .env.exemple not only assists with development, it will raise awareness around security.

**Comment by devsalman** [comment]
Imho, i think this env variable doesn't have big impact because its too environment specific. For me, i always reconfigure my application config / env variable when im deploying my application for production

**Pull request closed without merging**
