### PR TITLE
Introduce DB_PATH for sqlite issue in .env

### PR DESCRIPTION
**Pull request by MadMikeyB**
Per my comment on PR https://github.com/laravel/laravel/pull/3698

This PR resolves that issue - though I do have a strong feeling that this could be done a lot better, I simply didn't want to venture into laravel/framework to change the database_path() helper to check for an env('DB_PATH') - though I would imagine that would be somewhat cleaner.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We already have a way to set this.

**Comment by MadMikeyB** [comment]
@GrahamCampbell I know that we have `database_path()` but there are errors for certain scenarios..

Please see my linked comment for the example?

**Comment by GrahamCampbell** [comment]
Right, but the env allows us to bypass calling the database_path function.

**Comment by GrahamCampbell** [comment]
We also can't make assumptions about the filename.

**Comment by GrahamCampbell** [comment]
Thanks for the PR, but I'd suggest you just tweak your own apps to get them how you like them. Everyone likes things setup slightly differently.

**Pull request closed without merging**
