### PR TITLE
[9.x] Add Ignition

### PR DESCRIPTION
**Pull request by freekmurze**
This is the only change needed to get a beautiful Laravel specific error page whenever an exception occurs.

🌞
CleanShot 2022-01-12 at 21 38 48@2x

🌚
CleanShot 2022-01-12 at 21 38 33@2x

.

### CODE REVIEW

**Comment by dinhquochan** [comment]
what about the `facade/ignition` package? why not upgrade `facade/ignition` package?

**Comment by driesvints** [comment]
Thanks! 🌞 🌑

**Comment by freekmurze** [comment]
@dinhquochan We'll not be using the facade vendor name anymore in the future.

**Comment by dinhquochan** [comment]
> @dinhquochan We'll not be using the facade vendor name anymore in the future.

Got it 👍

**Pull request merged**
