### PR TITLE
Add MIT License to repo

### PR DESCRIPTION
**Pull request by robinnydahl**

### CODE REVIEW

**Comment by ankurk91** [comment]
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by crynobone** [comment]
`laravel/laravel` is just a project skeleton. When you download this and use it for your own project. It doesn't have to be MIT (or MIT compatible license). Having this file it just confusing.

**Comment by nunomaduro** [comment]
@nicknick-io Please read this: [Contributor Covenant Code of Conduct](https://github.com/github/opensource.guide/blob/master/CODE_OF_CONDUCT.md#our-standards).

@robinnydahl Thanks for your proposal! I'm not sure the app skeleton needs a license. It's **your own application**. You should create a license file that fit's your needs. 👍

**Comment by robinnydahl** [comment]
@nunomaduro Thanks for the feedback, seems I've misunderstood the placing of the license. I'll close this down.

**Pull request closed without merging**
