### PR TITLE
[5.4] Change PUSHER enviroment variable names

### PR DESCRIPTION
**Pull request by TheoKouzelis**
pusher.com's copy and paste .env snippet uses enviroment variables that
all start with "PUSHER_APP". This commit brings the config files in line
with pusher.com

### CODE REVIEW

**Comment by Francismori7** [comment]
Note issue https://github.com/laravel/framework/issues/17140 here which this PR "broke"

**Comment by TheoKouzelis** [comment]
Me and another developer have created pull requests to fix laravel/framework#17140 , if that was the reason for this pull request being reverted?

**Comment by fernandobandeira** [comment]
Yes, probably, I guess you could reopen it and link the PR laravel/framework#17151 mentioning that you fixed the issue laravel/framework#17140...

**Comment by TheoKouzelis** [comment]
@fernandobandeira How do I reopen PR. When I try to create a new pull request from TheoKouzelis:fix/pusher-config to laravel:develop, it shows up as being merged already.

**Comment by fernandobandeira** [comment]
You need to redo the PR, open a new branch and commit again...

**Comment by TheoKouzelis** [comment]
Thanks

**Pull request merged**
