### PR TITLE
Update web.php

### PR DESCRIPTION
**Pull request by flick36**
Since we now have the new view route helper we can use it on the web.php routes file isn't it? cleaning the code a little bit

### CODE REVIEW

**Comment by joshmanders** [comment]
seriously people, look at previous PR's both closed and open before you submit the same PR 60 times.

**Comment by a-komarev** [comment]
@joshmanders I hope after 1000th PR #4401 will be accepted to stop this.

**Comment by flick36** [comment]
@joshmanders u mad?

**Comment by brunogaspar** [comment]
@flick36 I don't believe he's mad, but i totally see his point, it's very frustrating to see the same PR being done every, single, day when there's search functionality to determine if a PR was done or not for this change (or any other change).

Cheers 🍻

**Pull request closed without merging**
