### PR TITLE
[8.x] Now extends the correct TestCase class

### PR DESCRIPTION
**Pull request by DilwoarH**
The issue with it loading up the PHPUnit Framework TestCase is that it does not create the application properly. This fix resolves this problem by pointing to the correct TestCase.

REF: https://github.com/facade/ignition/issues/181#issuecomment-626362299

This has caused a great deal of stress for a lot of people - hope this easy fix resolves their problems :)

### CODE REVIEW

**Comment by crynobone** [comment]
Why not move the test to "Feature" if it requires the framework?

**Comment by DilwoarH** [comment]
> Why not move the test to "Feature" if it requires the framework?

Because it's a unit test, not a feature test - simple things like `config('blah')` should still work.

**Comment by crynobone** [comment]
Many would argue loading the full framework isn't unit testing. Which is why it was default to load PHPUnit TestCase.

**Comment by driesvints** [comment]
Write a feature test.

**Pull request closed without merging**
