### PR TITLE
Add VSCode to gitignore file

### PR DESCRIPTION
**Pull request by zendrax**
Add /.vscode to .gitignore file to prevent commiting content of that folder to git repo.

### CODE REVIEW

**Comment by royduin** [comment]
Just put it in your [global gitignore](http://lmgtfy.com/?q=global+gitignore) 👼

**Comment by zendrax** [comment]
Then we can remove .idea from there also?

**Comment by DojoGeekRA** [comment]
@zendrax, it's unlikely that the `/.idea` will be removed.

A lot of people submitted PRs trying to add `/.idea` to the `.gitignore` until one day, we assume, @taylorotwell [became tired of them](https://github.com/laravel/laravel/pull/3877#issuecomment-239663470) and he merged it.

Later on, people tried to remove it several times until [this happened](https://github.com/laravel/laravel/pull/4094#issuecomment-270467941).

**Comment by taylorotwell** [comment]
Whatever. I've given up fighting this stupid battle.

**Comment by asoorm** [comment]
That's not very artisanal @taylorotwell 🤣

**Comment by robclancy** [comment]
@taylorotwell for now on when you merge something like this you need to just comment "Yolo".

Also I don't know why people care, this repository is a skeleton and the files are designed to be edited...

**Comment by TheWebDevel** [comment]
That commit message made my day @robclancy.  Now let's close this issue. Sorry this is not even an issue for God's sake. @taylorotwell

**Comment by zendrax** [comment]
That's like asking why would you use your small car to go to the city center where it's crowded if you have a big car. Or ask @taylorotwell why is he using Sublime over PhpStorm.
Speed? Longer battery life? Cooler laptop while it's in your lap? I'm sure someone can come up with who knows how many more reasons.

**Comment by robclancy** [comment]
I'm just curious, why would you get a PHPStorm license when VSCode is free?

**Comment by nrobates** [comment]
Because PHPStorm is beyond awesome in so many ways and is really geared for PHP Development.

**Comment by a-komarev** [comment]
@robclancy PHPStorm is free for Open Source developers too.

**Comment by robclancy** [comment]
VSCode is way faster, doesn't look crap, works with many languages, is free, doesn't have a bunch of fanboys like you guys who go everywhere possible to bring it up and tell people to use it (my biggest issue with it tbh, just fuck off).

**Comment by GuidoHendriks** [comment]
Very mature. 👏🏻

**Pull request merged**
