### PR TITLE
Update readme with Laracasts count

### PR DESCRIPTION
**Pull request by DrewRoberts**
Minor update to the readme file with the current number of @laracasts video tutorials.

@taylorotwell, you are the man.

This is my first pull request, so I wanted to honor @JeffreyWay with it for teaching me the ropes. I greatly appreciate both of you making the rest of us into web artisans with Laravel!

### CODE REVIEW

**Comment by ludo237** [comment]
Over 1100 is still true if it's over 1400

**Comment by techouse** [comment]
Seriously? How does one justify a pull request like this?!

**Comment by michaeldyrynda** [comment]
Drew is making their first contribution to open source; your reactions are a little disappointing.

**Comment by driesvints** [comment]
@DrewRoberts thanks for your PR Drew!

**Comment by chriskonnertz** [comment]
@techhouse

> Seriously? How does one justify a pull request like this?!

I think this number has been adjusted severeal times in the past. So  I'd say: Based on several precedents.

**Comment by techouse** [comment]
@chriskonnertz 
> I think this number has been adjusted several times in the past. So I'd say: Based on several precedents.
Very well, then think it's just a matter of time before someone will spot the somewhat evasive grammatical error in that very same line and submit yet another PR. :laughing:

**Comment by GuidoHendriks** [comment]
@techouse Aren't you just jealous of his contributor tag? You should be able to get one too by finding some minor typo or wait for 1500 Laracasts vids. 🤣

**Comment by techouse** [comment]
@GuidoHendriks not jealous of anything or anyone however, and as I pointed it out earlier, I can not find any justification for a PR for such a trivial thing. I wouldn't dare even thinking about it let alone do it. 🤣

**Comment by michaeldyrynda** [comment]
You could have either been kinder to Drew as they made it clear they were making their very first contribution or just kept your snide remarks to yourself. Perhaps you didn’t dare even think about that, either. 

One of Laravel’s best assets is its welcoming community and this isn’t a very good first impression.

**Comment by ludo237** [comment]
@michaeldyrynda I don't want to take the side of anybody but.. I mean I'm glad he is getting into OSS contribution and it's great for everybody, that being said Laravel receives hundreds of PRs every week and I'm wondering if it's time to raise the entry level bar avoiding certain type of PR. 

> Just because you can doesn't mean you should

Also I think that when it comes to pure grammar `fixes` like this, everybody has its own opinion on how it should be written thus generating more confusion and more PRs

**Comment by techouse** [comment]
@michaeldyrynda indeed it is a welcoming community. 10+ replies on such a minor matter, however only 3 on [major/breaking issues like this](https://github.com/laravel/framework/commit/f34ebdcf820ae1e28fcbea055151e3eafce2605a). 🤘🏻

**Comment by michaeldyrynda** [comment]
Maybe so, and that can be done without denigrating the contributor.

**Comment by chriskonnertz** [comment]
@techouse
> Very well, then think it's just a matter of time before someone will spot the somewhat evasive grammatical error in that very same line and submit yet another PR.

Go ahead, create a pr. Grammar mistakes should be fixed. Is it you/your? :)

**Comment by chriskonnertz** [comment]
@ludo237
>  Laravel receives hundreds of PRs every week

And that's why there is more than one person to handle them, as you can perfectly see here... :P

**Comment by techouse** [comment]
@chriskonnertz 

> Go ahead, create a pr. Grammar mistakes should be fixed. Is it you/your? :)

Indeed it is. However I am sorry, I will not go down that path of creating a PR for it since I do agree strongly with @ludo237 that the PR bar for such major projects should be set higher and _all_ pull requests _should_ be put under careful scrutiny.

**Comment by driesvints** [comment]
Hey everyone, I'm going to lock this because I feel this is getting off track from the PR at hand. Feel free to discuss this further on Discord or Larachat.

**Pull request merged**
