### PR TITLE
added env SES_REGION

### PR DESCRIPTION
**Pull request by Jameron**
The services.php file should use env() for ses region.

### CODE REVIEW

**Comment by zaknes** [comment]
Can you add the default value back, please?

```php
env('SES_REGION', 'us-east-1')
```

**Comment by taylorotwell** [comment]
It's fine as is. Can convert to environment in your own app if needed.

**Comment by Jameron** [comment]
Seems inconsistent to me.

**Comment by Jameron** [comment]
Also, this:

  'key' => env('SES_KEY'),
          'secret' => env('SES_SECRET'), 

would make more sense if it was 

 'key' => env('AWS_KEY'),
          'secret' => env('AWS_SECRET'),

**Comment by Jameron** [comment]
This config file makes me uneasy bro.

**Comment by erikwestlund** [comment]
There have been numerous recommendations to add extra ENV variables to the
config, and Taylor et al. have consistently given the answer Taylor just
did.

Not everyone uses AWS.  I don't think it's necessary to have AWS-specific
config in the env file when it is so easy to adapt.

**Comment by Jameron** [comment]
Take a look at the config/services.php file ...

**Comment by erikwestlund** [comment]
Missed that we're speaking of this specific file. My bad.

The region does not need to be kept out of version control as it's not
sensitive.  (See S3 links)

I think this is the guiding principle for the choice.

Erik

**Comment by Jameron** [comment]
Not sensitive yes, but it can be specific to an environment.  E.g. using latency based routing policy with multi-region setups. West coast servers should use west coast SES endpoint, and East coast servers should use east coast SES endpoint. 

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html

**Pull request closed without merging**
