### PR TITLE
Added new method Str::unique().

### PR DESCRIPTION
**Pull request by swt83**
Generate a unique string based on time instead of random chance.

### CODE REVIEW

**Comment by najela** [comment]
@swt83 But the md5 algorithm is not guaranteed to generate a unique string each time right?

**Comment by GrahamCampbell** [comment]
Neither is any hashing algorithm.

**Comment by najela** [comment]
@GrahamCampbell  Then we could use this https://gist.github.com/dahnielson/508447#file-uuid-php-L74

**Comment by GrahamCampbell** [comment]
@najela This PR isn't even up for discussion anymore as it's for Laravel 3, which has been EOL for a long time now.

**Pull request closed without merging**
