### PR TITLE
Route view helper for welcome page.

### PR DESCRIPTION
**Pull request by SidharthRaveendran**
Used the Laravel 5.5 route helper for views.

### CODE REVIEW

**Comment by NowNewStart** [comment]
#4437 #4424 #4410 #4403 #4401 #4400 #4398 #4396 #4391 #4395 #4386 #4381 #4378 #4367

**Comment by m1guelpf** [comment]
Duplicate https://github.com/laravel/laravel/pull/4437 https://github.com/laravel/laravel/pull/4424 https://github.com/laravel/laravel/pull/4410 https://github.com/laravel/laravel/pull/4403 https://github.com/laravel/laravel/pull/4401 and many others.

**Comment by KristofMorva** [comment]
Sometimes I feel it'd be easier for the Laravel team if they just disabled PRs for this repo :D

**Comment by SidharthRaveendran** [comment]
That would beat the whole purpose of having Laravel in github won't it.

**Comment by brunogaspar** [comment]
> Sometimes I feel it'd be easier for the Laravel team if they just disabled PRs for this repo :D

Even if they would want to disable pull requests, that's not possible in GitHub, only issues can be disabled.

----

As others already suggested, i would prefer to see both examples on the `web.php`, where one of which would be commented out, because these type of pull requests will never cease to exist unfortunately, since people rarely uses the search functionality.

**Comment by KristofMorva** [comment]
@SidharthRaveendran @brunogaspar I wasn't serious certainly :P

@brunogaspar the problem is, that way we should make examples in the source for like every method of `Route`. Also even if we do that, the same event will happen all over again when new features are introduced, because the core of the problem will remain - people use GitHub before learning how to use it. It's a far fetched thing, but I think GitHub could actually show a warning about possible duplicates before submitting a PR (based on title / changes / etc).

**Comment by a-komarev** [comment]
Calling @taylorotwell! Taylor, maybe you'd approve PR #4401 which adds an example to route file to stop this duplications, please?

**Pull request closed without merging**
