### PR TITLE
Add MAIL_THEME to .env file

### PR DESCRIPTION
**Pull request by maxlen**

### CODE REVIEW

**Comment by maxlen** [comment]
If pull request declined - type here why?

**Comment by GrahamCampbell** [comment]
Please see the comment I wrote on your previous PR.

**Comment by GrahamCampbell** [comment]
Laravel's config files are designed to be editied, which is why they are included in the apps, rather than being within the framework. You should edit the config file.

**Comment by maxlen** [comment]
strange. Ok

**Comment by maxlen** [comment]
And maybe we should add dkim to mailer?
If I'll add it to pullRequest - do you add it?

**Comment by maxlen** [comment]
@GrahamCampbell

**Pull request closed without merging**
