### PR TITLE
Maybe it's time to remove it.

### PR DESCRIPTION
**Pull request by RryLee**

### CODE REVIEW

**Comment by muhghazaliakbar** [comment]
Cool

**Comment by mateusjatenee** [comment]
I don't see a problem in that. It may even look more of a "fluent API" for some people.

**Comment by GrahamCampbell** [comment]
I think this is maybe best going to 5.2, though, actually, i think Route::get is way more expressive.

**Comment by anteriovieira** [comment]
@GrahamCampbell +1

**Pull request closed without merging**
