### PR TITLE
Update the usage of tailwindcss

### PR DESCRIPTION
**Pull request by pixcai**
Some updates:
- Updated the usage of Tailwind CSS to allow users to easily use it in `.css` or `.js` or `.blade.php` templates.
- Refined app layout to make it easier for users to develop new pages.

### CODE REVIEW

**Comment by pixcai** [comment]
CI is wrong, should I modify the `tests.yml` file to add `npm install` and `npm run build`? Or should I not modify it this way?

**Comment by TENIOS** [comment]
[Laravel Breeze](https://github.com/laravel/breeze).

**Comment by pixcai** [comment]
> [Laravel Breeze](https://github.com/laravel/breeze).

Yes, so I closed the PR.

**Comment by TENIOS** [comment]
> Yes, that‘s why I closed the PR.

It's nothing. I'd probably want it to be the default, too.

**Pull request closed without merging**
