### PR TITLE
Remove unnecessary else expression.

### PR DESCRIPTION
**Pull request by krienow**
Simplify the code to work without else.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, we don't accept these types of PRs.

**Comment by w2pc** [comment]
I am just curious what is the down side to a PR like this? Looks like a
valid code refactor. Is there a downside that I am missing?

**Comment by jonagoldman** [comment]
It's just easier to read. You can see the if / else without really looking. Otherwise you really need to understand whats going on.

**Comment by GrahamCampbell** [comment]
> Looks like a valid code refactor.

So is the other direction. See my point?

**Comment by danieliancu** [comment]
@GrahamCampbell I totally agree. It's a matter of personal preference. Anyway we can make this changes in our apps.

**Comment by potherca** [comment]
Thought of commenting, then thought better of it. Enjoy your day. :sun_with_face:

**Comment by gaomd** [comment]
This PR is a duplicate of https://github.com/laravel/laravel/pull/3657

**Pull request closed without merging**
