### PR TITLE
Add version info on welcome page

### PR DESCRIPTION
**Pull request by Laraveldeep**
Version info on welcome page is useful on fresh installation.

Very small changed made to original welcome page. Small version info will be displayed below Laravel text.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Laraveldeep Screenshot?

**Comment by Laraveldeep** [comment]
laravel_version

**Comment by taylorotwell** [comment]
No plans to add. Use php artisan --version.

**Comment by CaddyDz** [comment]
@Laraveldeep Told ya!

**Comment by okanlawonema** [comment]
Taylor your call!


You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/laravel/pull/4338#issuecomment-316779788>, or mute
the thread

**Pull request closed without merging**
