### PR TITLE
[6.x] Conform to the PSR-12 coding style

### PR DESCRIPTION
**Pull request by u01jmg3**
- Conform to the PSR-12 coding style
  - https://www.php-fig.org/psr/psr-12/
  - https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src/Standards/PSR12

---

- https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

  > _As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative._

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm, I'm 👎 here. Your changes break the comments documenting why the `use` happens bellow them.

**Comment by GrahamCampbell** [comment]
Also, Laravel has not yet committed to PSR-12, and when and if it does, will probably have an exclusion for these cases that you've changed.

**Comment by antonkomarev** [comment]
I think this comment is not placed before the `class` definition?

**Comment by SharakPL** [comment]
Removing empty line before first `use` statement in a class is enough to pass PSR12. Moving it above comment is unnecessary.

**Pull request closed without merging**
