### PR TITLE
[5.8] Update welcome.blade.php

### PR DESCRIPTION
**Pull request by voyula**

### CODE REVIEW

**Comment by driesvints** [comment]
@GavG actually, this would work fine. The named route `home` comes with the Auth scaffolding and the routes are only displayed when the auth scaffolding has been added so it's perfectly fine to use the `route` helper here. Fresh Laravel apps won't have issues with this.

**Comment by GavG** [comment]
@driesvints You're quite right, didn't notice the surrounding @if (Route::has('login')) block in the template.

**Comment by voyula** [comment]
This is right... Because has in auth control.

**Comment by shirshak55** [comment]
but it don't improve framework which might be wanted by taylor :)

**Pull request closed without merging**
