### PR TITLE
Add Tailwind, "composer run dev"

### PR DESCRIPTION
**Pull request by taylorotwell**
This PR does two things...

First, it adds a basic Tailwind configuration out of the box. This lets you start using Tailwind immediately without installing any starter kit. Useful if you just want to mess around or build things from scratch.

Second, it adds a `composer run dev` script, which starts `php artisan serve`, `php artisan queue:listen --tries=1`, `php artisan pail` (now a dev dependency by default), and `npm run dev` all in one command, with color coded output in the terminal using `concurrently`.

CleanShot 2024-10-10 at 09 07 08@2x

This gives you one command to run the application and have all of the basic stuff you need.

### CODE REVIEW

**Comment by masterfiras101** [comment]
What about pail in windows

**Comment by juanborras** [comment]
Would it be possible to add --host and --port?

**Comment by msamgan** [comment]
@juanborras, you can add the --port, etc, in the dev command manually. in the php artisan serve section.

**Comment by AhmedAlaa4611** [comment]
I hat pail to be a dev dependency by default!!!

**Comment by luisprmat** [comment]
> What about pail in windows

**laravel pail** and **laravel horizon** require **PHP-PCNTL** extension *Not supported for Windows*. In my PC definitely i'm using **WSL** over Ubuntu 24.04 y work fine!

**Comment by jrd-lewis** [comment]
There needs to be a flag added to the installer to do new installs without having Tailwind installed.

**Pull request merged**
