### PR TITLE
[5.1] Standalone "clear-compiled" script for use in Composer

### PR DESCRIPTION
**Pull request by vlakoff**
Alternative to #3694. Another way of solving #3687.

<br>Ref: [ClearCompiledCommand.php
](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Console/ClearCompiledCommand.php)

### CODE REVIEW

**Comment by vlakoff** [comment]
Reminder: Laravel 5.2 uses `services.php` instead of `services.json`.

**Comment by vlakoff** [comment]
Added a commit so that the script is compatible with both Laravel 5.1 and 5.2.
Less hassle for everybody. :relieved:

**Comment by taylorotwell** [comment]
The idea is good but we probably want this file somewhere in the framework itself in case we have to change it mid release. Change this PR to just be the script change and then PR to laravel/framework with the script that deletes the files.

**Comment by vlakoff** [comment]
Yeah but that's precisely what we can't do and is the source of the issues...
vendor/laravel/framework may not be installed yet.

**Comment by taylorotwell** [comment]
Hmm, true.

**Comment by crynobone** [comment]
Shoulder still be safe to do it on post update cmd since it doesn't load the whole app.

**Comment by GrahamCampbell** [comment]
@crynobone Yeh. It's fine to put this in laravel/framework, because we have no need to run commands before composer update.

**Comment by taylorotwell** [comment]
Yeah true we don't need to be doing anything pre-update anyways. So this can go into framework.

**Comment by barryvdh** [comment]
:+1: for doing it post-update/post-install with a simple script in laravel/framework

**Comment by vlakoff** [comment]
But putting it in laravel/framework makes it hard to resolve `basePath`, thus `bootstrapPath`.

**Comment by jmarcher** [comment]
I like this solution better than moving the command to the post-update-cmd

**Comment by barryvdh** [comment]
So like this? https://github.com/laravel/framework/pull/12827

**Comment by barryvdh** [comment]
Above is merged. Related: #3699

**Pull request closed without merging**
