### PR TITLE
Patch 1 - 	allow a specific guard login URL

### PR DESCRIPTION
**Pull request by amosmos**
Since Laravel already supports calling auth middleware with a specific guard (auth:admin), this will allow customizing each guard login url

### CODE REVIEW

**Comment by amosmos** [comment]
Sorry I don't understand the StyleCI error...

**Comment by lagbox** [comment]
looks like you left unneeded whitespace on that line

**Comment by amosmos** [comment]
ok I think you were right :-)

**Comment by scrubmx** [comment]
https://github.com/amosmos/laravel/blob/patch-1/config/auth.php#L42

I think `loginUrl` should be in snake case to be more consistent with other configuration files.

**Comment by amosmos** [comment]
To be honest I thought so too but then I noticed all customizing auth variables are written in cameCase like loginView, registerView and linkRequestView, so I thought this is how Taylor meant for it to be...

But of course I wouldn't mind changing it to whatever case it needs to be...

**Comment by taylorotwell** [comment]
You can make this change in your own application if you want.

**Comment by amosmos** [comment]
Hey Taylor,

Sure I can make it in my own app but wouldn't this assist a true multi-auth feature?

Right now if you really want multi auth you must make separate middlewares for each guard, just because of the different login url, even though you do already allow specifying a guard parameter.

So just this little change will support it - while of course keeping the default 'login' so everything works the same out of the box even if no specific URL was set in the config.

I guess I just wonder why you think it's not needed in laravel out of the box.

Thanks,
Amos

**Comment by amosmos** [comment]
What I mean is that this change keeps loginUrl optional, if none is specified the 'login' will be used just like it is today.

**Comment by danieliancu** [comment]
I think this is great but needs more thinking.

Named routes should be catered for as well and config may not be the best place for defining guard routes, but I can't come up with something better now.

**Comment by danieliancu** [comment]
I think you can discuss it depth on Slack http://larachat.co

**Comment by amosmos** [comment]
Maybe you could let the guard controller handle guests redirect? Than you could set the loginUrl in the auth controller, much like the redirectTo variable is set today (and others: loginView, registerView etc).

And of course this would be optional so if someone wants their own redirect handler logic they can just write it in the middleware like today.

**Comment by amosmos** [comment]
something like:

Auth::guard($guard)->redirectGuest()

**Comment by amosmos** [comment]
@danieliancu about named routes - I just went with the convention Taylor did on customizing auth routes - for example $redirectTo variable expects a URL and not a named route.

**Comment by danieliancu** [comment]
@amosmos that is intentional because you can easily set that with `route()`, but in config you don't have access to it because the routes have not been registered yet.

**Comment by amosmos** [comment]
oh great idea! i didn't think of it at all. yes you are correct about that

**Comment by amosmos** [comment]
Although for some reason I am getting an error when trying:
`protected $redirectTo = route('user.favorites');`

**Comment by danieliancu** [comment]
@amosmos set the value of the property to the named route and then call `route($this->redirectTo)` from the constructor to update its value.

**Comment by amosmos** [comment]
Oh, in that case I still have to manually set the controller to work with named routes.

So if it's my choice and needs a manual action by me to work, you can say the same thing about my suggestion for loginUrl...

Just set the config to the named route, and then call `route(loginUrl)` right in the next line in the middleware...

**Pull request closed without merging**
