### PR TITLE
Add new password validation rule

### PR DESCRIPTION
**Pull request by driesvints**
For https://github.com/laravel/framework/pull/14345

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but you've PRed to framework branch 5.3, but to laravel branch 5.2.

**Comment by driesvints** [comment]
Ah dammit! Thanks, I'll fix that when I get back home.

**Comment by GrahamCampbell** [comment]
You sent the new PR to 5.2 again?

**Comment by driesvints** [comment]
@GrahamCampbell bah, I selected the develop branch first but when I chose "compare accross forks" Github changed it back to master and I didn't spot it. Sorry for that, third time's a charm I guess.

**Pull request closed without merging**
