### PR TITLE
Require PHP 7 via composer.json

### PR DESCRIPTION
**Pull request by svenluijten**
Like in [the `composer.json` of `laravel/framework`](https://github.com/laravel/framework/blob/master/composer.json#L18).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/blob/5.4/composer.json#L18. :)

**Comment by svenluijten** [comment]
@GrahamCampbell Oh wait, I got confused with the branches on this repo. `master` = 5.4 here, `develop` is the next version (5.5), right? Do you want this PR to there or nah?

**Comment by GrahamCampbell** [comment]
Develop on this repo already has the correct php vesion. Thanks though.

**Comment by svenluijten** [comment]
Yeah just saw that 😛

**Pull request closed without merging**
