### PR TITLE
Update cross-env

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This also sets the minimum Node version to 10.14

https://github.com/kentcdodds/cross-env/releases/tag/v7.0.0

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but please separate these two changes.

**Comment by MichaelDeBoey** [comment]
@GrahamCampbell Dropping Node 8 is a consequence of updating `cross-env`

**Comment by driesvints** [comment]
@MichaelDeBoey we weren't enforcing this before and afaik can't cross-env require this itself?

**Comment by MichaelDeBoey** [comment]
@driesvints `cross-env` is enforcing this.
So since it's a dependency of this project, we should do to here.

**Comment by driesvints** [comment]
@MichaelDeBoey if the library is enforcing it itself I don't see why we should enforce it twice.

**Comment by MichaelDeBoey** [comment]
@driesvints So people can see it directly that the minimum supported Node version is Node 10.14

**Pull request closed without merging**
