### PR TITLE
Add Composer to Gitignore

### PR DESCRIPTION
**Pull request by m1guelpf**

### CODE REVIEW

**Comment by LuigiLazzari** [comment]
composer.phar isn't included in this repo.

**Comment by m1guelpf** [comment]
@LuigiLazzari No, but some guides download it instead of installing it globally, and then it gets commited to the repo.

**Comment by joshmanders** [comment]
That shouldn't be the frameworks worry. You can edit your `.gitignore` after you've created your application.

**Comment by yadakhov** [comment]
@m1guelpf Global .gitignore is your friend.  Add composer.phar there.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Pull request closed without merging**
