### PR TITLE
added .idea to gitignore

### PR DESCRIPTION
**Pull request by Marko298**
Hi, everyone who starts project in PhpStorm adds .idea to .gitignore.
I think we can automate this 😃

### CODE REVIEW

**Comment by GuidoHendriks** [comment]
You could just add it to your global .gitignore. Then you won't have to add it to all open source frameworks you'll ever use.

**Comment by Marko298** [comment]
how I can do this? I didn't found such ability in PhpStorm settings

**Comment by GuidoHendriks** [comment]
https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore

**Comment by edvordo** [comment]
Out of experience, the suggested method from link posted by @GuidoHendriks didn't work for me.

I had to create a `~/.config/git/ignore` file and put the globally ignored things there.

**Pull request closed without merging**
