### PR TITLE
Load Glyphicons font from the BootstrapCDN

### PR DESCRIPTION
**Pull request by aFreshMelon**
This allows for out the box use of Glyphicons.

This is the cleanest approach in my opinion.

### CODE REVIEW

**Comment by wilsonpinto360** [comment]
This will use only bootstrap version 3.3.2, i guess.

**Comment by andriesinfoserv** [comment]
please don't load anything from anyone's cdn in laravel by default.

**Comment by aFreshMelon** [comment]
@andriesinfoserv 

You realize that is already happening in the current version?

https://github.com/laravel/laravel/blob/master/resources/views/app.blade.php#L59

**Comment by andriesinfoserv** [comment]
:) i was afraid of that. nevermind, no big deal.

**Pull request closed without merging**
