### PR TITLE
[8.x] Cleaned up grammar

### PR DESCRIPTION
**Pull request by bram-pkg**
Hi,

I have done some proofreading of the phpdoc, I hope these changes sound okay.

### CODE REVIEW

**Comment by bram-pkg** [comment]
@GrahamCampbell re-ordered the words so the lines are decreasing in length.

**Comment by driesvints** [comment]
All of these unfortunately break the comments length (we try to keep those consistent everywhere). Sorry but we can't merge this.

**Comment by bram-pkg** [comment]
Could you elaborate, I'll gladly fix it?

**Comment by driesvints** [comment]
If you look at all comment blocks in Laravel, you'll notice that each one has the same length in lines. The changes in this PR breaks that pattern.

**Pull request closed without merging**
