### PR TITLE
Adds Laravel `v9.x` to changelog

### PR DESCRIPTION
**Pull request by nunomaduro**

### CODE REVIEW

**Comment by driesvints** [comment]
@stefanzweifel any idea why this wasn't done by the updater?

**Comment by stefanzweifel** [comment]
@driesvints Honestly, can't tell. Might be a bug I haven't discovered yet. The combination of having an "Unreleased" heading but no other heading in the changelog isn't something currently covered by tests. Will add tests for this very soon.

---

[The run](https://github.com/laravel/laravel/runs/5111992460?check_suite_focus=true#step:4:4) received the following as the release notes:

> Laravel 8 comes with a lot of changes to the base skeleton. Please consult the diff to see what's changed.

The workflow also [created](https://github.com/laravel/laravel/runs/5111992460?check_suite_focus=true#step:5:45) a [commit](https://github.com/laravel/laravel/commit/4c2104ac101b18ee7c3916cdb15b8ad5566489c2) but missing the input.

The [`8.x`](https://github.com/laravel/laravel/runs/5112229085?check_suite_focus=true#step:4:20) run was successful and created the [expected commit](https://github.com/laravel/laravel/commit/4c6186ac6207336b35bfdaf2669012711ac06d83). 🤔

**Comment by driesvints** [comment]
Yeah seems it's just missing the stuff nuno added here

**Comment by driesvints** [comment]
Honestly it'll probably be fine from now on. Just wanted to mention it to you.

**Comment by stefanzweifel** [comment]
Yeah can confirm that's a bug. The CLI is looking for a previous heading, finds none and does … nothing.
https://github.com/stefanzweifel/php-changelog-updater/blob/main/app/Actions/PasteReleaseNotesBelowUnreleasedHeading.php#L56-L60

Sorry for that. At least I can promise it will work in Laravel 10 next year.

**Comment by driesvints** [comment]
Cool, thanks! :)

**Pull request merged**
