### PR TITLE
Remove extra comma

### PR DESCRIPTION
**Pull request by ankurk91**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Personally, I'd rather actually see the Oxford comma added in all cases, rather than removed here.

(please don't make that change in this PR, tho, will need discussion first)

**Comment by alicompu** [comment]
Clean code, Beautiful.

**Comment by subotkevic** [comment]
Looks good. I have tested the changes. Seems to work.

**Comment by ankurk91** [comment]
Some resources :

https://en.m.wikipedia.org/wiki/Serial_comma

https://english.stackexchange.com/questions/412/should-i-put-a-comma-before-the-last-item-in-a-list

**Comment by michaeldyrynda** [comment]
The Oxford comma is used correctly in this instance.

**Pull request closed without merging**
