### PR TITLE
Aerate .env with spaces

### PR DESCRIPTION
**Pull request by vlakoff**
Sooo more pleasant to read, IMHO.

Spaces supported in dotenv since https://github.com/vlucas/phpdotenv/pull/13.

### CODE REVIEW

**Comment by vlakoff** [comment]
Of course, [KeyGenerateCommand](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Console/KeyGenerateCommand.php) should be updated as well.

**Comment by RryLee** [comment]
I think this not affect read...maybe

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by jovib** [comment]
:-1:

**Pull request closed without merging**
