### PR TITLE
Update JSON error message structure

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by m1guelpf** [comment]
@themsaid Related to https://github.com/laravel/internals/issues/603?

**Comment by themsaid** [comment]
yes

**Comment by taylorotwell** [comment]
@themsaid can you add this to the Laravel trello?

**Comment by m1guelpf** [comment]
@taylorotwell Is the Laravel trello public?

**Comment by themsaid** [comment]
@m1guelpf no it's an internal thing

**Pull request merged**
