### PR TITLE
Revert "Remove extra autoload file"

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Reverts laravel/laravel#4226

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why?

**Comment by taylorotwell** [comment]
I fixed the Artisan problem.

**Comment by GrahamCampbell** [comment]
> Why?

Because now the constant is undefined when running phpunit tests.

**Comment by diogoazevedos** [comment]
@GrahamCampbell @taylorotwell I made a mistake with #4226. Keep the autoload is the best way to share constants across the artisan, phpunit and laravel.

**Comment by taylorotwell** [comment]
We still haven't established why we need or want the constant in PHPUnit. It is still easily addable if someone wants it by just creating a file.

**Pull request closed without merging**
