### PR TITLE
Minor fixes to make phpstorm happy

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by barryvdh** [comment]
I think Laravel actually explicitly wants those `@return void` on constructors..

**Comment by martinlindhe** [comment]
@barryvdh: how come? constructors cant do anything except return void

**Comment by barryvdh** [comment]
Don't ask me, ask @GrahamCampbell ;)
I don't get it either and phpStorm is complaining when I need to add them..

**Comment by martinlindhe** [comment]
Ah. Well if it's there for a reason it would be nice to understand it. I keep removing these @return void:s on each new project i create.

**Comment by GrahamCampbell** [comment]
phpstorm is wrong, sorry.

**Comment by w2pc** [comment]
I think we understand that PhpStorm is wrong. I think people are asking why Laravel wants the @return void on constructors.

**Comment by GrahamCampbell** [comment]
Because return void is the correct annotation. A constructor does not return an instance of the object.

**Pull request closed without merging**
