### PR TITLE
added Security disclosure information

### PR DESCRIPTION
**Pull request by msurguy**
Please also add details on which versions of Laravel are currently supported...

### CODE REVIEW

**Comment by antonkomarev** [comment]
Yes, but it's missing here: https://github.com/laravel/laravel/security/policy

**Comment by xuanquynh** [comment]
It is not necessary. Developers will look at the README.md. Or Remove this section of readme.md after adding SECURITY.md.

**Comment by driesvints** [comment]
Heya, since this is the skeleton for anyone's laravel app, they'll get this file in their apps and that's why I don't think this is the right place. We already have on in the framework repo and like @xuanquynh said, it's also in the readme. Thanks.

**Comment by msurguy** [comment]
@driesvints thanks for the info! 👍

**Pull request closed without merging**
