### PR TITLE
Add .navbar-static-top class to navbar

### PR DESCRIPTION
**Pull request by sw-double**
Navbar should have `.navbar-static-top` class applied

### CODE REVIEW

**Comment by taylorotwell** [comment]
What does this do?

**Comment by sw-double** [comment]
Just removes some borders and border-radius.
Intended to be applied for navbars 100% wide positioned at the very top of the page.
https://github.com/twbs/bootstrap/blob/v3.3.4/less/navbar.less#L128

The difference is subtle on default navbar, but quite noticeable on inverted one.

navbar

**Comment by danielboendergaard** [comment]
:+1:

**Comment by taylorotwell** [comment]
Since all of this stuff is opt-in in 5.1 which releases in just about 6 weeks, let's just fix it there.

**Pull request closed without merging**
