### PR TITLE
fix user table migration problem, change utf8mb4 to utf8

### PR DESCRIPTION
**Pull request by afcn007**

### CODE REVIEW

**Comment by overtrue** [comment]
WTF？

**Comment by micos7** [comment]
utf8, unlike utf8mb4  doesn`t even support non latin based languages.

**Comment by afcn007** [comment]
I have get error when I migrate user table on 5.4.30 version, mysql says the email column is over the limit 767bytes, after change the utf8mb4 to utf8, migrate goes well, what other solution?

**Comment by ready4god2513** [comment]
```
SET GLOBAL innodb_file_format="Barracuda";
SET GLOBAL innodb_large_prefix="on";
SET GLOBAL innodb_file_per_table=true;
```

That's the solution @afcn007

**Pull request closed without merging**
