### PR TITLE
Fix yield calls for PHP5.5

### PR DESCRIPTION
**Pull request by davidhemphill**
Renames the Section::yield() method to Section::yield_template() while not changing the usage.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by GrahamCampbell** [comment]
L3 is not supported or maintained anymore.

**Comment by ericbarnes** [comment]
@GrahamCampbell this really should be fixed otherwise everyone is going to need to have their own fork or be stuck on php 5.4 forever.

**Comment by GrahamCampbell** [comment]
@ericbarnes As I said, L3 is neither supported nor recommended. L5 is the only supported and recommended version now. 4.2 will receive security fixes only, and Taylor will be tagging a final(ish) 4.2 release soonish.

**Comment by barryvdh** [comment]
Yeah its been brought op over a year or so, so guess not much to do but keep a fork of your own :( 
Luckily only a few projects left on L3..

**Comment by JoostK** [comment]
Editing the L3 core manually is not a big deal, it is not managed by Composer. I have a large L3 app with quite some changes to the core, never had any problems updating it (using git upstream merges I never had conflicts, and that is irrelevant now as L3 will not receive any updates anyway)

**Comment by davidhemphill** [comment]
No worries. My fork is available should someone with a large production L3 install need or desire the ability to put their site on PHP 5.5 or Forge.

**Comment by EhteshamMehmood** [comment]
As PHP 7 is coming mid of 2015 , So Laravel 5 will support with PHP7 ??

**Comment by EhteshamMehmood** [comment]
I am newbie , What is the future of Laravel ? 
There are very few questions on StackOverFlow.com ??

**Comment by barryvdh** [comment]
Will probably support php7, if possible.

Please use the forums for questions (https://laracasts.com/ or http://laravel.io/)

**Pull request closed without merging**
