### PR TITLE
Add Yarn lockfile

### PR DESCRIPTION
**Pull request by michaeldyrynda**

### CODE REVIEW

**Comment by mantrax314** [comment]
What's for?

**Comment by michaeldyrynda** [comment]
https://twitter.com/taylorotwell/status/785885272890183681, although Taylor subsequently said that he'll add this to the Laravel installer, so may opt to close this PR anyway.

**Comment by lucasmichot** [comment]
I suppose homestead would come with yarn already installed then ?

**Comment by michaeldyrynda** [comment]
Forge was updated, it makes sense homestead would be as well. Software parity 👌

**Comment by GrahamCampbell** [comment]
I don't think we need to commit this in the main repo, just like we haven't commited the composer.lock file.

**Comment by GrahamCampbell** [comment]
However, both these files are not "ignored", because users of this repo should commit those files to their apps.

**Comment by arcanedev-maroc** [comment]
Just discovered yarn today and this is my reaction:

Feels gooood

But i think the `yarn.lock` file must be added in `.gitignore` instead.

**Comment by michaeldyrynda** [comment]
Ignoring it kinda defeats the purpose of using the lockfile, no?

I'm in agreement with @GrahamCampbell I think.

**Comment by arcanedev-maroc** [comment]
I'm also not sure about it but yarn is way better than npm (speed, no time out, BS errors ...), especially with Windows OS.

**Comment by jehadassaf** [comment]
The Yarn lockfile is no different from the Composer one in terms of intended use.
This means that no, this should not be part of a fresh Laravel install and no, you should not add it to your .gitignore, as it would defeat its purpose.

**Comment by taylorotwell** [comment]
I already got it added in the "laravel new" build. Thanks though!

**Comment by jcloutz** [comment]
Any news on having yarn installed with homestead?

**Comment by taylorotwell** [comment]
I’ll need to rebuild the box. I should be able to do it this week.

Regards,
Taylor

**Pull request closed without merging**
