### PR TITLE
V1.7develop

### PR DESCRIPTION
**Pull request by MjeTjeu**

### CODE REVIEW

**Comment by LKDevelopment** [comment]
@MjeTjeu do you know what you are doing here?

**Comment by MjeTjeu** [comment]
No

**Comment by userabuser** [comment]
At least you're honest...

**Comment by LKDevelopment** [comment]
@MjeTjeu learn a little bit about git: https://laracasts.com/series/git-me-some-version-control

**Comment by TheWebDevel** [comment]
Seems like he's learning git with Laravel repository. 😛

**Comment by MoNoSoo** [comment]
LOL

**Comment by insign** [comment]
LOL

Hélio Araújo de Oliveira

mssg.me/helio

**Pull request closed without merging**
