### PR TITLE
Update AppServiceProvider.php

### PR DESCRIPTION
**Pull request by brunolsantos**
Fixed string Lenght error when migrating.

Traversy tip:
https://youtu.be/4pc6cgisbKE?t=11m56s

### CODE REVIEW

**Comment by lagbox** [comment]
not everyone needs to do this .. this is a work around for using the wrong version of a database

**Comment by pavinthan** [comment]
@brunolsantos  It doesn't need because, new MySQL servers support it, use the latest version of MySQL server is good

**Comment by brunolsantos** [comment]
Yes @lagbox and @pavinthan, but like @enimiste said there

> [ ... ]
But it is not the case all the time.

I think this update will improve the laravel usage for people that use XAMPP like programs.

**Comment by m1guelpf** [comment]
@brunolsantos You own the files. You can change them locally

**Comment by lagbox** [comment]
how about people actually use a real setup instead of these silly stacks that obviously come with dated software ... if only laravel was nice enough to figure out a way to provide a fully functional environment with all the latest software and didn't need to do any work arounds ... oh wait, homestead

**Pull request closed without merging**
