### PR TITLE
Add autocompletion for factory

### PR DESCRIPTION
**Pull request by kamui545**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Invalid cs.

**Comment by GrahamCampbell** [comment]
Needs to be:

```php
/** @var \Illuminate\Database\Eloquent\Factory $factory */
```

**Comment by kamui545** [comment]
Fixed and squashed, StyleCI is still unhappy thought

**Comment by GrahamCampbell** [comment]
Please apply the diff it gives you.

**Comment by kamui545** [comment]
all green

**Pull request closed without merging**
