### PR TITLE
Soporte basico de español

### PR DESCRIPTION
**Pull request by ebar0n**

### CODE REVIEW

**Comment by rweas** [comment]
:+1: The only thing is IDK if @taylorotwell wants the lang folder to be full of dozens of languages. But this does seem like something Laravel needs

**Comment by brunogaspar** [comment]
This was discussed before.

You can contribute to this repository here https://github.com/caouecs/Laravel4-lang

**Comment by ebar0n** [comment]
good to add in some way in the documentation would be there and language support and where it is located

**Comment by paulrose** [comment]
I think it would be best to have a separate languages repo so it doesnt clutter up the main project.

**Pull request closed without merging**
