### PR TITLE
opt: hard coded app name

### PR DESCRIPTION
**Pull request by sinkcup**
use config app name instead of hard coded "Laravel" in views.

### CODE REVIEW

**Comment by ludo237** [comment]
Ah 💩 here we go again

**Comment by bonzai** [comment]
#4994
#4533
#4469

**Comment by httpoz** [comment]
> Welcome view isn't used by your actual application.
Taylor https://github.com/laravel/laravel/pull/4889#issuecomment-449972838

**Comment by sinkcup** [comment]
oh... some many duplicate PRs...
and there will be duplicate PRs in the future, so maybe "fix it" is not a bad idea...

**Comment by GuidoHendriks** [comment]
There’s not really a downside to this. Maybe @taylorotwell will give in like he did on the factory phpdoc.

**Comment by taylorotwell** [comment]
I continue to be confused about this. "welcome.blade.php" is just the Laravel splash screen. It isn't your application.

**Comment by antonkomarev** [comment]
@taylorotwell call it `laravel.blade.php` :rofl:

**Pull request closed without merging**
