### PR TITLE
Change order.

### PR DESCRIPTION
**Pull request by jumilla**
Change validation key order.

### CODE REVIEW

**Comment by lukasgeiter** [comment]
This is not alphabetically sorted... The other PR was better.

**Comment by jumilla** [comment]
@lukasgeiter #3426 was sorted PR.

**Comment by lukasgeiter** [comment]
I'm saying your PR is not *correctly* sorted. ABCD**EF**GHI...

**Comment by jumilla** [comment]
@lukasgeiter I noticed after your comment.
Thanks! :)

**Pull request closed without merging**
