### PR TITLE
Create MakeAll.php

### PR DESCRIPTION
**Pull request by aminetiyal**
Add an extra command that generates all the files that can be generated using the php artisan make in one command

### CODE REVIEW

**Comment by m1guelpf** [comment]
Why would anyone do this?

**Comment by nicknick-io** [comment]
Why would you even do this?
Plus the code quality is crap, with commented out things and all.

**Comment by aminetiyal** [comment]
@m1guelpf for the developers who deals a lot with CRUD
this command to generate all the necessary files needed

**Comment by nunomaduro** [comment]
@aminetiyal Thank you for your proposal. 👍

IMO most of developers **do not need** this command. Fell free to keep that command in your Laravel apps tho!

Tip: Next time you have a great idea, share on [https://github.com/laravel/ideas](https://github.com/laravel/ideas) before creating the code for the pull request! Thank you!

**Pull request closed without merging**
