### PR TITLE
Use ::class notation

### PR DESCRIPTION
**Pull request by anik786**

### CODE REVIEW

**Comment by anik786** [comment]
I am unsure as to why there is a failing task as I only changed 1 file

**Comment by crynobone** [comment]
`5.0` branch is closed for modification. Beside this is redundant with #3570

**Comment by anik786** [comment]
oh thanks. so are all edits to be made to the master?

**Comment by vlakoff** [comment]
* laravel/framework:
    * backward compatible changes to latest stable (`5.1` as of now)
    * breaking changes to `master`
* laravel/laravel:
    * backward compatible changes to `master`
    * breaking changes to `develop`

See also: [Contribution - Which Branch?](http://laravel.com/docs/5.1/contributions#which-branch)

**Comment by anik786** [comment]
I didn't realise there is a difference between framework and laravel/laravel. However I can't seem to find "laravel/framework". Where is this?

**Comment by anik786** [comment]
Thanks!

**Pull request closed without merging**
