### PR TITLE
Change @endsection to @stop

### PR DESCRIPTION
**Pull request by natzim**
Closed previous request because I forgot to read the contribution guide.

Just a small fix, as the documentation says to use `@stop` rather than `@endsection`.

### CODE REVIEW

**Comment by taiyaei** [comment]
What's different between this and #3330?

**Comment by natzim** [comment]
Different branch name.

I'm not used to contributing to open source, so feel free to tell me if I'm doing something wrong.

**Comment by GrahamCampbell** [comment]
If you read the source code, you'll see that these two statements are in fact identical.

**Comment by GrahamCampbell** [comment]
> Different branch name.

Both pulls are targeted at the master.

**Comment by natzim** [comment]
I get that, but why not stick to what is in the documentation?

**Comment by taiyaei** [comment]
@GrahamCampbell I think he meant that he wanted his branch name different than `master`. It's not in the contribution documentation explicitly from what I can find though

@natzim It's true that `@endsection` is not in the documentation (at least not the templating documentation), it might be a good idea to PR to laravel/docs to add it there though

**Comment by natzim** [comment]
@taiyaei It was my understanding that `@stop` had replaced `@endsection` a while ago, so surely the inbuilt views should be using the more up-to-date syntax?

**Pull request closed without merging**
