### PR TITLE
Improve Docs Update README.md

### PR DESCRIPTION
**Pull request by guptaji609**

### CODE REVIEW

**Comment by gargakshit** [comment]
Please add a "spam" or "invalid" label to these kinds of PRs, else these would be counted towards hacktoberfest after the 14 day review window ends

**Comment by driesvints** [comment]
@gargakshit we don't want to pollute our repos with labels specific to hacktoberfest

**Comment by gargakshit** [comment]
invalid shouldn't be hacktoberfest specific I guess

**Comment by GrahamCampbell** [comment]
Feel free to directly report offending users to both GitHub and DigitalOcean, to stop their activity entirely.

**Pull request closed without merging**
