### PR TITLE
Enabling docker / docker-compose support

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure we want to dive into an official Docker recommendation at this point.

**Comment by shehi** [comment]
Sorry for being blunt, but we use bulky Vagrant platform and not accept flexible Docker to the official Laravel ecosystem for what reason exactly?! A platform which has full-fledged API which can completely be controlled and managed? Can anyone list a single point that makes Vagrant better than Docker please? With all due respect, this is ridiculous!

**Comment by appleboy** [comment]
Please try out the https://github.com/LaraDock/laradock

**Comment by shehi** [comment]
@appleboy , I already use Docker in my own small project: http://github.com/AudithSoftworks/Basis . That wasn't the point.

**Pull request closed without merging**
