### PR TITLE
Excepted URIs in RedirectIfAuthenticated middleware

### PR DESCRIPTION
**Pull request by olegmelnik**
Sometimes need for some routes from the group disable the redirect

### CODE REVIEW

**Comment by olegmelnik** [comment]
@GrahamCampbell 

> fully qualified name required please

fixed ?

**Comment by vlsoprun** [comment]
:+1:

**Comment by borisdamevin** [comment]
I had this problem, it was because the middleware `web` was call after middleware `auth`.

**Comment by taylorotwell** [comment]
You can build this into your own application fairly easily.

**Pull request closed without merging**
