### PR TITLE
Use the ::class notation

### PR DESCRIPTION
**Pull request by pespantelis**

### CODE REVIEW

**Comment by shehi** [comment]
Hmm... Looks nice: I have seen this notation in PHPStorm, but couldn't find anything about its function in official documents or web.

**Comment by pespantelis** [comment]
@shehi I found this http://php.net/manual/tr/migration55.new-features.php#migration55.new-features.class-name

**Comment by shehi** [comment]
Yea, I realized after seeing #3402 and PRs derived from there on.

**Comment by pespantelis** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:-1: from me

**Comment by pespantelis** [comment]
@GrahamCampbell IMO the reference of User's model at ModelFactory.php needs to be changed.
About the other changes, maybe you are right.

**Comment by shehi** [comment]
@GrahamCampbell : what is different here from #3402 and its derivatives?

**Comment by shehi** [comment]
@taylorotwell : Quick question - having non-FQNS here, won't break the code, will it? I mean, leading-back-slashes are missing. :)

**Comment by taylorotwell** [comment]
None of these files are namespaced so it will be fine.

**Pull request merged**
