### PR TITLE
Add _ide_helper.php to .gitignore

### PR DESCRIPTION
**Pull request by DanVeira**
Laravel 5 IDE Helper Generator: https://github.com/barryvdh/laravel-ide-helper

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It's not the job of the core to ignore files from packages.

**Comment by gpressutto5** [comment]
@GrahamCampbell What about Homestead.json and Homestead.yaml?

**Comment by DanVeira** [comment]
@gpressutto5 It's probably because Homestead is an official Laravel thingy.

**Comment by gpressutto5** [comment]
@DanVeira Yeah, that makes sense. But what about .idea?

**Comment by DanVeira** [comment]
@gpressutto5 

> The .idea change was only merged to stop the PRs coming.
https://github.com/laravel/laravel/pull/3980#issuecomment-251363260

**Pull request closed without merging**
