### PR TITLE
Use PHP 5.5 ::class property in config files

### PR DESCRIPTION
**Pull request by RomainLanz**
See https://github.com/laravel/laravel/pull/3402

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This looks much better to me. :)

**Comment by RomainLanz** [comment]
Do we also change `auth.php` file for `App\User`?

**Comment by nWidart** [comment]
Hehe, I was about to submit same PR. :smile: 

I'd do the same for `auth.php`.

**Comment by RomainLanz** [comment]
@nWidart You can also do the same for `services.php`.

Send a PR to my fork. I'll squash it.

**Comment by EspadaV8** [comment]
Wow, gone for a day and miss out on all the action. Thanks for this @RomainLanz this does look a lot better (don't know why I didn't do this in the first place).

**Pull request merged**
