### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by coolpraz**
adding new feature of laravel-mix to laravel framework

### CODE REVIEW

**Comment by tianyong90** [comment]
@coolpraz The latest version is v0.8.8

**Comment by coolpraz** [comment]
Maybe but i think latest stable release is 0.8.2

https://github.com/JeffreyWay/laravel-mix/releases

**Comment by tianyong90** [comment]
Not sure whether it is a stable version, but I'm already using v0.8.8 and everything went well so far :smile:

**Comment by GrahamCampbell** [comment]
The version constrain already loads the latest.

**Pull request closed without merging**
