### PR TITLE
[5.4] Update mounted instead of ready

### PR DESCRIPTION
**Pull request by insoutt**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think ready is better. No need to match it to the name in the code.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by Mohamed-Elwan** [comment]
I think console logging is targeted to developers and reading the same name in the code would be some how good. It's not a big deal but it's not bad at all.

**Comment by insoutt** [comment]
This is a small change. Although I think that mounted is more specific than ready

**Comment by Mechtecs** [comment]
:+1: for mounted

**Pull request merged**
