### PR TITLE
default APP_KEY to a 32 characters length string

### PR DESCRIPTION
**Pull request by KluVerKamp**
So  fresh installation of laravel won't throw the cipher related exception anymore.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is intentionally wrong to make people run the key generate command.

**Comment by alexleonard** [comment]
How many times... 

We should add a comment in config/app.php which says the default is intentionally not 32 characters to force key generation per install.

**Comment by lukasgeiter** [comment]
Or how about `ThisIsIntentionallyNot32Chars` as default? :stuck_out_tongue_winking_eye:

**Comment by fideloper** [comment]
heh

**Comment by KluVerKamp** [comment]
I see.
@lukasgeiter sounds better! :stuck_out_tongue_closed_eyes:

**Comment by alexleonard** [comment]
Yes! That's a great idea, no unnecessary comment needed.

ThisIsIntentionallyNot32CharactersSoYouHaveToSetItManuallyDontSubmitAGitPullPlease....

;)

**Comment by KluVerKamp** [comment]
@alexleonard well that has escalated quickly!

**Pull request closed without merging**
