### PR TITLE
Update Request Header Key in Vue Interceptor

### PR DESCRIPTION
**Pull request by milroyfraser**
* updated request header key to X-XSRF-TOKEN

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please explain why we should change this. ;)

**Comment by crynobone** [comment]
👎  we don't need this. `X-CSRF-TOKEN` is valid since `Laravel.csrfToken` is unecrypted, unlike before where we fetch the token from cookie.

**Comment by shahidnajam** [comment]
@GrahamCampbell Do you have any remote work for me? I am an awesome Laravel programmer and now jobless and have no luck to get work.

**Comment by milroyfraser** [comment]
@GrahamCampbell @crynobone how can I store the unencrypted csrf token to `Laravel.csrfToken`

**Comment by crynobone** [comment]
https://github.com/laravel/framework/commit/d73fe941be7b32c81458f2ce8bf3bf34fe6c5243

**Pull request closed without merging**
