### PR TITLE
Add PubNub event broadcasting

### PR DESCRIPTION
**Pull request by cwt137**
PubNub is a real-time, cloud based event system like Pusher. http://pubnub.com. It would be nice if Laravel supported this system as well. This pull request goes with laravel/framework#8684

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
merge conflicts?

**Comment by cwt137** [comment]
It said that it couldn't auto-merge, but it is a clean to me.

**Comment by lcdss** [comment]
@cwt137 Just missed align "=>" such as in database.php and filesystem.php files.

**Comment by GrahamCampbell** [comment]
You need to rebase without a merge commit please.

**Comment by cwt137** [comment]
I did the rebase

**Comment by GrahamCampbell** [comment]
You seem to have made an error there. There should be exactly one commit here, not multiple unrelated ones.

**Pull request closed without merging**
