### PR TITLE
Add "public" as a supported filesystem driver in docblock

### PR DESCRIPTION
**Pull request by michaeldyrynda**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Isn't public just an instance of the local driver usually?

**Comment by taylorotwell** [comment]
What I mean is it's not an actual driver, it uses the local driver by default.

**Comment by michaeldyrynda** [comment]
Yes, but isn't / shouldn't this be showing the supported (default?) disks?

Perhaps the docblock ought to be updated entirely at that point, seeing as it says `filesystem disk` but the supported examples are drivers.

**Comment by taylorotwell** [comment]
Eh, yeah, it's a little confusing. You can name disks anything you want so it's not like you are tied to only those names. IMO there really doesn't need to be any "supported" list in that comment at all.

**Comment by taylorotwell** [comment]
The supported list would actually be down lower where the disks are defined with a driver.

**Comment by GrahamCampbell** [comment]
👎 This is not a driver name. All names of instances are arbitrary.

**Comment by taylorotwell** [comment]
I fixed this comment in the file to make more sense.

**Comment by michaeldyrynda** [comment]
Much better 🎉

**Pull request closed without merging**
