### PR TITLE
Automatically change the name of the welcome page

### PR DESCRIPTION
**Pull request by khashayarzavosh**
A beginner: I spent a few minutes trying to figure out why the page title doesn't change.

### CODE REVIEW

**Comment by driesvints** [comment]
Feel free to do this in your own app.

**Comment by khashayarzavosh** [comment]
What was the difference between the two?

**Comment by khashayarzavosh** [comment]
> Feel free to do this in your own app.

What was the difference between the two?

**Comment by GrahamCampbell** [comment]
This repo is the default starter app. Your app is yours only.

**Comment by khashayarzavosh** [comment]
> This repo is the default starter app. Your app is yours only.


I know, but I may not want to delete the whole file and edit part of it or try renaming.

**Comment by GrahamCampbell** [comment]
You can do what you want with it.

**Comment by khashayarzavosh** [comment]
> You can do what you want with it.

I know, but it was easier.

**Pull request closed without merging**
