### PR TITLE
ignore maintenance mode `down` file

### PR DESCRIPTION
**Pull request by browner12**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Rejected in #3239.

**Comment by franzliedke** [comment]
Please reconsider. Laravel should take care (as in gitignoring them) of files that it generates.

**Comment by GrahamCampbell** [comment]
It's not up to me to reconsider. Taylor has closed at least one of these before, however, I can leave this open for him again if you want. :)

**Comment by franzliedke** [comment]
:+1:

**Comment by browner12** [comment]
sorry about that. i should have looked to see if this was already an open issue.

i'm curious, what is the thought  behind NOT wanting to add it to `.gitignore`? while it is obviously a very obscure issue, it did happen to me once when i was testing my down template. as such I added it to my personal `.gitignore` file, because i wouldn't want pushing that file to version control to affect my production environment.

**Comment by paulrose** [comment]
Things like maintenance mode shouldn't be dictated by the framework. It's a user choice. The way some people deploy is automated and they wouldn't necessarily login to a server and to a site down command.

This shouldn't be part of the gitignore on a project level, it's a per user choice.

**Comment by GrahamCampbell** [comment]
> Things like maintenance mode shouldn't be dictated by the framework.

It still is the user's choice. This pull request is asking us to change the default for a new laravel project, that's all.

**Comment by taylorotwell** [comment]
I'll just merge for the sake of not bikeshedding forever.

**Pull request merged**
