### PR TITLE
Add an example Route::view

### PR DESCRIPTION
**Pull request by brayniverse**
Maybe this will help reduce the number of Pull Requests you're getting for changing the default route. 😆

### CODE REVIEW

**Comment by kamui545** [comment]
Thanks to those PRs I learned the existence of this feature 😂

**Comment by a-komarev** [comment]
@brayniverse thats the only way to stop this kind of PRs :} Proposed this recently too: https://github.com/laravel/laravel/pull/4400#issuecomment-326396065

**Comment by joshmanders** [comment]
Or just submit a CONTRIBUTING.md file to the repo that is populated into the PR comment box that references 30 of the 500 bajillion PR's stating that it's not going to get accepted.

**Comment by m1guelpf** [comment]
@joshmanders I can see a problem with that:

- How can we add that file, while keeping it away from new laravel installations.

**Comment by joshmanders** [comment]
@m1guelpf put it in `.github` and have a `postinstall` that removes that directory.

**Comment by a-komarev** [comment]
I don't see any problem with adding contributions file, personally I'm adding it in all my repositories. But on practice tiny percent of people reading it.

**Comment by m1guelpf** [comment]
The only think I can see this viable is by creating bot that checks the diff for this change and closes it.

**Comment by m1guelpf** [comment]
Any other way would suppose adding a file to every Laravel installation

**Comment by a-komarev** [comment]
No. You can add `export-ignore CONTIRUBUTING.md` in `.gitattributes` file and it will present only in dev environment.

**Comment by joshmanders** [comment]
^ perfect.

**Pull request closed without merging**
