### PR TITLE
[7.x] Use `Route::view` for the initial route

### PR DESCRIPTION
**Pull request by mitogh**
Define the usage of a view route on the initial view instead of a callback.

### CODE REVIEW

**Comment by sangnguyenplus** [comment]
@mitogh You should check other PRs first https://github.com/laravel/laravel/pulls?q=is%3Apr+route%3A%3Aview
I think you should close this PR by yourself 😄

**Comment by GrahamCampbell** [comment]
Yes, please do check for existing PRs before sending in a PR.

**Comment by akbarjimi** [comment]
> Yes, please do check for existing PRs before sending in a PR.

This request has been made thousands of times, why not merge it once and for all and get rid of it?

**Comment by driesvints** [comment]
@akbarjimi the current example is specifically for newcomers to show how they can use closure based routes. This isn't meant to be optimized.

**Comment by mitogh** [comment]
Sure, thanks @sangnguyenplus

**Pull request closed without merging**
