### PR TITLE
Flexbox update

### PR DESCRIPTION
**Pull request by bart**
Replaced table cell alignment by flexbox

### CODE REVIEW

**Comment by ludo237** [comment]
Are flexbox well supported?

**Comment by pavankumarkatakam** [comment]
Checkout this url http://caniuse.com/#search=flexbox

**Comment by mikerockett** [comment]
I don't see the purpose of this. Who keeps the welcome view anyway? Does it really matter if it uses flexbox?

**Comment by bart** [comment]
In my opinion it would be a good start for some people who don't know it, doesn't it?

**Comment by bart** [comment]
Why did you close my PR @taylorotwell. That's IMO not what community driven development should look like!

**Comment by jonagoldman** [comment]
@bart flexbox is not supported in IE. Besides that, the welcome page is just an example you should be deleting as soon as you start working on your app. Its not a place to show the latest bleeding edge css feaures.

**Comment by ludo237** [comment]
@bart So a community driven development should accept everything beside its real effectiveness only because someone has decide that is the right thing to do? Lmao

**Comment by bart** [comment]
Nope @ludo237 but a bit of discussion would be great instead of instantly closing a pull request!

**Pull request closed without merging**
