### PR TITLE
Added --watch-poll

### PR DESCRIPTION
**Pull request by ilyahoilik**
There is problem with `npm run watch` (webpack doesn't detects a changes) without `--watch-poll`. I use Homestead.

### CODE REVIEW

**Comment by taylorotwell** [comment]
@JeffreyWay thoughts?

**Comment by JeffreyWay** [comment]
File watching is always a little strange with VMs. Some people have no issues, others need to opt for polling. Polling, as I understand it, puts a bit more strain on things, so it probably shouldn't be the default. 

Maybe we can make it more clear in the docs that `--watch-poll` is an alternative. I'll include that with my Mix PR.

**Comment by mlantz** [comment]
Could you not add another script called watch-poll which would leave it built in but as an additive

**Comment by taylorotwell** [comment]
That might be a better option.

**Pull request closed without merging**
