### PR TITLE
The Application name should be on the .env file

### PR DESCRIPTION
**Pull request by rsm23**
Since the .env file holds most of the application’s configurations the
application name also should be there, to be reachable as easy as all
the .env configurations.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Your application name does not change from dev to production.

**Comment by scoutman57** [comment]
I think people don't know what ENV really is suppose to be for. I think
they confuse it with a "application config" file and not a "environment
specific config" file

**Comment by GrahamCampbell** [comment]
Yeh, I totally agree @scoutman57.

**Comment by ejdelmonico** [comment]
Um. I would say that @rsm23 should read about the use of .env variables and the application thereof.

**Pull request closed without merging**
