### PR TITLE
Add url path on app.blade.php

### PR DESCRIPTION
**Pull request by tvalentius**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Duplicate. Already rejected, sorry.

**Comment by tvalentius** [comment]
why not add the url path on the app.blade.php?

**Comment by hfalucas** [comment]
Maybe because L5 doesn't ship anymore with the "illuminate/html" package?

**Comment by GrahamCampbell** [comment]
@hfalucas The URL facade calls a class in the routing package under the hood. Nothing to do with html.

**Pull request closed without merging**
