### PR TITLE
copy .env file as after create project

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Will work on any os.

### CODE REVIEW

**Comment by rowanparker** [comment]
What if people don't want to use the environment file? I assume it's shipped as an example file deliberately, so that it isn't automatically used.

**Comment by hannesvdvreken** [comment]
Oh, I thought it was shipped as an example file because you're not supposed to check your env file in your VCS.

**Comment by GrahamCampbell** [comment]
Oh, it's shipped like that for the reason @hannesvdvreken said. You're meant to be using it.

**Comment by rowanparker** [comment]
Ah ok, I understand. My apologies.

**Comment by hannesvdvreken** [comment]
np

**Pull request merged**
