### PR TITLE
Warn that cache key prefix is ignored on cache flush

### PR DESCRIPTION
**Pull request by tremby**
As discussed in https://github.com/laravel/framework/issues/5034

If you would prefer this to be against a different branch I can rebase.

### CODE REVIEW

**Comment by JosephSilber** [comment]
FWIW, I agree with @tremby. Although we geeks like to pull out the RTFM stick whenever possible, truth is most people don't.

If you're setting a prefix, chances are you'd at least read what's on top of it (or at least more likely than go read the docs).

**Comment by garygreen** [comment]
Wait, `Cache::flush()` get's rid of all cache and ignores the prefix for your app? Wtf, does anyone else find this really odd behavior? To me it should flush just your apps cache, i.e. within it's own namespace/prefix. Sounds more like a bug to be flushing all your other projects caches.
Is this the same behavior in 5.0? If so, I think it should change. Either way I'm +1 to this, was not obvious to me.

**Comment by tremby** [comment]
As far as I know, yes. See https://github.com/laravel/framework/issues/5034
for my original bug report and some discussion.

**Comment by taylorotwell** [comment]
This is more of a documentation concern.

**Pull request closed without merging**
