### PR TITLE
Update RouteServiceProvider.php

### PR DESCRIPTION
**Pull request by Amiir-Dev**
Fix routes problem, during using route commands in command line with php artisan

### CODE REVIEW

**Comment by driesvints** [comment]
This isn't necessarily.

**Comment by Amiir-Dev** [comment]
Many of the people Including myself, have faced this problem : "target-class-testcontroller-does-not-exist"
And also in the laracast people asked this question and whith just this line, it would be fixed.

**Comment by GrahamCampbell** [comment]
@Amiir-Dev look on line 29 of that file and read the comment above it...

**Comment by Amiir-Dev** [comment]
Ok, I'm sorry i didn't see that, so why this is disable when most of the people have problem with that!?

**Pull request closed without merging**
