### PR TITLE
Added title tag

### PR DESCRIPTION
**Pull request by rafaelfs17**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by rafaelfs17** [comment]
Why have you closed? Taylor said to add a period after "back"

**Comment by lukasgeiter** [comment]
@rafaelfs17 But you removed the period and added *"soon"*

**Comment by rafaelfs17** [comment]
@taylorotwell Is it?

**Comment by devfake** [comment]
A period means a dot -> 'Be right back.'

**Comment by rafaelfs17** [comment]
Thank you @devfake

**Pull request closed without merging**
