### PR TITLE
Use stable dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by eduard44** [comment]
So does this mean that Composer would get stable dependencies for everything in the project except for laravel/framework dependencies?

**Comment by Anahkiasen** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
> So does this mean that Composer would get stable dependencies for everything in the project except for laravel/framework dependencies?

No, this means composer will get stable for everything apart from laravel/framework itself. This means people will be running with stable symfony compoents etc.

**Comment by eduard44** [comment]
Nice :+1:

**Comment by deweller** [comment]
Doesn't adding ```@dev ``` mean that laravel will use UNstable dependencies by default?  

Forgive my misunderstanding here.

**Comment by GrahamCampbell** [comment]
No. `'@dev` means get unstable laravel/framework only. The other meant get all dependencies dev.

**Pull request merged**
