### PR TITLE
[5.2] Get guest middleware using guestMiddleware() method in ResetsPasswords

### PR DESCRIPTION
**Pull request by sadika9**
guestMiddleware() defined on ResetsPasswords trait

This change is required to fix issue laravel/framework#13383

Depends on pull request laravel/framework#13384

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @JosephSilber.

**Comment by taylorotwell** [comment]
Just set the value yourself. This controller belong sto the app and is yours to edit freely.

**Comment by taylorotwell** [comment]
This will have to wait until the next framework tag.

**Comment by it-can** [comment]
this can be merged now right?

**Comment by HoangTuanXS** [comment]
Vào Thứ Tư, ngày 18 tháng 5 năm 2016, Taylor Otwell <
notifications@github.com> đã viết:

> Merged #3767 <https://github.com/laravel/laravel/pull/3767>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/laravel/pull/3767#event-664649382>
>


-- 
Được gửi từ Gmail Mobile

**Pull request merged**
