### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by aayushitanwar**

### CODE REVIEW

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0012  You can check the status of or update this ticket online at: http://you.8ball.me

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: 2UhaWovntRYou can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravel, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: j1g4ZjxvdEYou can visit the helpdesk to browse articles and contact us at any time: http://you.8ball.meThank You.Kind Regards, Support Center

**Comment by vijaysebastian** [comment]
Hello laravel/laravelThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0013  You can check the status of or update this ticket online at: http://you.8ball.me

**Comment by JellyBool** [comment]
@taylorotwell just locked this ....

**Pull request closed without merging**
