### PR TITLE
Switching to 5.5

### PR DESCRIPTION
**Pull request by AnandPilania**
update from 5.4 to 5.5

### CODE REVIEW

**Comment by zlodes** [comment]
@AnandPilania wtf?

**Comment by AnandPilania** [comment]
@zlodes : Actually i'm a newbie with github and trying to update forked laravel from 5.4 to 5.5, so I googled about this... SORRY

**Comment by brayniverse** [comment]
Don't worry about it buddy, we have all been newbies at some point :)

**Comment by joshmanders** [comment]
Nothing wrong with being a newbie. I've been doing this for 20 years and still consider myself a newbie. Never stop learning and being better than you previously were. @AnandPilania!

**Comment by matthewlilley** [comment]
What he said.

**Pull request closed without merging**
