### PR TITLE
Encrypt the user password on the model

### PR DESCRIPTION
**Pull request by shadoWalker89**
The logic for how the password is encrypted will be defined in one place.

### CODE REVIEW

**Comment by yoosuf** [comment]
This is not necessarily needed

**Comment by jeroennoten** [comment]
Note that user creation in the `RegisterController` also has to change then: https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L68

**Comment by shadoWalker89** [comment]
Nice catch @jeroennoten, thanks

**Comment by GrahamCampbell** [comment]
Thanks but this has already been proposed and rejected.

**Pull request closed without merging**
