### PR TITLE
[7.x] Add Mailgun and Postmark mailer

### PR DESCRIPTION
**Pull request by mvdnbrk**

### CODE REVIEW

**Comment by crynobone** [comment]
Have a feeling that the documentation is outdated 

https://laravel.com/docs/7.x/mail#introduction

**Comment by driesvints** [comment]
@mvdnbrk can you confirm that the example in the docs isn't working for you?

**Comment by crynobone** [comment]
@driesvints I'm might be confused when the documentation asking to edit `mail.php` or `services.php`.

**Comment by driesvints** [comment]
@crynobone ah yeah, the docs there are for `services.php`.

**Comment by domstubbs** [comment]
For what it’s worth the `postmark.token` config described in [the docs](https://laravel.com/docs/7.x/mail#driver-prerequisites) seems to be outdated. The Postmark plugin [says to use](https://github.com/craigpaul/laravel-postmark/blob/6c59f3ab75d2a6dcfceccac5a8cb380f2d8fc940/UPGRADE.md) `env('POSTMARK_SECRET')` and to remove the Postmark key from services.php altogether.

**Pull request merged**
