### PR TITLE
Change text in title of welcome.blade to include more laravel detail

### PR DESCRIPTION
**Pull request by Damiloju**
I feel the title in the welcome page should display more than just Laravel that it does currently and have changed it to display something like this "Laravel -The PHP Framework For Web Artisans"

I just feel it says more

### CODE REVIEW

**Comment by alexbowers** [comment]
If it should match anything, surely it should match laravel.com one.

That uses a dash not a middot.

**Comment by Damiloju** [comment]
Yes we could change it to a dash then

**Comment by alexbowers** [comment]
There seems to be a double space on each side of the dash

**Comment by Damiloju** [comment]
Yeah. That's how it's on the website

**Comment by alexbowers** [comment]
`<title>Laravel - The PHP Framework For Web Artisans</title>` is the code from Laravel.com

no double space there.

**Comment by mingyoung** [comment]
Does it make sense?

**Comment by Damiloju** [comment]
it's a single space not double space

**Comment by Damiloju** [comment]
@mingyoung i feel so. Just having a laravel on the titile alone does not seem to detailed

**Comment by Damiloju** [comment]
@alexbowers fixed the double space issue it was my sublime that had the issue

**Comment by hesezibaei** [comment]
Laravel was born with love

**Comment by hesezibaei** [comment]
Welcome to laravel land

**Pull request closed without merging**
