### PR TITLE
Add DB_CHARSET and DB_COLLATION to env configuration

### PR DESCRIPTION
**Pull request by ElfSundae**
To store Emoji, the charset of MySQL should be set to  `utf8mb4`.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Is the charset of MySQL specific to the environment?

**Comment by GrahamCampbell** [comment]
Feel free to add this to your own app.

**Comment by ElfSundae** [comment]
No, it is specified to the app, but I think it could be configurated without modifying `config/app.php`

**Comment by RomainLanz** [comment]
It could be configured without changing the configuration file? This is no sense.

`.env` file is only for specific environment things.

**Comment by GrahamCampbell** [comment]
> No, it is specified to the app

If it's app specific, you should not be using an env variable. They are for non-app specific things.

**Comment by ElfSundae** [comment]
OK, thank you to point it.

**Pull request closed without merging**
