### PR TITLE
[6.x] Laravel  Support  php7.4  preload

### PR DESCRIPTION
**Pull request by wujunze**
[6.x] Laravel  Support  php7.4  preload

about issue  https://github.com/laravel/ideas/issues/1406

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This has the disadvantage that you can't upgrade deployed apps by reloading php-fpm, like envoyer does.

**Comment by wujunze** [comment]
> This has the disadvantage that you can't upgrade deployed apps by reloading php-fpm, like envoyer does.

Hello GrahamCampbell : 
    Do you have a better plan ? @GrahamCampbell

**Comment by fragkp** [comment]
@wujunze 
Hey,
I'm interested in why you're ignore FilesystemCache, LogManager and Carbon by default.

**Comment by wujunze** [comment]
> @wujunze
> Hey,
> I'm interested in why you're ignore FilesystemCache, LogManager and Carbon by default.

Hello : 
   I think don't  ignore class

**Comment by GrahamCampbell** [comment]
> Do you have a better plan

I propose we implement this more like the old framework compiled file command, instead of hacking it into laravel/laravel. We must also document the risks, since this is not a simple "turn it on and everything will be faster without consequences".

**Comment by themsaid** [comment]
I agree with @GrahamCampbell. However, I think we can just ship the file with laravel/laravel so people can use it *if* they want.

@wujunze I wonder if you managed to successfully test that it works on an Ubuntu 18.04 setup.

**Comment by deleugpn** [comment]
Coming from a Docker environment, I'm expecting to preload every single file in the application.

**Comment by wujunze** [comment]
> Coming from a Docker environment, I'm expecting to preload every single file in the application.

Your needs can be met

**Comment by themsaid** [comment]
@wujunze did you test this code on a server?

**Comment by GrahamCampbell** [comment]
Why does this need to be included in the default app?

**Comment by GrahamCampbell** [comment]
> Coming from a Docker environment, I'm expecting to preload every single file in the application.

This won't be possible, actually. Preloading requires all classes to be available, and Laravel's source code references classes that need not exist, for example, any of the optional dependencies.

**Comment by taylorotwell** [comment]
Thanks for PR but this contains no benchmark on improvements, it also does not give thought to what classes actually make sense to preload (the "hot" classes) because there is a optimum performance threshold by preloading the hot classes only.

**Pull request closed without merging**
