### PR TITLE
Removed reference to nonexistant Policy

### PR DESCRIPTION
**Pull request by tuxd00d**
'App\Policies\ModelPolicy' does not exist on this branch (or any other at this time).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Maybe just comment that out rather than removing it, so people can still see how to add policies from the code.

**Comment by shehi** [comment]
-1: Agreed with @GrahamCampbell

**Comment by rkgrep** [comment]
:-1: This does not cause any errors

**Comment by taylorotwell** [comment]
It's just an example to show you what the syntax looks like.

**Comment by tuxd00d** [comment]
Leaving it as an example is also a good idea.  @GrahamCampbell 's suggestion of commenting may be helpful.
```php
     protected $policies = [
       //  'App\Model' => 'App\Policies\ModelPolicy',
       //  Post::class => PostPolicy::class,
     ];
```

I felt the pull request was beneficial as the fresh app skeleton does an excellent job ( @taylorotwell ) of being slim and functional out-of-the-box.  Although it doesn't produce an error ( @rkgrep ), this particular line caused me to consider that I botched the upgrade to 5.1.11 because I couldn't find the referenced policy file.  I was hoping to help prevent the same confusion for others.

**Comment by RomainLanz** [comment]
@tuxd00d This is just an example, like the event/listener one.

https://github.com/laravel/laravel/blob/master/app/Providers/EventServiceProvider.php#L15

**Pull request closed without merging**
