### PR TITLE
[5.7] Remove duplication of middleware

### PR DESCRIPTION
**Pull request by pedrofurtado**
@taylorotwell

### CODE REVIEW

**Comment by driesvints** [comment]
Can you give some more info regarding this change?

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by taylorotwell** [comment]
I don't work PRs without explanations.

**Comment by pedrofurtado** [comment]
Sorry guys. I forgot to explain why: This file defines a middleware to be available for routes, named "bindings". It's used by default in "api".
But it is also used in "web". But, different of "api", they use the full-qualified class name of middleware ("Illuminate\Routing\Middleware\SubstituteBindings::class") instead of name "bindings". So , I suggest to remove this duplicate in the file 👍 

let me know if it is ok or if any change is required 🤝

**Comment by ludo237** [comment]
Why not the inverse? I mean why don't use the full-qualified name inside the `api` key? 

I don't think that Kernel need any update on this

**Pull request closed without merging**
