### PR TITLE
Update welcome.blade.php

### PR DESCRIPTION
**Pull request by tamjidmurtoza**
Please update font comment for easy to understand.

### CODE REVIEW

**Comment by MatthewSH** [comment]
This isn't really all that necessary.

**Comment by Mechtecs** [comment]
The fonts means fonts in general and is not limited to "Google Fonts". It should be kept as it is now.

**Comment by ConnorVG** [comment]
A change like this will just make other people PR stuff like:
```diff
diff --git a/resources/views/welcome.blade.php b/resources/views/welcome.blade.php
index 606e59e7e3..51161200b4 100644
--- a/resources/views/welcome.blade.php
+++ b/resources/views/welcome.blade.php
@@ -8,8 +4,8 @@
 
         <title>Laravel</title>
 
-        <!-- Styles -->
+        <!-- CSS Styles -->
         <style>
```

#nothankyou

**Comment by MatthewSH** [comment]
@ConnorVG is absolutely correct. There is no point to specify or expand on the comments that are there. It's simple and straightforward enough. There is no need for further explanation. 

Which begs the question, why am I making this secondary comment if what's needing to be explained has already been explained?

**Pull request closed without merging**
