### PR TITLE
Laracasts contains 2000 video tutorials

### PR DESCRIPTION
**Pull request by SarwarAhmed**

### CODE REVIEW

**Comment by FoksVHox** [comment]
If Laravasts contains 2000 video tutorials, then the old readme is still true, as 1500 < 2000

**Comment by GrahamCampbell** [comment]
Why not just change to "thousands of videos".

**Comment by realodix** [comment]
> Why not just change to "thousands of videos".

I agree. We don't need to pay attention to this, at least until the number of tutorial videos reaches 1,000,000

**Comment by Neeraj1005** [comment]
> Why not just change to "thousands of videos".

either 1500+ (plus)

**Pull request merged**
