### PR TITLE
Move CSRF check to RouteServiceProvider

### PR DESCRIPTION
**Pull request by rkgrep**
However I don't like session middlewares in Kernel, I PR this as mentioned in #3544

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I kind of wonder if this is something that should only be changed on the develop branch?

**Comment by rkgrep** [comment]
This repository is only used for initial installation, so this shouldn't break anything.

**Comment by GrahamCampbell** [comment]
Yeh, but i'm saying maybe we shouldn't have as a default until 5.2.

**Comment by razamehdi-vteams** [comment]
:+1: for this. I believe this should be in the RouteServiceProvider

**Comment by taylorotwell** [comment]
Going to just hold off on this entirely.

**Pull request closed without merging**
