### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by coolpraz**
update laravel mix to new version

### CODE REVIEW

**Comment by RomainLanz** [comment]
Why not using [greekeeper](https://greenkeeper.io/) instead of having every week PR like that?

**Comment by GrahamCampbell** [comment]
If we wanted to just blindly update the version, we could just use a wildcard. I don't see why greenkeeper is useful tbh.

**Comment by RomainLanz** [comment]
It's not blindly update....

Greenkeeper will clone the repository, applies the update, run the test-suite (that we don't have) of the JavaScript code, then create a PR to update the package with all result from the test-suite, changelog of the package, commits from the latest update, etc.

**Comment by GrahamCampbell** [comment]
> Greenkeeper will clone the repository, applies the update, run the test-suite (that we don't have) of the JavaScript code, then create a PR to update the package with all results from the test-suite, changelog of the package, commits from the latest update, etc.

Basically a blind update then. Doesn't do anything to solve the so called PR problem described.

**Comment by RomainLanz** [comment]
The "PR problem" is that someone need to create the PR.

Same goes for all other JS dependencies.
```
"devDependencies": {
  "axios": "^0.15.3",
  "bootstrap-sass": "^3.3.7",
  "jquery": "^3.1.1",
  "laravel-mix": "^0.8.1",
  "lodash": "^4.17.4",
  "vue": "^2.1.10"
}
```

**Pull request merged**
