### PR TITLE
[8.x] type hint the middleware Request

### PR DESCRIPTION
**Pull request by browner12**
stemming from https://github.com/laravel/framework/pull/34224

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe better for 9.x?

**Comment by browner12** [comment]
with `laravel/laravel` it doesn't really matter though, right? since people will only get these changes on brand new projects, or if they choose to manually make the change.

also, there's no "9.x" branch for this repo

**Comment by GrahamCampbell** [comment]
> also, there's no "9.x" branch for this repo

It's called `develop`. ;)

**Comment by browner12** [comment]
ahh duh, forgot about that. thanks!

I'm open to either branch, although my opinion would be it's fine here.

**Pull request merged**
