### PR TITLE
[6.x] Generate a password using the Hash facade

### PR DESCRIPTION
**Pull request by osbre**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. I don't think that's the way passwords are "hashed", though?

**Comment by osbre** [comment]
the previous version saved the result of executing the Hash facade, which allowed to log in under the user's email and password "password"

It works the same way

https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L69

**Comment by GrahamCampbell** [comment]
Ah, I see. The reason for not calling hash was because it takes a long time to execute, and uses memory too.

**Comment by GrahamCampbell** [comment]
This slows down the tests unnecessarily, which is why the hashed value is hard-coded.

**Comment by osbre** [comment]
Thanks for the explanation

**Pull request closed without merging**
