### PR TITLE
Update UserFactory to use Hash facade

### PR DESCRIPTION
**Pull request by JustSteveKing**
This is a bug bear of mine, the default factory assumes that the user is using the `bcrypt` helper - where as with the configuration the ability to change the hashing driver is available. Moving to the Hash Facade here allows for this to be reflected in the default factory.

*note*: This isn't a huge problem for people to change, but if it is available why not use it?

### CODE REVIEW

**Comment by crynobone** [comment]
`composer.lock` shouldn't be part of this PR

**Comment by JustSteveKing** [comment]
@crynobone you are absolutely right there!

**Comment by driesvints** [comment]
Heya thanks but we specifically don't use the hashing here to speed up the factories. Feel free to do this in your own project!

**Comment by JustSteveKing** [comment]
No problems @driesvints 👍

**Pull request closed without merging**
