### PR TITLE
[9.x] Vite 4 support

### PR DESCRIPTION
**Pull request by timacdonald**

### CODE REVIEW

**Comment by flavio-paqt** [comment]
I think it is to early to upgrade to Vite 4, the beta just rolled out.

**Comment by driesvints** [comment]
@flavio-paqt this PR is in draft so not planning to merge it during beta.

**Comment by flavio-paqt** [comment]
> @flavio-paqt this PR is in draft so not planning to merge it during beta.

Never mind, I didn't saw it.

**Comment by fpolli** [comment]
I'm sorry if I am intruding or ignorant, but Vite 4 went public 2 days ago (looks like almost immediately after the last comment here). I'm here because Laravel package.json of 9.43 requires Vite 3.0.0 and I the vite-plugin-svelte from the svelte people requires 4.0.0 and when I tried to install it, npm gave me a peer dependency conflict. Looks like I got caught in a transition. Will this be committed soon? Should I just wait for the next laravel update to continue installing svelte?

**Comment by jessarcher** [comment]
I have tested this with the Laravel Vite plugin PR at https://github.com/laravel/vite-plugin/pull/179 and confirmed it's working. Once we've tag `v0.7.2` of the Vite plugin then this is good to merge.

**Comment by xsjcTony** [comment]
> I have tested this with the Laravel Vite plugin PR at [laravel/vite-plugin#179](https://github.com/laravel/vite-plugin/pull/179) and confirmed it's working. Once we've tag `v0.7.2` of the Vite plugin then this is good to merge.

Appreciate that. Is there any planned release date for `v0.7.2`?

**Pull request merged**
