### PR TITLE
Rename Inspire to InspireCommand to be consistent with core commands

### PR DESCRIPTION
**Pull request by anik786**
Make Inspire consistent with core commands: https://github.com/laravel/framework/tree/5.1/src/Illuminate/Foundation/Console

### CODE REVIEW

**Comment by anik786** [comment]
Why was this merge closed? I thought it was a fair change that made sense and consistent with the rest of the framework.

**Comment by taylorotwell** [comment]
The command suffix is redundant since we're in the commands namespace.

**Comment by anik786** [comment]
Although I agree with you, this is inconsistent with the rest of the framework. 

For example consider the controllers: "AuthController" and "PasswordController" which sits in the "Controller" directory. 

Or consider the "AppServiceProvider", "AuthServiceProvider", "EventServiceProvider", "RouteServiceProvider" in the "Providers" directory.

Therefore I think consistency is more important.

However, with that said I think you have a point and I would suggest removing the words "Provider" and "Controller" from these classes.

**Comment by anik786** [comment]
But consistency beats shorthand

**Comment by taylorotwell** [comment]
No. I am not obligated to name it consistently with the framework core commands, whose class names aren't even exposed to the user, if I no longer feel like that is the best way to name commands.

**Comment by anik786** [comment]
fair enough

**Pull request closed without merging**
