### PR TITLE
Option 2 - put RefreshDatabase into the abstract TestCase

### PR DESCRIPTION
**Pull request by laurencei**
This seems like a better approach - that way all test classes extend the one file, rather than constantly redeclaring it?

### CODE REVIEW

**Comment by KristofMorva** [comment]
I guess it's like that because in some cases you don't want to reset the database - maybe if you have many no-database-touching unit tests to gain performance?

**Comment by fireynis** [comment]
@KristofMorva I think that is exactly why. This is forcing someone to reset their DB, maybe they don't want to do that at all and run tests against a persisting DB.

Right or wrong, forcing them to do it is not better.

**Comment by fletch3555** [comment]
Agreed.  If you do anything about this, it should be Option 1 (#4489), not this.  But I don't really see the benefit to that one either.

**Comment by laurencei** [comment]
Makes sense. I'll let Taylor close it when he decides...

**Comment by rosDNsf** [comment]
@laurencei running the database refreshing in EVERY test is not even close to be a sensible default.

For example, why custom validation rules, hashing classes or third party services which should have independent unit test that don't rely on the database be obligated to pay for the performance hit of the "RefreshDatabase" trait?

> You can still change it to suit your application as needed.

I would say the same to you, if you require to do this just because you don't want to use the trait when it is needed, then do it in your own applications.

**Comment by laurencei** [comment]
ok - fair enough - it was just an idea 😄

**Pull request closed without merging**
