### PR TITLE
add DB_CONNECTION variable in .env.example file

### PR DESCRIPTION
**Pull request by emmanuelgautier**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by shehi** [comment]
As https://github.com/laravel/laravel/blob/master/config/database.php says, it can be optional. Why bother? I think we shouldn't clutter ```.env``` file any more. The bare minimum is the best.

**Comment by lukasgeiter** [comment]
I think instead of adding nearly everything to the example file, it would make sense to have a list of all used environment variables in the docs. @taylorotwell what are your thoughts on that?

**Comment by GrahamCampbell** [comment]
Why do we bother with the mail driver but not the db driver?

**Comment by GrahamCampbell** [comment]
Surely the db driver is more important?

**Comment by shehi** [comment]
Mail driver should only have "log" as default driver and be removed from
example env file.

**Comment by emmanuelgautier** [comment]
I think so @lukasgeiter . Have, at least, env variables used in configuration files is important to know what is possible to configure fastly.

**Comment by adaojunior** [comment]
I agree with @lukasgeiter

**Pull request closed without merging**
