### PR TITLE
Update database.php

### PR DESCRIPTION
**Pull request by aramirez92**
Allow to use Laravel 5.4 with old mysql version.

We can add to our .env file or env vars
DB_CHARSET=utf8
DB_COLLATION=utf8_unicode_ci

Regards.

### CODE REVIEW

**Comment by overtrue** [comment]
👎

**Comment by G-Bruin** [comment]
image

**Comment by RryLee** [comment]
:

**Comment by slow-is-fast** [comment]
why downvote?

2017-04-07 10:19 GMT+08:00 李锐 <notifications@github.com>:

**Comment by taylorotwell** [comment]
You can add this to your own application if you want.

**Comment by GrahamCampbell** [comment]
> Laravel become popular in "utf8 countries", and following the purpose that Laravel is for Artisans, better than that, Worldwide Artisans, would be great to have this config by default.

Config is just that. You are meant to actually edit these files. Environment variables are for things unrelated to your app, that change on a per install basis.

**Pull request closed without merging**
