### PR TITLE
Do not use compiled file for artisan

### PR DESCRIPTION
**Pull request by CurosMJ**
Use `autoload-without-compiled.php` 

This PR fixes https://github.com/laravel/framework/issues/9678

This should also be merged with master also.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why would we not just check if we are running in the console in the autoload file?

**Comment by CurosMJ** [comment]
Because the process would be complex I presume.

**Comment by CurosMJ** [comment]
Another way would be to not depend on `bootstrap/app.php` in the `artisan` file.

**Comment by taylorotwell** [comment]
Here's how you check for CLI usage:

```
return php_sapi_name() == 'cli';
```

**Comment by taylorotwell** [comment]
Closing this for now.

**Pull request closed without merging**
