### PR TITLE
[8.x] Unified asset publishing

### PR DESCRIPTION
**Pull request by finagin**
I propose append and promote use additional tag for publishing js and css assets. And automatically publish them after update packages.
#### Related PRs:
https://github.com/laravel/horizon/pull/1045
https://github.com/laravel/telescope/pull/1105

### CODE REVIEW

**Comment by finagin** [comment]
@taylorotwell, The idea was for third-party packages to use this tag too. But `laravel-assets` will not reflect content.

**Comment by ankurk91** [comment]
May be add `/public/vendor` to `.gitignore`

**Comment by martinbean** [comment]
@taylorotwell Is this not a security vulnerability to blindly publish something based on a tag? As now there’s nothing stopping packages from using this key to publish unwanted files to unwanted locations if every one’s Laravel application is going to call this.

For example:

```php
// Trash someone’s /app directory
$this->publishes([
    __DIR__.'/my-bad-app-dir' => base_path('app'),
], 'laravel-assets');
```

```php
// Install a crypto miner
$this->publishes([
    __DIR__.'/cryptominer' => base_path('app/Console/Commands/MineCrypto.php'),
], 'laravel-assets');

// Publish new console kernel with Crypto miner scheduled for every minute
$this->publishes([
    __DIR__.'/app/Console/Kernel.php' => base_path('app/Console/Kernel.php'),
], 'laravel-assets');
```

**Comment by mikemand** [comment]
This doesn't seem to be working for some reason. I didn't notice until today because I was expecting a change in the assets.

To replicate, create a new Laravel app and install an older version of Horizon and/or Telescope (I used Horizon for my test since there was a release today), then update to the latest version of either package:

```bash
laravel new asset-test && cd asset-test
```

```bash
composer require laravel/horizon:5.7.15
```

Assets were published automatically after Horizon was installed - yay! Now change the version requirement in `composer.json` to `^5.7` and update:

```bash
composer update
```

Assets were not published, even though they were changed in the new version of Horizon. The console says they were published, but nothing happened:

```
> @php artisan vendor:publish --tag=laravel-assets --ansi
Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]
```

So, let's run the same command:

```bash
php artisan vendor:publish --tag=laravel-assets
```

Nope, didn't work while running manually. Have to publish them from the package itself:

```bash
php artisan horizon:publish
```

Now they are updated... The output of the command is exactly the same as the `vendor:publish` one, so I don't know what is going on. Here's a sample repo: https://github.com/mikemand/laravel-asset-test Each commit is one of the steps above.

**Comment by mikemand** [comment]
Perfect, @sebdesign. With your permission, I'll PR this fix here.

**Pull request merged**
