### PR TITLE
[7.x] Add missing return statement

### PR DESCRIPTION
**Pull request by u01jmg3**
- Add missing return statement

### CODE REVIEW

**Comment by u01jmg3** [comment]
PHPStan:

```
Method App\Http\Middleware\Authenticate::redirectTo() should return string|null but return statement is missing.
```

**Comment by u01jmg3** [comment]
Bit confused why this commit was accepted 40f93da when the [`route()`](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/helpers.php#L764) helper doesn't return `null` 🤷‍♂️

**Comment by u01jmg3** [comment]
@mingyoung, @marky291: a bit confused why this commit was accepted 40f93da when the [`route()`](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/helpers.php#L764) helper doesn't return `null` 🤷‍♂️

**Comment by GrahamCampbell** [comment]
Because not returning anything **does** return null. Try it out.

**Comment by u01jmg3** [comment]
Thanks for clarifying and I get that. Should PHPStan know better then?

**Comment by GrahamCampbell** [comment]
No, PHPStan is making you be explicit to ensure the code does what you intended. You can update your own app to be explicit if you like, or ignore the warning.

**Comment by u01jmg3** [comment]
Thanks @GrahamCampbell!

**Pull request closed without merging**
