### PR TITLE
Add middleware to force https protocol

### PR DESCRIPTION
**Pull request by ricardogobbosouza**

### CODE REVIEW

**Comment by driesvints** [comment]
This should probably be handled at the web server level or through a service like Cloudflare. Otherwise, feel free to release this as a package. Thanks.

**Comment by GrahamCampbell** [comment]
Yeh, there's loads of resources online for how to do this in apache or nginx, for example.

**Comment by ricardogobbosouza** [comment]
Yes, without a doubt, this would be an alternative, many projects that are executed in shared hosting do not have access to such configurations

**Comment by ricardogobbosouza** [comment]
So I left it disabled by default.

**Comment by ricardogobbosouza** [comment]
Maybe we could have a section in the documentation explaining about https

**Comment by GrahamCampbell** [comment]
That is not really a concern for the framework, and indeed, I'd recommend not ever doing that sort of thing in the framework, unless you are particularly careful. For example, you don't want to accidentality leak a session cookie over HTTP.

**Pull request closed without merging**
