### PR TITLE
Replaced callback to retrieve welcome view with the Route::view method

### PR DESCRIPTION
**Pull request by Bcryp7**

### CODE REVIEW

**Comment by brunogaspar** [comment]
Hey @Bcryp7 

Unfortunately, this change was attempted many many times before and was denied pretty much every single time.

I'm surprised that the Laravel pull request army haven't replied to you yet with all the duplicated pull requests links :)

But basically https://github.com/laravel/laravel/search?q=Route%3A%3Aview%28%27%2F%27%2C+%27welcome%27%29%3B&type=Issues

**Comment by laurencei** [comment]
I've mentioned it once before - but might be worth doing this just to stop the PRs coming in.

```
Route::get('/', 'welcome');
    return view('welcome');
});

// Route::view('/', 'welcome');
```

There's lots of places in `laravel/laravel` with commented out code showing examples of what can be done there - so it seems reasonable to do this here.

**Comment by Bcryp7** [comment]
Thanks everyone for your replies. I missed those PRs. I just submitted because it kind of bothers the eye and I change it in every project, plus it's much cleaner and readable. Let's see what happens, thanks guys.

**Comment by taylorotwell** [comment]
I always leave the Closure there because it's a convenient spot to hack around and test something on a fresh project without having to create a controller, etc.

**Pull request closed without merging**
