### PR TITLE
Removing @return void annotation on constructor

### PR DESCRIPTION
**Pull request by denjaland**
Scrutinizer (and probably other code quality verifiers) mark these as a minor issue.
As a constructor never returns a value, I thought it'd be nice to have these annotations removed indeed.

### CODE REVIEW

**Comment by carkii** [comment]
I believe that, this return help the user how to use the function perfectly.

For me, it very useful and no matters what Scrutinizer believes:)

**Comment by GrahamCampbell** [comment]
Yes, the void annotations are intended.

**Comment by denjaland** [comment]
Ok fair enough - I would never put it on a constructor myself to be honest; that is just part of php language; ANY developer should know a constructor doesn't return anything...  

For your own methods, I agree it gives better hints for the developers using it.

**Comment by denjaland** [comment]
I was just thinking about this again, and how I would never do it, but I was in fact wrong.
I believe you should update the annotations to return SELF actually.

Because the result of any constructor is that it creates an object of the class it belongs to, and returns it so it is placed inside the variable.

Looking at https://phpdoc.org/docs/latest/references/phpdoc/tags/return.html, it actually confirms that maybe you need to update it for your constructors to make it more correct - if you insist on keeping the annotation there :-)

**Comment by GrahamCampbell** [comment]
phpdoc.org is wrong i'm afraid. They are just functions like any other, and they return whatever you actually return in them. (feel free to try this out)

Note however, that this did change in php 7.1, though, phpdoc.org defintely didn't use that definition because of that, it just got it wrong.

**Pull request closed without merging**
