### PR TITLE
[5.7] get to view on routes web.php

### PR DESCRIPTION
**Pull request by narwy**
Updated route option as per documentation:
https://laravel.com/docs/5.7/routing#view-routes

### CODE REVIEW

**Comment by fagai** [comment]
#4681

**Comment by narwy** [comment]
I heard it might get merged and not closed in 5.7 ;)

**Comment by m1guelpf** [comment]
#4598
#4569
#4498
#4481
#4443
#4439
#4437
#4424
#4410
#4403
#4401
#4400
#4398
#4396
#4395
#4391
#4386
#4381
#4378
#4367
#4310

...

**Comment by laurencei** [comment]
It's clearly a thing. Maybe we do:

```
    Route::view('/', 'welcome');
         return view('welcome');
    });

    // Route::view('/', 'welcome');
```

Then it shows it can be one or the other, and stop this PR from occurring again... 😄

**Comment by narwy** [comment]
> #4598
> #4569
> #4498
> #4481
> #4443
> #4439
> #4437
> #4424
> #4410
> #4403
> #4401
> #4400
> #4398
> #4396
> #4395
> #4391
> #4386
> #4381
> #4378
> #4367
> #4310
> 
> ...

Nice copy and paste from @fagai 's link :)

**Comment by connectkushal** [comment]
i had the same thoughts on putting a commented code in the routes file just so that such pr's stop coming up. But then it becomes more confusing for the new user unless you write a small description as well. But how much will you explain, do you point it to the docs ? Do you touch upon passing variables to view ? 
Also does one ignore the possibility that the new user will uncomment the code without deleting the closure, having duplicate route entries. Do you put a warning ? 

Ultimately i closed it as it seems just too futile. IMO This should be closed like the other pr's.

**Comment by ludo237** [comment]
Please stop with these kind of PRs, ask yourself if this is really adding new value to Laravel

Spoiler alert: it's not.

**Comment by narwy** [comment]
@ludo237 I feel like contributing this PR I am helping people who are new to MVC understand there are functions that have been built to allow using less lines of code. I can see your a spaces instead of tabs kind of guy.

**Comment by driesvints** [comment]
Please stop sending these in.

**Comment by narwy** [comment]
@driesvints That's for your super details contribution to the PR.

**Comment by driesvints** [comment]
@narwy as you can see numerous PRs about this have been closed in the past. After more than 30 PRs you should realize that this isn't going to get merged.

**Comment by narwy** [comment]
@driesvints It's obviously not going to be merged if it's not discussed about and just closed. @laurencei had a decent input and then you came along and closed it, high five.

**Comment by driesvints** [comment]
Please use https://github.com/laravel/ideas if you want to discuss something like this.

We also have the docs which explains these alternative usages (and is probably the place where people discover them in the first place). We could start adding more of these "alternative" usages for other functionality as well to the skeleton but that will only bloat the skeleton even further.

I'm going to close this down because this has been rejected so much now that I don't believe it will be merged anytime soon. Please open an issue with the ideas repo if you want to add this and get some input and support there if you really want to see this get merged in.

**Pull request closed without merging**
