### PR TITLE
Make sessions more accessible from .env

### PR DESCRIPTION
**Pull request by fwartner**
This will make the session configuration more flexible using the .env file.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No need to add this by default I think.

**Comment by fwartner** [comment]
I often came into a situation were i need to edit these variables directly in the config files.. Becomes sometimes a pain..

**Comment by GrahamCampbell** [comment]
> I often came into a situation were i need to edit these variables directly in the config files.. Becomes sometimes a pain..

Editing the config file is the default option, and that's not a bad thing. The environment variables should only be used for secrets, or things that change per environment. Things that are the same in your application should be set by editing the config files.

**Comment by fwartner** [comment]
You are talking about "secrets"..

```
BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database
```

Are these lines (all of them are by *default* in the .env file) some sort of "secrets"? ^^

**Comment by GrahamCampbell** [comment]
> You are talking about "secrets"..

I didn't say just secrets. I said:

> used for secrets, or things that change per environment.

**Comment by taylorotwell** [comment]
You can add this to your own app as needed.

**Pull request closed without merging**
