### PR TITLE
Adding nova folder to .gitignore

### PR DESCRIPTION
**Pull request by arcanedev-maroc**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why?

**Comment by CaddyDz** [comment]
So no one accidentally publish it on an open source repository I guess

**Comment by arcanedev-maroc** [comment]
To avoid [this issue](https://twitter.com/themsaid/status/1032540011567173632)

**Comment by CaddyDz** [comment]
It has already happened :man_facepalming: 
https://github.com/search?q=%22laravel%2Fnova%22%3A+%22%2A%22&type=Code

**Pull request closed without merging**
